.TH "Flatted" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flatted
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBparse\fP ($json, $assoc=false, $depth=512, $options=0)"
.br
.ti -1c
.RI "static \fBstringify\fP ($value, $options=0, $depth=512)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
