.TH "md_frontend_2node__modules_2_0dremix-run_2router_2_c_h_a_n_g_e_l_o_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2_0dremix-run_2router_2_c_h_a_n_g_e_l_o_g \- \fR@remix-run/router\fP 
.PP

.SH "1\&.23\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add \fRfetcherKey\fP as a parameter to \fRpatchRoutesOnNavigation\fP (\fR#13109\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix regression introduced in \fR6\&.29\&.0\fP via \fR#12169\fP that caused issues navigating to hash routes inside splat routes for applications using Lazy Route Discovery (\fRpatchRoutesOnNavigation\fP) (\fR#13108\fP)
.PP
.SH "1\&.22\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Provide the request \fRsignal\fP as a parameter to \fRpatchRoutesOnNavigation\fP (\fR#12900\fP)
.IP "  \(bu" 4
This can be used to abort any manifest fetches if the in-flight navigation/fetcher is aborted
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Do not log v7 deprecation warnings in production builds (\fR#12794\fP)
.IP "\(bu" 2
Strip search parameters from \fRpatchRoutesOnNavigation\fP \fRpath\fP param for fetcher calls (\fR#12899\fP)
.IP "\(bu" 2
Properly bubble headers when throwing a \fRdata()\fP result (\fR#12845\fP)
.IP "\(bu" 2
Optimize route matching by skipping redundant \fRmatchRoutes\fP calls when possible (\fR#12169\fP)
.PP
.SH "1\&.21\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
- Fix issue with fetcher data cleanup in the data layer on fetcher unmount (\fR#12674\fP)
.IP "  \(bu" 4
Fix behavior of manual fetcher keys when not opted into \fRfuture\&.v7_fetcherPersist\fP
.PP

.PP
.SH "1\&.21\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
- Log deprecation warnings for v7 flags (\fR#11750\fP)
.IP "  \(bu" 4
Add deprecation warnings to \fRjson\fP/\fRdefer\fP in favor of returning raw objects
.IP "    \(bu" 6
These methods will be removed in React Router v7
.PP

.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Update JSDoc URLs for new website structure (add /v6/ segment) (\fR#12141\fP)
.PP
.SH "1\&.20\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Stabilize \fRunstable_patchRoutesOnNavigation\fP (\fR#11973\fP)
.IP "  \(bu" 4
Add new \fRPatchRoutesOnNavigationFunctionArgs\fP type for convenience (\fR#11967\fP)
.PP

.IP "\(bu" 2
Stabilize \fRunstable_dataStrategy\fP (\fR#11974\fP)
.IP "\(bu" 2
Stabilize the \fRunstable_flushSync\fP option for navigations and fetchers (\fR#11989\fP)
.IP "\(bu" 2
Stabilize the \fRunstable_viewTransition\fP option for navigations and the corresponding \fRunstable_useViewTransitionState\fP hook (\fR#11989\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix bug when submitting to the current contextual route (parent route with an index child) when an \fR?index\fP param already exists from a prior submission (\fR#12003\fP)
.IP "\(bu" 2
Fix \fRuseFormAction\fP bug - when removing \fR?index\fP param it would not keep other non-Remix \fRindex\fP params (\fR#12003\fP)
.IP "\(bu" 2
Fix bug with fetchers not persisting \fRpreventScrollReset\fP through redirects during concurrent fetches (\fR#11999\fP)
.IP "\(bu" 2
Remove internal cache to fix issues with interrupted \fRpatchRoutesOnNavigation\fP calls (\fR#12055\fP)
.IP "  \(bu" 4
We used to cache in-progress calls to \fRpatchRoutesOnNavigation\fP internally so that multiple navigations with the same start/end would only execute the function once and use the same promise
.IP "  \(bu" 4
However, this approach was at odds with \fRpatch\fP short circuiting if a navigation was interrupted (and the \fRrequest\&.signal\fP aborted) since the first invocation's \fRpatch\fP would no-op
.IP "  \(bu" 4
This cache also made some assumptions as to what a valid cache key might be - and is oblivious to any other application-state changes that may have occurred
.IP "  \(bu" 4
So, the cache has been removed because in \fImost\fP cases, repeated calls to something like \fRimport()\fP for async routes will already be cached automatically - and if not it's easy enough for users to implement this cache in userland
.PP

.IP "\(bu" 2
Avoid unnecessary \fRconsole\&.error\fP on fetcher abort due to back-to-back revalidation calls (\fR#12050\fP)
.IP "\(bu" 2
Expose errors thrown from \fRpatchRoutesOnNavigation\fP directly to \fRuseRouteError\fP instead of wrapping them in a 400 \fRErrorResponse\fP instance (\fR#12111\fP)
.IP "\(bu" 2
Fix types for \fRRouteObject\fP within \fRPatchRoutesOnNavigationFunction\fP's \fRpatch\fP method so it doesn't expect agnostic route objects passed to \fRpatch\fP (\fR#11967\fP)
.IP "\(bu" 2
Fix bugs with \fRpartialHydration\fP when hydrating with errors (\fR#12070\fP)
.IP "\(bu" 2
Remove internal \fRdiscoveredRoutes\fP FIFO queue from \fRunstable_patchRoutesOnNavigation\fP (\fR#11977\fP)
.PP
.SH "1\&.19\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Update the \fRunstable_dataStrategy\fP API to allow for more advanced implementations (\fR#11943\fP)
.IP "  \(bu" 4
Rename \fRunstable_HandlerResult\fP to \fRunstable_DataStrategyResult\fP
.IP "  \(bu" 4
The return signature has changed from a parallel array of \fRunstable_DataStrategyResult[]\fP (parallel to \fRmatches\fP) to a key/value object of \fRrouteId => unstable_DataStrategyResult\fP
.IP "    \(bu" 6
This allows you to more easily decide to opt-into or out-of revalidating data that may not have been revalidated by default (via \fRmatch\&.shouldLoad\fP)
.IP "    \(bu" 6
⚠️ This is a breaking change if you've currently adopted \fRunstable_dataStrategy\fP
.PP

.IP "  \(bu" 4
Added a new \fRfetcherKey\fP parameter to \fRunstable_dataStrategy\fP to allow differentiation from navigational and fetcher calls
.IP "  \(bu" 4
You should now return/throw a result from your \fRhandlerOverride\fP instead of returning a \fRDataStrategyResult\fP
.IP "    \(bu" 6
If you are aggregating the results of \fRmatch\&.resolve()\fP into a final results object you should not need to think about the \fRDataStrategyResult\fP type
.IP "    \(bu" 6
If you are manually filling your results object from within your \fRhandlerOverride\fP, then you will need to assign a \fRDataStrategyResult\fP as the value so React Router knows if it's a successful execution or an error\&.
.PP

.PP

.IP "\(bu" 2
Preserve view transition through redirects (\fR#11925\fP)
.IP "\(bu" 2
Fix blocker usage when \fRblocker\&.proceed\fP is called quickly/synchronously (\fR#11930\fP)
.IP "\(bu" 2
Preserve pending view transitions through a router revalidation call (\fR#11917\fP)
.PP
.SH "1\&.19\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fog of War: Update \fRunstable_patchRoutesOnMiss\fP logic so that we call the method when we match routes with dynamic param or splat segments in case there exists a higher-scoring static route that we've not yet discovered\&. (\fR#11883\fP)
.IP "  \(bu" 4
We also now leverage an internal FIFO queue of previous paths we've already called \fRunstable_patchRouteOnMiss\fP against so that we don't re-call on subsequent navigations to the same path
.PP

.IP "\(bu" 2
Rename \fRunstable_patchRoutesOnMiss\fP to \fRunstable_patchRoutesOnNavigation\fP to match new behavior (\fR#11888\fP)
.PP
.SH "1\&.19\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add a new \fRreplace(url, init?)\fP alternative to \fRredirect(url, init?)\fP that performs a \fRhistory\&.replaceState\fP instead of a \fRhistory\&.pushState\fP on client-side navigation redirects (\fR#11811\fP)
.IP "\(bu" 2
Add a new \fRunstable_data()\fP API for usage with Remix Single Fetch (\fR#11836\fP)
.IP "  \(bu" 4
This API is not intended for direct usage in React Router SPA applications
.IP "  \(bu" 4
It is primarily intended for usage with \fRcreateStaticHandler\&.query()\fP to allow loaders/actions to return arbitrary data + \fRstatus\fP/\fRheaders\fP without forcing the serialization of data into a \fRResponse\fP instance
.IP "  \(bu" 4
This allows for more advanced serialization tactics via \fRunstable_dataStrategy\fP such as serializing via \fRturbo-stream\fP in Remix Single Fetch
.IP "  \(bu" 4
⚠️ This removes the \fRstatus\fP field from \fRHandlerResult\fP
.IP "    \(bu" 6
If you need to return a specific \fRstatus\fP from \fRunstable_dataStrategy\fP you should instead do so via \fRunstable_data()\fP
.PP

.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix internal cleanup of interrupted fetchers to avoid invalid revalidations on navigations (\fR#11839\fP)
.IP "  \(bu" 4
When a \fRfetcher\&.load\fP is interrupted by an \fRaction\fP submission, we track it internally and force revalidation once the \fRaction\fP completes
.IP "  \(bu" 4
We previously only cleared out this internal tracking info on a successful \fInavigation\fP submission
.IP "  \(bu" 4
Therefore, if the \fRfetcher\&.load\fP was interrupted by a \fRfetcher\&.submit\fP, then we wouldn't remove it from this internal tracking info on successful load (incorrectly)
.IP "  \(bu" 4
And then on the next navigation it's presence in the internal tracking would automatically trigger execution of the \fRfetcher\&.load\fP again, ignoring any \fRshouldRevalidate\fP logic
.IP "  \(bu" 4
This fix cleans up the internal tracking so it applies to both navigation submission and fetcher submissions
.PP

.IP "\(bu" 2
Fix initial hydration behavior when using \fRfuture\&.v7_partialHydration\fP along with \fRunstable_patchRoutesOnMiss\fP (\fR#11838\fP)
.IP "  \(bu" 4
During initial hydration, \fRrouter\&.state\&.matches\fP will now include any partial matches so that we can render ancestor \fRHydrateFallback\fP components
.PP

.PP
.SH "1\&.18\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Stabilize \fRfuture\&.unstable_skipActionErrorRevalidation\fP as \fRfuture\&.v7_skipActionErrorRevalidation\fP (\fR#11769\fP)
.IP "  \(bu" 4
When this flag is enabled, actions will not automatically trigger a revalidation if they return/throw a \fRResponse\fP with a \fR4xx\fP/\fR5xx\fP status code
.IP "  \(bu" 4
You may still opt-into revalidation via \fRshouldRevalidate\fP
.IP "  \(bu" 4
This also changes \fRshouldRevalidate\fP's \fRunstable_actionStatus\fP parameter to \fRactionStatus\fP
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix bubbling of errors thrown from \fRunstable_patchRoutesOnMiss\fP (\fR#11786\fP)
.IP "\(bu" 2
Fix hydration in SSR apps using \fRunstable_patchRoutesOnMiss\fP that matched a splat route on the server (\fR#11790\fP)
.PP
.SH "1\&.17\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fog of War (unstable): Trigger a new \fRrouter\&.routes\fP identity/reflow during route patching (\fR#11740\fP)
.IP "\(bu" 2
Fog of War (unstable): Fix initial matching when a splat route matches (\fR#11759\fP)
.PP
.SH "1\&.17\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add support for Lazy Route Discovery (a\&.k\&.a\&. Fog of War) (\fR#11626\fP)
.IP "  \(bu" 4
RFC: https://github.com/remix-run/react-router/discussions/11113
.IP "  \(bu" 4
\fRunstable_patchRoutesOnMiss\fP docs: https://reactrouter.com/v6/routers/create-browser-router
.PP

.PP
.SH "1\&.16\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Support \fRunstable_dataStrategy\fP on \fRstaticHandler\&.queryRoute\fP (\fR#11515\fP)
.PP
.SH "1\&.16\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add a new \fRunstable_dataStrategy\fP configuration option (\fR#11098\fP)
.IP "  \(bu" 4
This option allows Data Router applications to take control over the approach for executing route loaders and actions
.IP "  \(bu" 4
The default implementation is today's behavior, to fetch all loaders in parallel, but this option allows users to implement more advanced data flows including Remix single-fetch, middleware/context APIs, automatic loader caching, and more
.PP

.IP "\(bu" 2
Move \fRunstable_dataStrategy\fP from \fRcreateStaticHandler\fP to \fRstaticHandler\&.query\fP so it can be request-specific for use with the \fRResponseStub\fP approach in Remix\&. It's not really applicable to \fRqueryRoute\fP for now since that's a singular handler call anyway so any pre-processing/post/processing could be done there manually\&. (\fR#11377\fP)
.IP "\(bu" 2
Add a new \fRfuture\&.unstable_skipActionRevalidation\fP future flag (\fR#11098\fP)
.IP "  \(bu" 4
Currently, active loaders revalidate after any action, regardless of the result
.IP "  \(bu" 4
With this flag enabled, actions that return/throw a 4xx/5xx response status will no longer automatically revalidate
.IP "  \(bu" 4
This should reduce load on your server since it's rare that a 4xx/5xx should actually mutate any data
.IP "  \(bu" 4
If you need to revalidate after a 4xx/5xx result with this flag enabled, you can still do that via returning \fRtrue\fP from \fRshouldRevalidate\fP
.IP "  \(bu" 4
\fRshouldRevalidate\fP now also receives a new \fRunstable_actionStatus\fP argument alongside \fRactionResult\fP so you can make decision based on the status of the \fRaction\fP response without having to encode it into the action data
.PP

.IP "\(bu" 2
Added a \fRskipLoaderErrorBubbling\fP flag to \fRstaticHandler\&.query\fP to disable error bubbling on loader executions for single-fetch scenarios where the client-side router will handle the bubbling (\fR#11098\fP)
.PP
.SH "1\&.15\&.3"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix a \fRfuture\&.v7_partialHydration\fP bug that would re-run loaders below the boundary on hydration if SSR loader errors bubbled to a parent boundary (\fR#11324\fP)
.IP "\(bu" 2
Fix a \fRfuture\&.v7_partialHydration\fP bug that would consider the router uninitialized if a route did not have a loader (\fR#11325\fP)
.PP
.SH "1\&.15\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Preserve hydrated errors during partial hydration runs (\fR#11305\fP)
.PP
.SH "1\&.15\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix encoding/decoding issues with pre-encoded dynamic parameter values (\fR#11199\fP)
.PP
.SH "1\&.15\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add a \fRcreateStaticHandler\fP \fRfuture\&.v7_throwAbortReason\fP flag to throw \fRrequest\&.signal\&.reason\fP (defaults to a \fRDOMException\fP) when a request is aborted instead of an \fRError\fP such as \fRnew Error("query() call aborted: GET /path")\fP (\fR#11104\fP)
.IP "  \(bu" 4
Please note that \fRDOMException\fP was added in Node v17 so you will not get a \fRDOMException\fP on Node 16 and below\&.
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Respect the \fRErrorResponse\fP status code if passed to \fRgetStaticContextFormError\fP (\fR#11213\fP)
.PP
.SH "1\&.14\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix bug where dashes were not picked up in dynamic parameter names (\fR#11160\fP)
.IP "\(bu" 2
Do not attempt to deserialize empty JSON responses (\fR#11164\fP)
.PP
.SH "1\&.14\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix bug with \fRroute\&.lazy\fP not working correctly on initial SPA load when \fRv7_partialHydration\fP is specified (\fR#11121\fP)
.IP "\(bu" 2
Fix bug preventing revalidation from occurring for persisted fetchers unmounted during the \fRsubmitting\fP phase (\fR#11102\fP)
.IP "\(bu" 2
De-dup relative path logic in \fRresolveTo\fP (\fR#11097\fP)
.PP
.SH "1\&.14\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Added a new \fRfuture\&.v7_partialHydration\fP future flag that enables partial hydration of a data router when Server-Side Rendering\&. This allows you to provide \fRhydrationData\&.loaderData\fP that has values for \fIsome\fP initially matched route loaders, but not all\&. When this flag is enabled, the router will call \fRloader\fP functions for routes that do not have hydration loader data during \fRrouter\&.initialize()\fP, and it will render down to the deepest provided \fRHydrateFallback\fP (up to the first route without hydration data) while it executes the unhydrated routes\&. (\fR#11033\fP)

.PP
For example, the following router has a \fRroot\fP and \fRindex\fP route, but only provided \fRhydrationData\&.loaderData\fP for the \fRroot\fP route\&. Because the \fRindex\fP route has a \fRloader\fP, we need to run that during initialization\&. With \fRfuture\&.v7_partialHydration\fP specified, \fR<RouterProvider>\fP will render the \fRRootComponent\fP (because it has data) and then the \fRIndexFallback\fP (since it does not have data)\&. Once \fRindexLoader\fP finishes, application will update and display \fRIndexComponent\fP\&.

.PP
.PP
.nf
let router = createBrowserRouter(
  [
    {
      id: "root",
      path: "/",
      loader: rootLoader,
      Component: RootComponent,
      Fallback: RootFallback,
      children: [
        {
          id: "index",
          index: true,
          loader: indexLoader,
          Component: IndexComponent,
          HydrateFallback: IndexFallback,
        },
      ],
    },
  ],
  {
    future: {
      v7_partialHydration: true,
    },
    hydrationData: {
      loaderData: {
        root: { message: "Hydrated from Root!" },
      },
    },
  }
);
.fi
.PP

.PP
If the above example did not have an \fRIndexFallback\fP, then \fRRouterProvider\fP would instead render the \fRRootFallback\fP while it executed the \fRindexLoader\fP\&.

.PP
\fBNote:\fP When \fRfuture\&.v7_partialHydration\fP is provided, the \fR<RouterProvider fallbackElement>\fP prop is ignored since you can move it to a \fRFallback\fP on your top-most route\&. The \fRfallbackElement\fP prop will be removed in React Router v7 when \fRv7_partialHydration\fP behavior becomes the standard behavior\&.
.IP "\(bu" 2
Add a new \fRfuture\&.v7_relativeSplatPath\fP flag to implement a breaking bug fix to relative routing when inside a splat route\&. (\fR#11087\fP)

.PP
This fix was originally added in \fR#10983\fP and was later reverted in \fR#11078\fP because it was determined that a large number of existing applications were relying on the buggy behavior (see \fR#11052\fP)

.PP
\fBThe Bug\fP The buggy behavior is that without this flag, the default behavior when resolving relative paths is to \fIignore\fP any splat (\fR*\fP) portion of the current route path\&.

.PP
\fBThe Background\fP This decision was originally made thinking that it would make the concept of nested different sections of your apps in \fR<Routes>\fP easier if relative routing would \fIreplace\fP the current splat:

.PP
.PP
.nf
<BrowserRouter>
  <Routes>
    <Route path="/" element={<Home />} />
    <Route path="dashboard/*" element={<Dashboard />} />
  </Routes>
</BrowserRouter>
.fi
.PP

.PP
Any paths like \fR/dashboard\fP, \fR/dashboard/team\fP, \fR/dashboard/projects\fP will match the \fRDashboard\fP route\&. The dashboard component itself can then render nested \fR<Routes>\fP:

.PP
.PP
.nf
function Dashboard() {
  return (
    <div>
      <h2>Dashboard</h2>
      <nav>
        <Link to="/">Dashboard Home</Link>
        <Link to="team">Team</Link>
        <Link to="projects">Projects</Link>
      </nav>

      <Routes>
        <Route path="/" element={<DashboardHome />} />
        <Route path="team" element={<DashboardTeam />} />
        <Route path="projects" element={<DashboardProjects />} />
      </Routes>
    </div>
  );
}
.fi
.PP

.PP
Now, all links and route paths are relative to the router above them\&. This makes code splitting and compartmentalizing your app really easy\&. You could render the \fRDashboard\fP as its own independent app, or embed it into your large app without making any changes to it\&.

.PP
\fBThe Problem\fP

.PP
The problem is that this concept of ignoring part of a path breaks a lot of other assumptions in React Router - namely that \fR"\&."\fP always means the current location pathname for that route\&. When we ignore the splat portion, we start getting invalid paths when using \fR"\&."\fP:

.PP
.PP
.nf
// If we are on URL /dashboard/team, and we want to link to /dashboard/team:
function DashboardTeam() {
  // ❌ This is broken and results in <a href="/dashboard">
  return <Link to="\&.">A broken link to the Current URL</Link>;

  // ✅ This is fixed but super unintuitive since we're already at /dashboard/team!
  return <Link to="\&./team">A broken link to the Current URL</Link>;
}
.fi
.PP

.PP
We've also introduced an issue that we can no longer move our \fRDashboardTeam\fP component around our route hierarchy easily - since it behaves differently if we're underneath a non-splat route, such as \fR/dashboard/:widget\fP\&. Now, our \fR"\&."\fP links will, properly point to ourself \fIinclusive of the dynamic param value\fP so behavior will break from it's corresponding usage in a \fR/dashboard/*\fP route\&.

.PP
Even worse, consider a nested splat route configuration:

.PP
.PP
.nf
<BrowserRouter>
  <Routes>
    <Route path="dashboard">
      <Route path="*" element={<Dashboard />} />
    </Route>
  </Routes>
</BrowserRouter>
.fi
.PP

.PP
Now, a \fR<Link to="\&.">\fP and a \fR<Link to="\&.\&.">\fP inside the \fRDashboard\fP component go to the same place! That is definitely not correct!

.PP
Another common issue arose in Data Routers (and Remix) where any \fR<Form>\fP should post to it's own route \fRaction\fP if you the user doesn't specify a form action:

.PP
.PP
.nf
let router = createBrowserRouter({
  path: "/dashboard",
  children: [
    {
      path: "*",
      action: dashboardAction,
      Component() {
        // ❌ This form is broken!  It throws a 405 error when it submits because
        // it tries to submit to /dashboard (without the splat value) and the parent
        // `/dashboard` route doesn't have an action
        return <Form method="post">\&.\&.\&.</Form>;
      },
    },
  ],
});
.fi
.PP

.PP
This is just a compounded issue from the above because the default location for a \fRForm\fP to submit to is itself (\fR"\&."\fP) - and if we ignore the splat portion, that now resolves to the parent route\&.

.PP
\fBThe Solution\fP If you are leveraging this behavior, it's recommended to enable the future flag, move your splat to it's own route, and leverage \fR\&.\&./\fP for any links to "sibling" pages:

.PP
.PP
.nf
<BrowserRouter>
  <Routes>
    <Route path="dashboard">
      <Route index path="*" element={<Dashboard />} />
    </Route>
  </Routes>
</BrowserRouter>

function Dashboard() {
  return (
    <div>
      <h2>Dashboard</h2>
      <nav>
        <Link to="\&.\&.">Dashboard Home</Link>
        <Link to="\&.\&./team">Team</Link>
        <Link to="\&.\&./projects">Projects</Link>
      </nav>

      <Routes>
        <Route path="/" element={<DashboardHome />} />
        <Route path="team" element={<DashboardTeam />} />
        <Route path="projects" element={<DashboardProjects />} />
      </Router>
    </div>
  );
}
.fi
.PP

.PP
This way, \fR\&.\fP means "the full current pathname for my route" in all cases (including static, dynamic, and splat routes) and \fR\&.\&.\fP always means "my parents pathname"\&.
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Catch and bubble errors thrown when trying to unwrap responses from \fRloader\fP/\fRaction\fP functions (\fR#11061\fP)
.IP "\(bu" 2
Fix \fRrelative="path"\fP issue when rendering \fRLink\fP/\fRNavLink\fP outside of matched routes (\fR#11062\fP)
.PP
.SH "1\&.13\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Revert the \fRuseResolvedPath\fP fix for splat routes due to a large number of applications that were relying on the buggy behavior (see https://github.com/remix-run/react-router/issues/11052#issuecomment-1836589329)\&. We plan to re-introduce this fix behind a future flag in the next minor version\&. (\fR#11078\fP)
.PP
.SH "1\&.13\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Export the \fRPathParam\fP type from the public API (\fR#10719\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix bug with \fRresolveTo\fP in splat routes (\fR#11045\fP)
.IP "  \(bu" 4
This is a follow up to \fR#10983\fP to handle the few other code paths using \fRgetPathContributingMatches\fP
.IP "  \(bu" 4
This removes the \fRUNSAFE_getPathContributingMatches\fP export from \fR@remix-run/router\fP since we no longer need this in the \fRreact-router\fP/\fRreact-router-dom\fP layers
.PP

.IP "\(bu" 2
Do not revalidate unmounted fetchers when \fRv7_fetcherPersist\fP is enabled (\fR#11044\fP)
.PP
.SH "1\&.12\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add \fRunstable_flushSync\fP option to \fRrouter\&.navigate\fP and \fRrouter\&.fetch\fP to tell the React Router layer to opt-out of \fRReact\&.startTransition\fP and into \fRReactDOM\&.flushSync\fP for state updates (\fR#11005\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRrelative="path"\fP bug where relative path calculations started from the full location pathname, instead of from the current contextual route pathname\&. (\fR#11006\fP)

.PP
.PP
.nf
<Route path="/a">
  <Route path="/b" element={<Component />}>
    <Route path="/c" />
  </Route>
</Route>;

function Component() {
  return (
    <>
      {/* This is now correctly relative to /a/b, not /a/b/c */}
      <Link to="\&.\&." relative="path" />
      <Outlet />
    </>
  );
}
.fi
.PP

.PP
.SH "1\&.11\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add a new \fRfuture\&.v7_fetcherPersist\fP flag to the \fR@remix-run/router\fP to change the persistence behavior of fetchers when \fRrouter\&.deleteFetcher\fP is called\&. Instead of being immediately cleaned up, fetchers will persist until they return to an \fRidle\fP state (\fRRFC\fP) (\fR#10962\fP)
.IP "  \(bu" 4
This is sort of a long-standing bug fix as the \fRuseFetchers()\fP API was always supposed to only reflect \fBin-flight\fP fetcher information for pending/optimistic UI -- it was not intended to reflect fetcher data or hang onto fetchers after they returned to an \fRidle\fP state
.IP "  \(bu" 4
Keep an eye out for the following specific behavioral changes when opting into this flag and check your app for compatibility:
.IP "    \(bu" 6
Fetchers that complete \fIwhile still mounted\fP will no longer appear in \fRuseFetchers()\fP\&. They served effectively no purpose in there since you can access the data via \fRuseFetcher()\&.data\fP)\&.
.IP "    \(bu" 6
Fetchers that previously unmounted \fIwhile in-flight\fP will not be immediately aborted and will instead be cleaned up once they return to an \fRidle\fP state\&. They will remain exposed via \fRuseFetchers\fP while in-flight so you can still access pending/optimistic data after unmount\&.
.PP

.PP

.IP "\(bu" 2
When \fRv7_fetcherPersist\fP is enabled, the router now performs ref-counting on fetcher keys via \fRgetFetcher\fP/\fRdeleteFetcher\fP so it knows when a given fetcher is totally unmounted from the UI (\fR#10977\fP)
.IP "  \(bu" 4
Once a fetcher has been totally unmounted, we can ignore post-processing of a persisted fetcher result such as a redirect or an error
.IP "  \(bu" 4
The router will also pass a new \fRdeletedFetchers\fP array to the subscriber callbacks so that the UI layer can remove associated fetcher data
.PP

.IP "\(bu" 2
Add support for optional path segments in \fRmatchPath\fP (\fR#10768\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRrouter\&.getFetcher\fP/\fRrouter\&.deleteFetcher\fP type definitions which incorrectly specified \fRkey\fP as an optional parameter (\fR#10960\fP)
.PP
.SH "1\&.10\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add experimental support for the \fRView Transitions API\fP by allowing users to opt-into view transitions on navigations via the new \fRunstable_viewTransition\fP option to \fRrouter\&.navigate\fP (\fR#10916\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Allow 404 detection to leverage root route error boundary if path contains a URL segment (\fR#10852\fP)
.IP "\(bu" 2
Fix \fRErrorResponse\fP type to avoid leaking internal field (\fR#10876\fP)
.PP
.SH "1\&.9\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
In order to move towards stricter TypeScript support in the future, we're aiming to replace current usages of \fRany\fP with \fRunknown\fP on exposed typings for user-provided data\&. To do this in Remix v2 without introducing breaking changes in React Router v6, we have added generics to a number of shared types\&. These continue to default to \fRany\fP in React Router and are overridden with \fRunknown\fP in Remix\&. In React Router v7 we plan to move these to \fRunknown\fP as a breaking change\&. (\fR#10843\fP)
.IP "  \(bu" 4
\fRLocation\fP now accepts a generic for the \fRlocation\&.state\fP value
.IP "  \(bu" 4
\fRActionFunctionArgs\fP/\fRActionFunction\fP/\fRLoaderFunctionArgs\fP/\fRLoaderFunction\fP now accept a generic for the \fRcontext\fP parameter (only used in SSR usages via \fRcreateStaticHandler\fP)
.IP "  \(bu" 4
The return type of \fRuseMatches\fP (now exported as \fRUIMatch\fP) accepts generics for \fRmatch\&.data\fP and \fRmatch\&.handle\fP - both of which were already set to \fRunknown\fP
.PP

.IP "\(bu" 2
Move the \fR@private\fP class export \fRErrorResponse\fP to an \fRUNSAFE_ErrorResponseImpl\fP export since it is an implementation detail and there should be no construction of \fRErrorResponse\fP instances in userland\&. This frees us up to export a \fRtype ErrorResponse\fP which correlates to an instance of the class via \fRInstanceType\fP\&. Userland code should only ever be using \fRErrorResponse\fP as a type and should be type-narrowing via \fRisRouteErrorResponse\fP\&. (\fR#10811\fP)
.IP "\(bu" 2
Export \fRShouldRevalidateFunctionArgs\fP interface (\fR#10797\fP)
.IP "\(bu" 2
Removed private/internal APIs only required for the Remix v1 backwards compatibility layer and no longer needed in Remix v2 (\fR_isFetchActionRedirect\fP, \fR_hasFetcherDoneAnything\fP) (\fR#10715\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Add method/url to error message on aborted \fRquery\fP/\fRqueryRoute\fP calls (\fR#10793\fP)
.IP "\(bu" 2
Fix a race-condition with loader/action-thrown errors on \fRroute\&.lazy\fP routes (\fR#10778\fP)
.IP "\(bu" 2
Fix type for \fRactionResult\fP on the arguments object passed to \fRshouldRevalidate\fP (\fR#10779\fP)
.PP
.SH "1\&.8\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add's a new \fRredirectDocument()\fP function which allows users to specify that a redirect from a \fRloader\fP/\fRaction\fP should trigger a document reload (via \fRwindow\&.location\fP) instead of attempting to navigate to the redirected location via React Router (\fR#10705\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix an issue in \fRqueryRoute\fP that was not always identifying thrown \fRResponse\fP instances (\fR#10717\fP)
.IP "\(bu" 2
Ensure hash history always includes a leading slash on hash pathnames (\fR#10753\fP)
.PP
.SH "1\&.7\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Trigger an error if a \fRdefer\fP promise resolves/rejects with \fRundefined\fP in order to match the behavior of loaders and actions which must return a value or \fRnull\fP (\fR#10690\fP)
.IP "\(bu" 2
Properly handle fetcher redirects interrupted by normal navigations (\fR#10674\fP, \fR#10709\fP)
.IP "\(bu" 2
Initial-load fetchers should not automatically revalidate on GET navigations (\fR#10688\fP)
.IP "\(bu" 2
Enhance the return type of \fRRoute\&.lazy\fP to prohibit returning an empty object (\fR#10634\fP)
.PP
.SH "1\&.7\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix issues with reused blockers on subsequent navigations (\fR#10656\fP)
.PP
.SH "1\&.7\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add support for \fRapplication/json\fP and \fRtext/plain\fP encodings for \fRrouter\&.navigate\fP/\fRrouter\&.fetch\fP submissions\&. To leverage these encodings, pass your data in a \fRbody\fP parameter and specify the desired \fRformEncType\fP: (\fR#10413\fP)

.PP
.PP
.nf
// By default, the encoding is "application/x\-www\-form\-urlencoded"
router\&.navigate("/", {
  formMethod: "post",
  body: { key: "value" },
});

async function action({ request }) {
  // await request\&.formData() => FormData instance with entry [key=value]
}
.fi
.PP

.PP
.PP
.nf
// Pass `formEncType` to opt\-into a different encoding (json)
router\&.navigate("/", {
  formMethod: "post",
  formEncType: "application/json",
  body: { key: "value" },
});

async function action({ request }) {
  // await request\&.json() => { key: "value" }
}
.fi
.PP

.PP
.PP
.nf
// Pass `formEncType` to opt\-into a different encoding (text)
router\&.navigate("/", {
  formMethod: "post",
  formEncType: "text/plain",
  body: "Text submission",
});

async function action({ request }) {
  // await request\&.text() => "Text submission"
}
.fi
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Call \fRwindow\&.history\&.pushState/replaceState\fP before updating React Router state (instead of after) so that \fRwindow\&.location\fP matches \fRuseLocation\fP during synchronous React 17 rendering (\fR#10448\fP)
.IP "  \(bu" 4
⚠️ However, generally apps should not be relying on \fRwindow\&.location\fP and should always reference \fRuseLocation\fP when possible, as \fRwindow\&.location\fP will not be in sync 100% of the time (due to \fRpopstate\fP events, concurrent mode, etc\&.)
.PP

.IP "\(bu" 2
Strip \fRbasename\fP from the \fRlocation\fP provided to \fR<ScrollRestoration getKey>\fP to match the \fRuseLocation\fP behavior (\fR#10550\fP)
.IP "\(bu" 2
Avoid calling \fRshouldRevalidate\fP for fetchers that have not yet completed a data load (\fR#10623\fP)
.IP "\(bu" 2
Fix \fRunstable_useBlocker\fP key issues in \fRStrictMode\fP (\fR#10573\fP)
.IP "\(bu" 2
Upgrade \fRtypescript\fP to 5\&.1 (\fR#10581\fP)
.PP
.SH "1\&.6\&.3"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Allow fetcher revalidations to complete if submitting fetcher is deleted (\fR#10535\fP)
.IP "\(bu" 2
Re-throw \fRDOMException\fP (\fRDataCloneError\fP) when attempting to perform a \fRPUSH\fP navigation with non-serializable state\&. (\fR#10427\fP)
.IP "\(bu" 2
Ensure revalidations happen when hash is present (\fR#10516\fP)
.IP "\(bu" 2
upgrade jest and jsdom (\fR#10453\fP)
.PP
.SH "1\&.6\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix HMR-driven error boundaries by properly reconstructing new routes and \fRmanifest\fP in \fR\\_internalSetRoutes\fP (\fR#10437\fP)
.IP "\(bu" 2
Fix bug where initial data load would not kick off when hash is present (\fR#10493\fP)
.PP
.SH "1\&.6\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRbasename\fP handling when navigating without a path (\fR#10433\fP)
.IP "\(bu" 2
"Same hash" navigations no longer re-run loaders to match browser behavior (i\&.e\&. \fR/path#hash -> /path#hash\fP) (\fR#10408\fP)
.PP
.SH "1\&.6\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Enable relative routing in the \fR@remix-run/router\fP when providing a source route ID from which the path is relative to: (\fR#10336\fP)
.IP "  \(bu" 4
Example: \fRrouter\&.navigate("\&.\&./path", { fromRouteId: "some-route" })\fP\&.
.IP "  \(bu" 4
This also applies to \fRrouter\&.fetch\fP which already receives a source route ID
.PP

.IP "\(bu" 2
Introduce a new \fR@remix-run/router\fP \fRfuture\&.v7_prependBasename\fP flag to enable \fRbasename\fP prefixing to all paths coming into \fRrouter\&.navigate\fP and \fRrouter\&.fetch\fP\&.
.IP "  \(bu" 4
Previously the \fRbasename\fP was prepended in the React Router layer, but now that relative routing is being handled by the router we need prepend the \fRbasename\fP \fIafter\fP resolving any relative paths
.IP "  \(bu" 4
This also enables \fRbasename\fP support in \fRuseFetcher\fP as well
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Enhance \fRLoaderFunction\fP/\fRActionFunction\fP return type to prevent \fRundefined\fP from being a valid return value (\fR#10267\fP)
.IP "\(bu" 2
Ensure proper 404 error on \fRfetcher\&.load\fP call to a route without a \fRloader\fP (\fR#10345\fP)
.IP "\(bu" 2
Deprecate the \fRcreateRouter\fP \fRdetectErrorBoundary\fP option in favor of the new \fRmapRouteProperties\fP option for converting a framework-agnostic route to a framework-aware route\&. This allows us to set more than just the \fRhasErrorBoundary\fP property during route pre-processing, and is now used for mapping \fRComponent -> element\fP and \fRErrorBoundary -> errorElement\fP in \fRreact-router\fP\&. (\fR#10287\fP)
.IP "\(bu" 2
Fixed a bug where fetchers were incorrectly attempting to revalidate on search params changes or routing to the same URL (using the same logic for route \fRloader\fP revalidations)\&. However, since fetchers have a static href, they should only revalidate on \fRaction\fP submissions or \fRrouter\&.revalidate\fP calls\&. (\fR#10344\fP)
.IP "\(bu" 2
Decouple \fRAbortController\fP usage between revalidating fetchers and the thing that triggered them such that the unmount/deletion of a revalidating fetcher doesn't impact the ongoing triggering navigation/revalidation (\fR#10271\fP)
.PP
.SH "1\&.5\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Added support for \fR\fBFuture Flags\fP\fP in React Router\&. The first flag being introduced is \fRfuture\&.v7_normalizeFormMethod\fP which will normalize the exposed \fRuseNavigation()/useFetcher()\fP \fRformMethod\fP fields as uppercase HTTP methods to align with the \fRfetch()\fP behavior\&. (\fR#10207\fP)
.IP "  \(bu" 4
When \fRfuture\&.v7_normalizeFormMethod === false\fP (default v6 behavior),
.IP "    \(bu" 6
\fRuseNavigation()\&.formMethod\fP is lowercase
.IP "    \(bu" 6
\fRuseFetcher()\&.formMethod\fP is lowercase
.PP

.IP "  \(bu" 4
When \fRfuture\&.v7_normalizeFormMethod === true\fP:
.IP "    \(bu" 6
\fRuseNavigation()\&.formMethod\fP is uppercase
.IP "    \(bu" 6
\fRuseFetcher()\&.formMethod\fP is uppercase
.PP

.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Provide fetcher submission to \fRshouldRevalidate\fP if the fetcher action redirects (\fR#10208\fP)
.IP "\(bu" 2
Properly handle \fRlazy()\fP errors during router initialization (\fR#10201\fP)
.IP "\(bu" 2
Remove \fRinstanceof\fP check for \fRDeferredData\fP to be resilient to ESM/CJS boundaries in SSR bundling scenarios (\fR#10247\fP)
.IP "\(bu" 2
Update to latest \fR@remix-run/web-fetch@4\&.3\&.3\fP (\fR#10216\fP)
.PP
.SH "1\&.4\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
\fBIntroducing Lazy Route Modules!\fP (\fR#10045\fP)

.PP
In order to keep your application bundles small and support code-splitting of your routes, we've introduced a new \fRlazy()\fP route property\&. This is an async function that resolves the non-route-matching portions of your route definition (\fRloader\fP, \fRaction\fP, \fRelement\fP/\fRComponent\fP, \fRerrorElement\fP/\fRErrorBoundary\fP, \fRshouldRevalidate\fP, \fRhandle\fP)\&.

.PP
Lazy routes are resolved on initial load and during the \fRloading\fP or \fRsubmitting\fP phase of a navigation or fetcher call\&. You cannot lazily define route-matching properties (\fRpath\fP, \fRindex\fP, \fRchildren\fP) since we only execute your lazy route functions after we've matched known routes\&.

.PP
Your \fRlazy\fP functions will typically return the result of a dynamic import\&.

.PP
.PP
.nf
// In this example, we assume most folks land on the homepage so we include that
// in our critical\-path bundle, but then we lazily load modules for /a and /b so
// they don't load until the user navigates to those routes
let routes = createRoutesFromElements(
  <Route path="/" element={<Layout />}>
    <Route index element={<Home />} />
    <Route path="a" lazy={() => import("\&./a")} />
    <Route path="b" lazy={() => import("\&./b")} />
  </Route>
);
.fi
.PP

.PP
Then in your lazy route modules, export the properties you want defined for the route:

.PP
.PP
.nf
export async function loader({ request }) {
  let data = await fetchData(request);
  return json(data);
}

// Export a `Component` directly instead of needing to create a React Element from it
export function Component() {
  let data = useLoaderData();

  return (
    <>
      <h1>You made it!</h1>
      <p>{data}</p>
    </>
  );
}

// Export an `ErrorBoundary` directly instead of needing to create a React Element from it
export function ErrorBoundary() {
  let error = useRouteError();
  return isRouteErrorResponse(error) ? (
    <h1>
      {error\&.status} {error\&.statusText}
    </h1>
  ) : (
    <h1>{error\&.message || error}</h1>
  );
}
.fi
.PP

.PP
An example of this in action can be found in the \fR\fRexamples/lazy-loading-router-provider\fP\fP directory of the repository\&.

.PP
🙌 Huge thanks to @rossipedia for the \fRInitial Proposal\fP and \fRPOC Implementation\fP\&.
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRgeneratePath\fP incorrectly applying parameters in some cases (\fR#10078\fP)
.PP
.SH "1\&.3\&.3"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Correctly perform a hard redirect for same-origin absolute URLs outside of the router \fRbasename\fP (\fR#10076\fP)
.IP "\(bu" 2
Ensure status code and headers are maintained for \fRdefer\fP loader responses in \fRcreateStaticHandler\fP's \fRquery()\fP method (\fR#10077\fP)
.IP "\(bu" 2
Change \fRinvariant\fP to an \fRUNSAFE_invariant\fP export since it's only intended for internal use (\fR#10066\fP)
.IP "\(bu" 2
Add internal API for custom HMR implementations (\fR#9996\fP)
.PP
.SH "1\&.3\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Remove inaccurate console warning for POP navigations and update active blocker logic (\fR#10030\fP)
.IP "\(bu" 2
Only check for differing origin on absolute URL redirects (\fR#10033\fP)
.PP
.SH "1\&.3\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fixes 2 separate issues for revalidating fetcher \fRshouldRevalidate\fP calls (\fR#9948\fP)
.IP "  \(bu" 4
The \fRshouldRevalidate\fP function was only being called for \fIexplicit\fP revalidation scenarios (after a mutation, manual \fRuseRevalidator\fP call, or an \fRX-Remix-Revalidate\fP header used for cookie setting in Remix)\&. It was not properly being called on \fIimplicit\fP revalidation scenarios that also apply to navigation \fRloader\fP revalidation, such as a change in search params or clicking a link for the page we're already on\&. It's now correctly called in those additional scenarios\&.
.IP "  \(bu" 4
The parameters being passed were incorrect and inconsistent with one another since the \fRcurrent*\fP/\fRnext*\fP parameters reflected the static \fRfetcher\&.load\fP URL (and thus were identical)\&. Instead, they should have reflected the the navigation that triggered the revalidation (as the \fRform*\fP parameters did)\&. These parameters now correctly reflect the triggering navigation\&.
.PP

.IP "\(bu" 2
Respect \fRpreventScrollReset\fP on \fR<fetcher\&.Form>\fP (\fR#9963\fP)
.IP "\(bu" 2
Do not short circuit on hash change only mutation submissions (\fR#9944\fP)
.IP "\(bu" 2
Remove \fRinstanceof\fP check from \fRisRouteErrorResponse\fP to avoid bundling issues on the server (\fR#9930\fP)
.IP "\(bu" 2
Fix navigation for hash routers on manual URL changes (\fR#9980\fP)
.IP "\(bu" 2
Detect when a \fRdefer\fP call only contains critical data and remove the \fRAbortController\fP (\fR#9965\fP)
.IP "\(bu" 2
Send the name as the value when url-encoding \fRFile\fP \fRFormData\fP entries (\fR#9867\fP)
.PP
.SH "1\&.3\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Added support for navigation blocking APIs (\fR#9709\fP)
.IP "\(bu" 2
Expose deferred information from \fRcreateStaticHandler\fP (\fR#9760\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Improved absolute redirect url detection in actions/loaders (\fR#9829\fP)
.IP "\(bu" 2
Fix URL creation with memory histories (\fR#9814\fP)
.IP "\(bu" 2
Fix \fRgeneratePath\fP when optional params are present (\fR#9764\fP)
.IP "\(bu" 2
Fix scroll reset if a submission redirects (\fR#9886\fP)
.IP "\(bu" 2
Fix 404 bug with same-origin absolute redirects (\fR#9913\fP)
.IP "\(bu" 2
Support \fROPTIONS\fP requests in \fRstaticHandler\&.queryRoute\fP (\fR#9914\fP)
.PP
.SH "1\&.2\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Include submission info in \fRshouldRevalidate\fP on action redirects (\fR#9777\fP, \fR#9782\fP)
.IP "\(bu" 2
Reset \fRactionData\fP on action redirect to current location (\fR#9772\fP)
.PP
.SH "1\&.2\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Remove \fRunstable_\fP prefix from \fRcreateStaticHandler\fP/\fRcreateStaticRouter\fP/\fRStaticRouterProvider\fP (\fR#9738\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix explicit \fRreplace\fP on submissions and \fRPUSH\fP on submission to new paths (\fR#9734\fP)
.IP "\(bu" 2
Fix a few bugs where loader/action data wasn't properly cleared on errors (\fR#9735\fP)
.IP "\(bu" 2
Prevent \fRuseLoaderData\fP usage in \fRerrorElement\fP (\fR#9735\fP)
.IP "\(bu" 2
Skip initial scroll restoration for SSR apps with \fRhydrationData\fP (\fR#9664\fP)
.PP
.SH "1\&.1\&.0"
.PP
This release introduces support for \fROptional Route Segments\fP\&. Now, adding a \fR?\fP to the end of any path segment will make that entire segment optional\&. This works for both static segments and dynamic parameters\&.

.PP
\fBOptional Params Examples\fP

.PP
.IP "\(bu" 2
Path \fRlang?/about\fP will match:
.IP "  \(bu" 4
\fR/:lang/about\fP
.IP "  \(bu" 4
\fR/about\fP
.PP

.IP "\(bu" 2
Path \fR/multistep/:widget1?/widget2?/widget3?\fP will match:
.IP "  \(bu" 4
\fR/multistep\fP
.IP "  \(bu" 4
\fR/multistep/:widget1\fP
.IP "  \(bu" 4
\fR/multistep/:widget1/:widget2\fP
.IP "  \(bu" 4
\fR/multistep/:widget1/:widget2/:widget3\fP
.PP

.PP

.PP
\fBOptional Static Segment Example\fP

.PP
.IP "\(bu" 2
Path \fR/home?\fP will match:
.IP "  \(bu" 4
\fR/\fP
.IP "  \(bu" 4
\fR/home\fP
.PP

.IP "\(bu" 2
Path \fR/fr?/about\fP will match:
.IP "  \(bu" 4
\fR/about\fP
.IP "  \(bu" 4
\fR/fr/about\fP
.PP

.PP
.SS "Minor Changes"
.IP "\(bu" 2
Allows optional routes and optional static segments (\fR#9650\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Stop incorrectly matching on partial named parameters, i\&.e\&. \fR<Route path="prefix-:param">\fP, to align with how splat parameters work\&. If you were previously relying on this behavior then it's recommended to extract the static portion of the path at the \fRuseParams\fP call site: (\fR#9506\fP)
.PP

.PP
.PP
.nf
// Old behavior at URL /prefix\-123
<Route path="prefix\-:id" element={<Comp /> }>

function Comp() {
  let params = useParams(); // { id: '123' }
  let id = params\&.id; // "123"
  \&.\&.\&.
}

// New behavior at URL /prefix\-123
<Route path=":id" element={<Comp /> }>

function Comp() {
  let params = useParams(); // { id: 'prefix\-123' }
  let id = params\&.id\&.replace(/^prefix\-/, ''); // "123"
  \&.\&.\&.
}
.fi
.PP

.PP
.IP "\(bu" 2
Persist \fRheaders\fP on \fRloader\fP \fRrequest\fP's after SSR document \fRaction\fP request (\fR#9721\fP)
.IP "\(bu" 2
Fix requests sent to revalidating loaders so they reflect a GET request (\fR#9660\fP)
.IP "\(bu" 2
Fix issue with deeply nested optional segments (\fR#9727\fP)
.IP "\(bu" 2
GET forms now expose a submission on the loading navigation (\fR#9695\fP)
.IP "\(bu" 2
Fix error boundary tracking for multiple errors bubbling to the same boundary (\fR#9702\fP)
.PP
.SH "1\&.0\&.5"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix requests sent to revalidating loaders so they reflect a \fRGET\fP request (\fR#9680\fP)
.IP "\(bu" 2
Remove \fRinstanceof Response\fP checks in favor of \fRisResponse\fP (\fR#9690\fP)
.IP "\(bu" 2
Fix \fRURL\fP creation in Cloudflare Pages or other non-browser-environments (\fR#9682\fP, \fR#9689\fP)
.IP "\(bu" 2
Add \fRrequestContext\fP support to static handler \fRquery\fP/\fRqueryRoute\fP (\fR#9696\fP)
.IP "  \(bu" 4
Note that the unstable API of \fRqueryRoute(path, routeId)\fP has been changed to \fRqueryRoute(path, { routeId, requestContext })\fP
.PP

.PP
.SH "1\&.0\&.4"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Throw an error if an \fRaction\fP/\fRloader\fP function returns \fRundefined\fP as revalidations need to know whether the loader has previously been executed\&. \fRundefined\fP also causes issues during SSR stringification for hydration\&. You should always ensure you \fRloader\fP/\fRaction\fP returns a value, and you may return \fRnull\fP if you don't wish to return anything\&. (\fR#9511\fP)
.IP "\(bu" 2
Properly handle redirects to external domains (\fR#9590\fP, \fR#9654\fP)
.IP "\(bu" 2
Preserve the HTTP method on 307/308 redirects (\fR#9597\fP)
.IP "\(bu" 2
Support \fRbasename\fP in static data routers (\fR#9591\fP)
.IP "\(bu" 2
Enhanced \fRErrorResponse\fP bodies to contain more descriptive text in internal 403/404/405 scenarios
.PP
.SH "1\&.0\&.3"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix hrefs generated when using \fRcreateHashRouter\fP (\fR#9409\fP)
.IP "\(bu" 2
fix encoding/matching issues with special chars (\fR#9477\fP, \fR#9496\fP)
.IP "\(bu" 2
Support \fRbasename\fP and relative routing in \fRloader\fP/\fRaction\fP redirects (\fR#9447\fP)
.IP "\(bu" 2
Ignore pathless layout routes when looking for proper submission \fRaction\fP function (\fR#9455\fP)
.IP "\(bu" 2
properly support \fRindex\fP routes with a \fRpath\fP in \fRuseResolvedPath\fP (\fR#9486\fP)
.IP "\(bu" 2
Add UMD build for \fR@remix-run/router\fP (\fR#9446\fP)
.IP "\(bu" 2
fix \fRcreateURL\fP in local file execution in Firefox (\fR#9464\fP)
.IP "\(bu" 2
Updates to \fRunstable_createStaticHandler\fP for incorporating into Remix (\fR#9482\fP, \fR#9465\fP)
.PP
.SH "1\&.0\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Reset \fRactionData\fP after a successful action redirect (\fR#9334\fP)
.IP "\(bu" 2
Update \fRmatchPath\fP to avoid false positives on dash-separated segments (\fR#9300\fP)
.IP "\(bu" 2
If an index route has children, it will result in a runtime error\&. We have strengthened our \fRRouteObject\fP/\fRRouteProps\fP types to surface the error in TypeScript\&. (\fR#9366\fP)
.PP
.SH "1\&.0\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Preserve state from \fRinitialEntries\fP (\fR#9288\fP)
.IP "\(bu" 2
Preserve \fR?index\fP for fetcher get submissions to index routes (\fR#9312\fP)
.PP
.SH "1\&.0\&.0"
.PP
This is the first stable release of \fR@remix-run/router\fP, which provides all the underlying routing and data loading/mutation logic for \fRreact-router\fP\&. You should \fInot\fP be using this package directly unless you are authoring a routing library similar to \fRreact-router\fP\&.

.PP
For an overview of the features provided by \fRreact-router\fP, we recommend you go check out the \fRdocs\fP, especially the \fRfeature overview\fP and the \fRtutorial\fP\&.

.PP
For an overview of the features provided by \fR@remix-run/router\fP, please check out the \fB\fRREADME\fP\fP\&. 
