.TH "md_frontend_2node__modules_2recharts-scale_2_c_h_a_n_g_e_l_o_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2recharts-scale_2_c_h_a_n_g_e_l_o_g \- 0\&.4\&.5 (Mar 25, 2021) 
.PP

.SS "chore"
.IP "\(bu" 2
fix: previous release
.PP
.SH "0\&.4\&.4 (Mar 18, 2021)"
.PP
.SS "chore"
.IP "\(bu" 2
bring up all dev deps (incl\&. eslint and webpack) to the latest
.IP "\(bu" 2
move CI to Github actions
.IP "\(bu" 2
add linting and building to ci pipeline (in addition to unit testing)
.PP
.SH "0\&.4\&.0 (Seq 28, 2018)"
.PP
.SS "feat"
.IP "\(bu" 2
use \fRdecimal\&.js-light\fP to handle large number or high precision
.PP
.SH "0\&.3\&.2 (Aug 21, 2017)"
.PP
.SS "fix"
.IP "\(bu" 2
fix \fRgetNiceTickValues\fP when the number is a scientific notation
.PP
.SH "0\&.3\&.1 (Jun 11, 2017)"
.PP
.SS "fix"
.IP "\(bu" 2
fix \fRgetDigitCount\fP when the number is a scientific notation
.PP
.SH "0\&.3\&.0 (Mar 01, 2017)"
.PP
.SS "feat"
.IP "\(bu" 2
Add new ticks function \fRgetTickValuesFixedDomain\fP
.PP
.SH "0\&.2\&.3 (Feb 28, 2017)"
.PP
.SS "fix"
.IP "\(bu" 2
Fix calculation precision of calculateStep, add Arithmetic\&.modulo
.PP
.SH "0\&.2\&.2 (Feb 28, 2017)"
.PP
.SS "fix"
.IP "\(bu" 2
Fix calculation precision of calculateStep
.PP
.SH "0\&.2\&.1 (July 25, 2016)"
.PP
.SS "fix"
.IP "\(bu" 2
Fix the precision of ticks for decimals
.PP
.SH "0\&.2\&.0 (July 25, 2016)"
.PP
.SS "feat"
.IP "\(bu" 2
Support \fRallowDecimals\fP option
.PP
.SH "0\&.1\&.11 (July 19, 2016)"
.PP
.SS "fix"
.IP "\(bu" 2
Tweak the strategy of calculating step of ticks
.PP
.SH "0\&.1\&.10 (July 07, 2016)"
.PP
.SS "deps"
.IP "\(bu" 2
update deps and fix lint error
.PP
.SH "0\&.1\&.9 (April 08, 2016)"
.PP
.SS "fix"
.IP "\(bu" 2
Fix ticks for interval [0, 0]
.PP
.SH "0\&.1\&.8 (Feb 04, 2016)"
.PP
.SS "refactor"
.IP "\(bu" 2
Refactor the export method
.PP
.SH "0\&.1\&.7 (Feb 04, 2016)"
.PP
.SS "chore"
.IP "\(bu" 2
Optimize npm script commands 
.PP

