.TH "md_frontend_2node__modules_2victory-vendor_2_c_h_a_n_g_e_l_o_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2victory-vendor_2_c_h_a_n_g_e_l_o_g \- victory-vendor 
.PP

.SH "36\&.9\&.2"
.PP
.SH "36\&.9\&.1"
.PP
.SH "36\&.9\&.0"
.PP
.SH "36\&.8\&.6"
.PP
.SH "36\&.8\&.5"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Replace instances of lodash\&.assign with Object\&.assign (\fR#2757\fP)
.PP
.SH "36\&.8\&.4"
.PP
.SH "36\&.8\&.3"
.PP
.SH "36\&.8\&.2"
.PP
.SH "36\&.8\&.1"
.PP
.SH "36\&.8\&.0"
.PP
.SH "36\&.7\&.0"
.PP
.SH "36\&.6\&.12"
.PP
.SH "36\&.6\&.11"
.PP
.SH "36\&.6\&.10"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Setup NPM Provenance (\fR#2590\fP)
.PP
.SH "36\&.6\&.9"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Setup NPM Provenance (\fR#2587\fP)
.PP
.SH "36\&.6\&.8"
.PP
.SH "36\&.6\&.7"
.PP
.SH "36\&.6\&.6"
.PP
.SH "36\&.6\&.5"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Export types directly from d3-* (fixes \fR#2439\fP) (\fR#2440\fP)
.PP
.SH "36\&.6\&.4"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Allow data accessors to accept any data types (fixes \fR#2360\fP) (\fR#2436\fP)
.PP
.SH "36\&.6\&.3"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Do not generate *\&.js\&.map sourcemaps (fixes \fR#2346\fP) (\fR#2432\fP)
.PP
.SH "36\&.6\&.2"
.PP
.SH "36\&.6\&.1"
.PP
.SH "36\&.6\&.0"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Update source code with minor lint-based improvements (see \fR#2236\fP)\&. (\fR#2403\fP)
.PP
.SH "36\&.5\&.3 and earlier"
.PP
Change history for version 36\&.5\&.3 and earlier can be found in our root \fRCHANGELOG\&.md\fP\&. 
