.TH "md_frontend_2node__modules_2date-fns_2_s_e_c_u_r_i_t_y" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2date-fns_2_s_e_c_u_r_i_t_y \- Security Policy 
.PP

.SH "Supported Versions"
.PP
Security updates are applied only to the latest release\&.
.SH "Reporting a Vulnerability"
.PP
If you have discovered a security vulnerability in this project, please report it privately\&. \fBDo not disclose it as a public issue\&.\fP This gives us time to work with you to fix the issue before public exposure, reducing the chance that the exploit will be used before a patch is released\&. Please disclose it to \fRSasha Koss\fP\&. This project is maintained by a team of volunteers on a reasonable-effort basis\&. As such, please give us at least 90 days to work on a fix before public exposure\&. 
