.TH "md_frontend_2node__modules_2postcss-selector-parser_2_a_p_i" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2postcss-selector-parser_2_a_p_i \- API Documentation 
.PP


.PP
\fIPlease use only this documented API when working with the parser\&. Methods not documented here are subject to change at any point\&.\fP
.SH "\fRparser\fP function"
.PP
This is the module's main entry point\&.

.PP
.PP
.nf
const parser = require('postcss\-selector\-parser');
.fi
.PP
.SS "\fRparser([transform], [options])\fP"
Creates a new \fRprocessor\fP instance

.PP
.PP
.nf
const processor = parser();
.fi
.PP

.PP
Or, with optional transform function

.PP
.PP
.nf
const transform = selectors => {
    selectors\&.walkUniversals(selector => {
        selector\&.remove();
    });
};

const processor = parser(transform)

// Example
const result = processor\&.processSync('*\&.class');
// => \&.class
.fi
.PP

.PP
\fBSee processor documentation\fP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRtransform (function)\fP: Provide a function to work with the parsed AST\&.
.IP "\(bu" 2
\fRoptions (object)\fP: Provide default options for all calls on the returned \fRProcessor\fP\&.
.PP
.SS "\fRparser\&.attribute([props])\fP"
Creates a new attribute selector\&.

.PP
.PP
.nf
parser\&.attribute({attribute: 'href'});
// => [href]
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.className([props])\fP"
Creates a new class selector\&.

.PP
.PP
.nf
parser\&.className({value: 'button'});
// => \&.button
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.combinator([props])\fP"
Creates a new selector combinator\&.

.PP
.PP
.nf
parser\&.combinator({value: '+'});
// => +
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP

.PP
Notes:
.IP "\(bu" 2
\fBDescendant Combinators\fP The value of descendant combinators created by the parser always just a single space (\fR" "\fP)\&. For descendant selectors with no comments, additional space is now stored in \fRnode\&.spaces\&.before\fP\&. Depending on the location of comments, additional spaces may be stored in \fRnode\&.raws\&.spaces\&.before\fP, \fRnode\&.raws\&.spaces\&.after\fP, or \fRnode\&.raws\&.value\fP\&.
.IP "\(bu" 2
\fBNamed Combinators\fP Although, nonstandard and unlikely to ever become a standard, named combinators like \fR/deep/\fP and \fR/for/\fP are parsed as combinators\&. The \fRnode\&.value\fP is name after being unescaped and normalized as lowercase\&. The original value for the combinator name is stored in \fRnode\&.raws\&.value\fP\&.
.PP
.SS "\fRparser\&.comment([props])\fP"
Creates a new comment\&.

.PP
.PP
.nf
parser\&.comment({value: '/* Affirmative, Dave\&. I read you\&. */'});
// => /* Affirmative, Dave\&. I read you\&. */
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.id([props])\fP"
Creates a new id selector\&.

.PP
.PP
.nf
parser\&.id({value: 'search'});
// => #search
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.nesting([props])\fP"
Creates a new nesting selector\&.

.PP
.PP
.nf
parser\&.nesting();
// => &
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.pseudo([props])\fP"
Creates a new pseudo selector\&.

.PP
.PP
.nf
parser\&.pseudo({value: '::before'});
// => ::before
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.root([props])\fP"
Creates a new root node\&.

.PP
.PP
.nf
parser\&.root();
// => (empty)
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.selector([props])\fP"
Creates a new selector node\&.

.PP
.PP
.nf
parser\&.selector();
// => (empty)
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.string([props])\fP"
Creates a new string node\&.

.PP
.PP
.nf
parser\&.string();
// => (empty)
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.tag([props])\fP"
Creates a new tag selector\&.

.PP
.PP
.nf
parser\&.tag({value: 'button'});
// => button
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SS "\fRparser\&.universal([props])\fP"
Creates a new universal selector\&.

.PP
.PP
.nf
parser\&.universal();
// => *
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRprops (object)\fP: The new node's properties\&.
.PP
.SH "Node types"
.PP
.SS "\fRnode\&.type\fP"
A string representation of the selector type\&. It can be one of the following; \fRattribute\fP, \fRclass\fP, \fRcombinator\fP, \fRcomment\fP, \fRid\fP, \fRnesting\fP, \fRpseudo\fP, \fRroot\fP, \fRselector\fP, \fRstring\fP, \fRtag\fP, or \fRuniversal\fP\&. Note that for convenience, these constants are exposed on the main \fRparser\fP as uppercased keys\&. So for example you can get \fRid\fP by querying \fRparser\&.ID\fP\&.

.PP
.PP
.nf
parser\&.attribute({attribute: 'href'})\&.type;
// => 'attribute'
.fi
.PP
.SS "\fRnode\&.parent\fP"
Returns the parent node\&.

.PP
.PP
.nf
root\&.nodes[0]\&.parent === root;
.fi
.PP
.SS "\fRnode\&.toString()\fP, \fRString(node)\fP, or \fR'' + node\fP"
Returns a string representation of the node\&.

.PP
.PP
.nf
const id = parser\&.id({value: 'search'});
console\&.log(String(id));
// => #search
.fi
.PP
.SS "\fRnode\&.next()\fP & \fRnode\&.prev()\fP"
Returns the next/previous child of the parent node\&.

.PP
.PP
.nf
const next = id\&.next();
if (next && next\&.type !== 'combinator') {
    throw new Error('Qualified IDs are not allowed!');
}
.fi
.PP
.SS "\fRnode\&.replaceWith(node)\fP"
Replace a node with another\&.

.PP
.PP
.nf
const attr = selectors\&.first\&.first;
const className = parser\&.className({value: 'test'});
attr\&.replaceWith(className);
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRnode\fP: The node to substitute the original with\&.
.PP
.SS "\fRnode\&.remove()\fP"
Removes the node from its parent node\&.

.PP
.PP
.nf
if (node\&.type === 'id') {
    node\&.remove();
}
.fi
.PP
.SS "\fRnode\&.clone()\fP"
Returns a copy of a node, detached from any parent containers that the original might have had\&.

.PP
.PP
.nf
const cloned = parser\&.id({value: 'search'});
String(cloned);

// => #search
.fi
.PP
.SS "\fRnode\&.isAtPosition(line, column)\fP"
Return a \fRboolean\fP indicating whether this node includes the character at the position of the given line and column\&. Returns \fRundefined\fP if the nodes lack sufficient source metadata to determine the position\&.

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRline\fP: 1-index based line number relative to the start of the selector\&.
.IP "\(bu" 2
\fRcolumn\fP: 1-index based column number relative to the start of the selector\&.
.PP
.SS "\fRnode\&.spaces\fP"
Extra whitespaces around the node will be moved into \fRnode\&.spaces\&.before\fP and \fRnode\&.spaces\&.after\fP\&. So for example, these spaces will be moved as they have no semantic meaning:

.PP
.PP
.nf
h1     ,     h2   {}
.fi
.PP

.PP
For descendent selectors, the value is always a single space\&.

.PP
.PP
.nf
h1        h2 {}
.fi
.PP

.PP
Additional whitespace is found in either the \fRnode\&.spaces\&.before\fP and \fRnode\&.spaces\&.after\fP depending on the presence of comments or other whitespace characters\&. If the actual whitespace does not start or end with a single space, the node's raw value is set to the actual space(s) found in the source\&.
.SS "\fRnode\&.source\fP"
An object describing the node's start/end, line/column source position\&.

.PP
Within the following CSS, the \fR\&.bar\fP class node \&.\&.\&.

.PP
.PP
.nf
\&.foo,
  \&.bar {}
.fi
.PP

.PP
\&.\&.\&. will contain the following \fRsource\fP object\&.

.PP
.PP
.nf
source: {
    start: {
        line: 2,
        column: 3
    },
    end: {
        line: 2,
        column: 6
    }
}
.fi
.PP
.SS "\fRnode\&.sourceIndex\fP"
The zero-based index of the node within the original source string\&.

.PP
Within the following CSS, the \fR\&.baz\fP class node will have a \fRsourceIndex\fP of \fR12\fP\&.

.PP
.PP
.nf
\&.foo, \&.bar, \&.baz {}
.fi
.PP
.SH "Container types"
.PP
The \fRroot\fP, \fRselector\fP, and \fRpseudo\fP nodes have some helper methods for working with their children\&.
.SS "\fRcontainer\&.nodes\fP"
An array of the container's children\&.

.PP
.PP
.nf
// Input: h1 h2
selectors\&.at(0)\&.nodes\&.length   // => 3
selectors\&.at(0)\&.nodes[0]\&.value // => 'h1'
selectors\&.at(0)\&.nodes[1]\&.value // => ' '
.fi
.PP
.SS "\fRcontainer\&.first\fP & \fRcontainer\&.last\fP"
The first/last child of the container\&.

.PP
.PP
.nf
selector\&.first === selector\&.nodes[0];
selector\&.last === selector\&.nodes[selector\&.nodes\&.length \- 1];
.fi
.PP
.SS "\fRcontainer\&.at(index)\fP"
Returns the node at position \fRindex\fP\&.

.PP
.PP
.nf
selector\&.at(0) === selector\&.first;
selector\&.at(0) === selector\&.nodes[0];
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRindex\fP: The index of the node to return\&.
.PP
.SS "\fRcontainer\&.atPosition(line, column)\fP"
Returns the node at the source position \fRindex\fP\&.

.PP
.PP
.nf
selector\&.at(0) === selector\&.first;
selector\&.at(0) === selector\&.nodes[0];
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRindex\fP: The index of the node to return\&.
.PP
.SS "\fRcontainer\&.index(node)\fP"
Return the index of the node within its container\&.

.PP
.PP
.nf
selector\&.index(selector\&.nodes[2]) // => 2
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRnode\fP: A node within the current container\&.
.PP
.SS "\fRcontainer\&.length\fP"
Proxy to the length of the container's nodes\&.

.PP
.PP
.nf
container\&.length === container\&.nodes\&.length
.fi
.PP
.SS "\fRcontainer\fP Array iterators"
The container class provides proxies to certain Array methods; these are:

.PP
.IP "\(bu" 2
\fRcontainer\&.map === container\&.nodes\&.map\fP
.IP "\(bu" 2
\fRcontainer\&.reduce === container\&.nodes\&.reduce\fP
.IP "\(bu" 2
\fRcontainer\&.every === container\&.nodes\&.every\fP
.IP "\(bu" 2
\fRcontainer\&.some === container\&.nodes\&.some\fP
.IP "\(bu" 2
\fRcontainer\&.filter === container\&.nodes\&.filter\fP
.IP "\(bu" 2
\fRcontainer\&.sort === container\&.nodes\&.sort\fP
.PP

.PP
Note that these methods only work on a container's immediate children; recursive iteration is provided by \fRcontainer\&.walk\fP\&.
.SS "\fRcontainer\&.each(callback)\fP"
Iterate the container's immediate children, calling \fRcallback\fP for each child\&. You may return \fRfalse\fP within the callback to break the iteration\&.

.PP
.PP
.nf
let className;
selectors\&.each((selector, index) => {
    if (selector\&.type === 'class') {
        className = selector\&.value;
        return false;
    }
});
.fi
.PP

.PP
Note that unlike \fRArray#forEach()\fP, this iterator is safe to use whilst adding or removing nodes from the container\&.

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRcallback (function)\fP: A function to call for each node, which receives \fRnode\fP and \fRindex\fP arguments\&.
.PP
.SS "\fRcontainer\&.walk(callback)\fP"
Like \fRcontainer#each\fP, but will also iterate child nodes as long as they are \fRcontainer\fP types\&.

.PP
.PP
.nf
selectors\&.walk((selector, index) => {
    // all nodes
});
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRcallback (function)\fP: A function to call for each node, which receives \fRnode\fP and \fRindex\fP arguments\&.
.PP

.PP
This iterator is safe to use whilst mutating \fRcontainer\&.nodes\fP, like \fRcontainer#each\fP\&.
.SS "\fRcontainer\&.walk\fP proxies"
The container class provides proxy methods for iterating over types of nodes, so that it is easier to write modules that target specific selectors\&. Those methods are:

.PP
.IP "\(bu" 2
\fRcontainer\&.walkAttributes\fP
.IP "\(bu" 2
\fRcontainer\&.walkClasses\fP
.IP "\(bu" 2
\fRcontainer\&.walkCombinators\fP
.IP "\(bu" 2
\fRcontainer\&.walkComments\fP
.IP "\(bu" 2
\fRcontainer\&.walkIds\fP
.IP "\(bu" 2
\fRcontainer\&.walkNesting\fP
.IP "\(bu" 2
\fRcontainer\&.walkPseudos\fP
.IP "\(bu" 2
\fRcontainer\&.walkTags\fP
.IP "\(bu" 2
\fRcontainer\&.walkUniversals\fP
.PP
.SS "\fRcontainer\&.split(callback)\fP"
This method allows you to split a group of nodes by returning \fRtrue\fP from a callback\&. It returns an array of arrays, where each inner array corresponds to the groups that you created via the callback\&.

.PP
.PP
.nf
// (input) => h1 h2>>h3
const list = selectors\&.first\&.split(selector => {
    return selector\&.type === 'combinator';
});

// (node values) => [['h1', ' '], ['h2', '>>'], ['h3']]
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRcallback (function)\fP: A function to call for each node, which receives \fRnode\fP as an argument\&.
.PP
.SS "\fRcontainer\&.prepend(node)\fP & \fRcontainer\&.append(node)\fP"
Add a node to the start/end of the container\&. Note that doing so will set the parent property of the node to this container\&.

.PP
.PP
.nf
const id = parser\&.id({value: 'search'});
selector\&.append(id);
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRnode\fP: The node to add\&.
.PP
.SS "\fRcontainer\&.insertBefore(old, new)\fP & \fRcontainer\&.insertAfter(old, new)\fP"
Add a node before or after an existing node in a container:

.PP
.PP
.nf
selectors\&.walk(selector => {
    if (selector\&.type !== 'class') {
        const className = parser\&.className({value: 'theme\-name'});
        selector\&.parent\&.insertAfter(selector, className);
    }
});
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRold\fP: The existing node in the container\&.
.IP "\(bu" 2
\fRnew\fP: The new node to add before/after the existing node\&.
.PP
.SS "\fRcontainer\&.removeChild(node)\fP"
Remove the node from the container\&. Note that you can also use \fRnode\&.remove()\fP if you would like to remove just a single node\&.

.PP
.PP
.nf
selector\&.length // => 2
selector\&.remove(id)
selector\&.length // => 1;
id\&.parent       // undefined
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRnode\fP: The node to remove\&.
.PP
.SS "\fRcontainer\&.removeAll()\fP or \fRcontainer\&.empty()\fP"
Remove all children from the container\&.

.PP
.PP
.nf
selector\&.removeAll();
selector\&.length // => 0
.fi
.PP
.SH "Root nodes"
.PP
A root node represents a comma separated list of selectors\&. Indeed, all a root's \fRtoString()\fP method does is join its selector children with a ','\&. Other than this, it has no special functionality and acts like a container\&.
.SS "\fRroot\&.trailingComma\fP"
This will be set to \fRtrue\fP if the input has a trailing comma, in order to support parsing of legacy CSS hacks\&.
.SH "Selector nodes"
.PP
A selector node represents a single complex selector\&. For example, this selector string \fRh1 h2 h3, [href] > p\fP, is represented as two selector nodes\&. It has no special functionality of its own\&.
.SH "Pseudo nodes"
.PP
A pseudo selector extends a container node; if it has any parameters of its own (such as \fRh1:not(h2, h3)\fP), they will be its children\&. Note that the pseudo \fRvalue\fP will always contain the colons preceding the pseudo identifier\&. This is so that both \fR:before\fP and \fR::before\fP are properly represented in the AST\&.
.SH "Attribute nodes"
.PP
.SS "\fRattribute\&.quoted\fP"
Returns \fRtrue\fP if the attribute's value is wrapped in quotation marks, false if it is not\&. Remains \fRundefined\fP if there is no attribute value\&.

.PP
.PP
.nf
[href=foo] /* false */
[href='foo'] /* true */
[href="foo"] /* true */
[href] /* undefined */
.fi
.PP
.SS "\fRattribute\&.qualifiedAttribute\fP"
Returns the attribute name qualified with the namespace if one is given\&.
.SS "\fRattribute\&.offsetOf(part)\fP"
Returns the offset of the attribute part specified relative to the start of the node of the output string\&. This is useful in raising error messages about a specific part of the attribute, especially in combination with \fRattribute\&.sourceIndex\fP\&.

.PP
Returns \fR-1\fP if the name is invalid or the value doesn't exist in this attribute\&.

.PP
The legal values for \fRpart\fP are:

.PP
.IP "\(bu" 2
\fR"ns"\fP - alias for "namespace"
.IP "\(bu" 2
\fR"namespace"\fP - the namespace if it exists\&.
.IP "\(bu" 2
\fR"attribute"\fP - the attribute name
.IP "\(bu" 2
\fR"attributeNS"\fP - the start of the attribute or its namespace
.IP "\(bu" 2
\fR"operator"\fP - the match operator of the attribute
.IP "\(bu" 2
\fR"value"\fP - The value (string or identifier)
.IP "\(bu" 2
\fR"insensitive"\fP - the case insensitivity flag
.PP
.SS "\fRattribute\&.raws\&.unquoted\fP"
Returns the unquoted content of the attribute's value\&. Remains \fRundefined\fP if there is no attribute value\&.

.PP
.PP
.nf
[href=foo] /* foo */
[href='foo'] /* foo */
[href="foo"] /* foo */
[href] /* undefined */
.fi
.PP
.SS "\fRattribute\&.spaces\fP"
Like \fRnode\&.spaces\fP with the \fRbefore\fP and \fRafter\fP values containing the spaces around the element, the parts of the attribute can also have spaces before and after them\&. The for each of \fRattribute\fP, \fRoperator\fP, \fRvalue\fP and \fRinsensitive\fP there is corresponding property of the same nam in \fRnode\&.spaces\fP that has an optional \fRbefore\fP or \fRafter\fP string containing only whitespace\&.

.PP
Note that corresponding values in \fRattributes\&.raws\&.spaces\fP contain values including any comments\&. If set, these values will override the \fRattribute\&.spaces\fP value\&. Take care to remove them if changing \fRattribute\&.spaces\fP\&.
.SS "\fRattribute\&.raws\fP"
The raws object stores comments and other information necessary to re-render the node exactly as it was in the source\&.

.PP
If a comment is embedded within the identifiers for the \fRnamespace\fP, \fRattribute\fP or \fRvalue\fP then a property is placed in the raws for that value containing the full source of the propery including comments\&.

.PP
If a comment is embedded within the space between parts of the attribute then the raw for that space is set accordingly\&.

.PP
Setting an attribute's property \fRraws\fP value to be deleted\&.

.PP
For now, changing the spaces required also updating or removing any of the raws values that override them\&.

.PP
Example: \fR[ /*before*/ href /* after-attr */ = /* after-operator */ te/*inside-value*/st/* wow */ /*omg*/i/*bbq*/ /*whodoesthis*/]\fP would parse as:

.PP
.PP
.nf
{
  attribute: "href",
  operator: "=",
  value: "test",
  spaces: {
    before: '',
    after: '',
    attribute: { before: '  ', after: '  ' },
    operator: { after: '  ' },
    value: { after: ' ' },
    insensitive: { after: ' ' }
  },
  raws: {
    spaces: {
      attribute: { before: ' /*before*/ ', after: ' /* after\-attr */ ' },
      operator: { after: ' /* after\-operator */ ' },
      value: { after: '/* wow */ /*omg*/' },
      insensitive: { after: '/*bbq*/ /*whodoesthis*/' }
    },
    unquoted: 'test',
    value: 'te/*inside\-value*/st'
  }
}
.fi
.PP
.SH "\fRProcessor\fP"
.PP
.SS "\fRProcessorOptions\fP"
.IP "\(bu" 2
\fRlossless\fP - When \fRtrue\fP, whitespace is preserved\&. Defaults to \fRtrue\fP\&.
.IP "\(bu" 2
\fRupdateSelector\fP - When \fRtrue\fP, if any processor methods are passed a postcss \fRRule\fP node instead of a string, then that Rule's selector is updated with the results of the processing\&. Defaults to \fRtrue\fP\&.
.PP
.SS "\fRprocess|processSync(selectors, [options])\fP"
Processes the \fRselectors\fP, returning a string from the result of processing\&.

.PP
Note: when the \fRupdateSelector\fP option is set, the rule's selector will be updated with the resulting string\&.

.PP
\fBExample:\fP

.PP
.PP
.nf
const parser = require("postcss\-selector\-parser");
const processor = parser();

let result = processor\&.processSync(' \&.class');
console\&.log(result);
// =>  \&.class

// Asynchronous operation
let promise = processor\&.process(' \&.class')\&.then(result => {
    console\&.log(result)
    // => \&.class
});

// To have the parser normalize whitespace values, utilize the options
result = processor\&.processSync('  \&.class  ', {lossless: false});
console\&.log(result);
// => \&.class

// For better syntax errors, pass a PostCSS Rule node\&.
const postcss = require('postcss');
rule = postcss\&.rule({selector: ' #foo    > a,  \&.class  '});
processor\&.process(rule, {lossless: false, updateSelector: true})\&.then(result => {
    console\&.log(result);
    // => #foo>a,\&.class
    console\&.log("rule:", rule\&.selector);
    // => rule: #foo>a,\&.class
})
.fi
.PP

.PP
Arguments:

.PP
.IP "\(bu" 2
\fRselectors (string|postcss\&.Rule)\fP: Either a selector string or a PostCSS Rule node\&.
.IP "\(bu" 2
\fR[options] (object)\fP: Process options
.PP
.SS "\fRast|astSync(selectors, [options])\fP"
Like \fRprocess()\fP and \fRprocessSync()\fP but after processing the \fRselectors\fP these methods return the \fRRoot\fP node of the result instead of a string\&.

.PP
Note: when the \fRupdateSelector\fP option is set, the rule's selector will be updated with the resulting string\&.
.SS "\fRtransform|transformSync(selectors, [options])\fP"
Like \fRprocess()\fP and \fRprocessSync()\fP but after processing the \fRselectors\fP these methods return the value returned by the processor callback\&.

.PP
Note: when the \fRupdateSelector\fP option is set, the rule's selector will be updated with the resulting string\&.
.SS "Error Handling Within Selector Processors"
The root node passed to the selector processor callback has a method \fRerror(message, options)\fP that returns an error object\&. This method should always be used to raise errors relating to the syntax of selectors\&. The options to this method are passed to postcss's error constructor (\fRdocumentation\fP)\&.
.SS "Async Error Example"
.PP
.nf
let processor = (root) => {
    return new Promise((resolve, reject) => {
        root\&.walkClasses((classNode) => {
            if (/^(\&.*)[\-_]/\&.test(classNode\&.value)) {
                let msg = "classes may not have underscores or dashes in them";
                reject(root\&.error(msg, {
                    index: classNode\&.sourceIndex + RegExp\&.$1\&.length + 1,
                    word: classNode\&.value
                }));
            }
        });
        resolve();
    });
};

const postcss = require("postcss");
const parser = require("postcss\-selector\-parser");
const selectorProcessor = parser(processor);
const plugin = postcss\&.plugin('classValidator', (options) => {
    return (root) => {
        let promises = [];
        root\&.walkRules(rule => {
            promises\&.push(selectorProcessor\&.process(rule));
        });
        return Promise\&.all(promises);
    };
});
postcss(plugin())\&.process(`
\&.foo\-bar {
  color: red;
}
`\&.trim(), {from: 'test\&.css'})\&.catch((e) => console\&.error(e\&.toString()));

// CssSyntaxError: classValidator: \&./test\&.css:1:5: classes may not have underscores or dashes in them
//
// > 1 | \&.foo\-bar {
//     |     ^
//   2 |   color: red;
//   3 | }
.fi
.PP
.SS "Synchronous Error Example"
.PP
.nf
let processor = (root) => {
    root\&.walkClasses((classNode) => {
        if (/\&.*[\-_]/\&.test(classNode\&.value)) {
            let msg = "classes may not have underscores or dashes in them";
            throw root\&.error(msg, {
                index: classNode\&.sourceIndex,
                word: classNode\&.value
            });
        }
    });
};

const postcss = require("postcss");
const parser = require("postcss\-selector\-parser");
const selectorProcessor = parser(processor);
const plugin = postcss\&.plugin('classValidator', (options) => {
    return (root) => {
        root\&.walkRules(rule => {
            selectorProcessor\&.processSync(rule);
        });
    };
});
postcss(plugin())\&.process(`
\&.foo\-bar {
  color: red;
}
`\&.trim(), {from: 'test\&.css'})\&.catch((e) => console\&.error(e\&.toString()));

// CssSyntaxError: classValidator: \&./test\&.css:1:5: classes may not have underscores or dashes in them
//
// > 1 | \&.foo\-bar {
//     |     ^
//   2 |   color: red;
//   3 | }
.fi
.PP
 
