.TH "md_frontend_2node__modules_2date-fns_2docs_2webpack" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2date-fns_2docs_2webpack \- webpack 
.PP

.SH "Removing unused languages from dynamic import"
.PP
If a locale is imported dynamically, then all locales from date-fns are loaded by webpack into a bundle (~160kb) or split across the chunks\&. This prolongs the build process and increases the amount of space taken\&. However, it is possible to use webpack to trim down languages using \fRContextReplacementPlugin\fP\&.

.PP
Let's assume that we have a single point in which supported locales are present:

.PP
\fRconfig\&.js\fP:

.PP
.PP
.nf
// `see date\-fns/src/locale` for available locales
export const supportedLocales = ["en\-US", "de", "pl", "it"];
.fi
.PP

.PP
We could also have a function that formats the date:

.PP
.PP
.nf
const getLocale = (locale) => import(`date\-fns/locale/${locale}/index\&.js`); // or require() if using CommonJS

const formatDate = (date, formatStyle, locale) => {
  return format(date, formatStyle, {
    locale: getLocale(locale),
  });
};
.fi
.PP

.PP
In order to exclude unused languages we can use webpacks \fRContextReplacementPlugin\fP\&.

.PP
\fRwebpack\&.config\&.js\fP:

.PP
.PP
.nf
import webpack from 'webpack'
import { supportedLocales } from '\&./config\&.js'

export default const config = {
  plugins: [
    new webpack\&.ContextReplacementPlugin(
      /^date\-fns[/\\\\]locale$/,
      new RegExp(`\\\\\&.[/\\\\\\\\](${supportedLocales\&.join('|')})[/\\\\\\\\]index\\\\\&.js$`)
    )
  ]
}
.fi
.PP

.PP
This results in a language bundle of ~23kb \&. 
