.TH "md_frontend_2node__modules_2react-router_2_c_h_a_n_g_e_l_o_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2react-router_2_c_h_a_n_g_e_l_o_g \- \fRreact-router\fP 
.PP

.SH "6\&.30\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Partially revert optimization added in \fR6\&.29\&.0\fP to reduce calls to \fRmatchRoutes\fP because it surfaced other issues (\fR#13623\fP)
.IP "\(bu" 2
Stop logging invalid warning when \fRv7_relativeSplatPath\fP is set to false (\fR#13502\fP)
.PP
.SH "6\&.30\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add \fRfetcherKey\fP as a parameter to \fRpatchRoutesOnNavigation\fP (\fR#13109\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.23\&.0\fP
.PP

.PP
.SH "6\&.29\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Provide the request \fRsignal\fP as a parameter to \fRpatchRoutesOnNavigation\fP (\fR#12900\fP)
.IP "  \(bu" 4
This can be used to abort any manifest fetches if the in-flight navigation/fetcher is aborted
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Do not log v7 deprecation warnings in production builds (\fR#12794\fP)
.IP "\(bu" 2
Limit matchRoutes optimization to client side routers (\fR#12881\fP)
.IP "\(bu" 2
Optimize route matching by skipping redundant \fRmatchRoutes\fP calls when possible (\fR#12169\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.22\&.0\fP
.PP

.PP
.SH "6\&.28\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.21\&.1\fP
.PP

.PP
.SH "6\&.28\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Allow users to opt out of deprecation warnings by setting flags to false (\fR#12441\fP)
.PP
.SH "6\&.28\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Log deprecation warnings for v7 flags (\fR#11750\fP)
.IP "  \(bu" 4
Add deprecation warnings to \fRjson\fP/\fRdefer\fP in favor of returning raw objects
.IP "    \(bu" 6
These methods will be removed in React Router v7
.PP

.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Update JSDoc URLs for new website structure (add /v6/ segment) (\fR#12141\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.21\&.0\fP
.PP

.PP
.SH "6\&.27\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Stabilize \fRunstable_patchRoutesOnNavigation\fP (\fR#11973\fP)
.IP "  \(bu" 4
Add new \fRPatchRoutesOnNavigationFunctionArgs\fP type for convenience (\fR#11967\fP)
.PP

.IP "\(bu" 2
Stabilize \fRunstable_dataStrategy\fP (\fR#11974\fP)
.IP "\(bu" 2
Stabilize the \fRunstable_flushSync\fP option for navigations and fetchers (\fR#11989\fP)
.IP "\(bu" 2
Stabilize the \fRunstable_viewTransition\fP option for navigations and the corresponding \fRunstable_useViewTransitionState\fP hook (\fR#11989\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix bug when submitting to the current contextual route (parent route with an index child) when an \fR?index\fP param already exists from a prior submission (\fR#12003\fP)
.IP "\(bu" 2
Fix \fRuseFormAction\fP bug - when removing \fR?index\fP param it would not keep other non-Remix \fRindex\fP params (\fR#12003\fP)
.IP "\(bu" 2
Fix types for \fRRouteObject\fP within \fRPatchRoutesOnNavigationFunction\fP's \fRpatch\fP method so it doesn't expect agnostic route objects passed to \fRpatch\fP (\fR#11967\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.20\&.0\fP
.PP

.PP
.SH "6\&.26\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.19\&.2\fP
.PP

.PP
.SH "6\&.26\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Rename \fRunstable_patchRoutesOnMiss\fP to \fRunstable_patchRoutesOnNavigation\fP to match new behavior (\fR#11888\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.19\&.1\fP
.PP

.PP
.SH "6\&.26\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add a new \fRreplace(url, init?)\fP alternative to \fRredirect(url, init?)\fP that performs a \fRhistory\&.replaceState\fP instead of a \fRhistory\&.pushState\fP on client-side navigation redirects (\fR#11811\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix initial hydration behavior when using \fRfuture\&.v7_partialHydration\fP along with \fRunstable_patchRoutesOnMiss\fP (\fR#11838\fP)
.IP "  \(bu" 4
During initial hydration, \fRrouter\&.state\&.matches\fP will now include any partial matches so that we can render ancestor \fRHydrateFallback\fP components
.PP

.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.19\&.0\fP
.PP

.PP
.SH "6\&.25\&.1"
.PP
No significant changes to this package were made in this release\&. \fRSee the repo \fRCHANGELOG\&.md\fP\fP for an overview of all changes in v6\&.25\&.1\&.
.SH "6\&.25\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Stabilize \fRfuture\&.unstable_skipActionErrorRevalidation\fP as \fRfuture\&.v7_skipActionErrorRevalidation\fP (\fR#11769\fP)
.IP "  \(bu" 4
When this flag is enabled, actions will not automatically trigger a revalidation if they return/throw a \fRResponse\fP with a \fR4xx\fP/\fR5xx\fP status code
.IP "  \(bu" 4
You may still opt-into revalidation via \fRshouldRevalidate\fP
.IP "  \(bu" 4
This also changes \fRshouldRevalidate\fP's \fRunstable_actionStatus\fP parameter to \fRactionStatus\fP
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix regression and properly decode paths inside \fRuseMatch\fP so matches/params reflect decoded params (\fR#11789\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.18\&.0\fP
.PP

.PP
.SH "6\&.24\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
When using \fRfuture\&.v7_relativeSplatPath\fP, properly resolve relative paths in splat routes that are children of pathless routes (\fR#11633\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.17\&.1\fP
.PP

.PP
.SH "6\&.24\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add support for Lazy Route Discovery (a\&.k\&.a\&. Fog of War) (\fR#11626\fP)
.IP "  \(bu" 4
RFC: https://github.com/remix-run/react-router/discussions/11113
.IP "  \(bu" 4
\fRunstable_patchRoutesOnMiss\fP docs: https://reactrouter.com/v6/routers/create-browser-router
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.17\&.0\fP
.PP

.PP
.SH "6\&.23\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
allow undefined to be resolved with \fR<Await>\fP (\fR#11513\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.16\&.1\fP
.PP

.PP
.SH "6\&.23\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add a new \fRunstable_dataStrategy\fP configuration option (\fR#11098\fP)
.IP "  \(bu" 4
This option allows Data Router applications to take control over the approach for executing route loaders and actions
.IP "  \(bu" 4
The default implementation is today's behavior, to fetch all loaders in parallel, but this option allows users to implement more advanced data flows including Remix single-fetch, middleware/context APIs, automatic loader caching, and more
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.16\&.0\fP
.PP

.PP
.SH "6\&.22\&.3"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.15\&.3\fP
.PP

.PP
.SH "6\&.22\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.15\&.2\fP
.PP

.PP
.SH "6\&.22\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix encoding/decoding issues with pre-encoded dynamic parameter values (\fR#11199\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.15\&.1\fP
.PP

.PP
.SH "6\&.22\&.0"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.15\&.0\fP
.PP

.PP
.SH "6\&.21\&.3"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Remove leftover \fRunstable_\fP prefix from \fRBlocker\fP/\fRBlockerFunction\fP types (\fR#11187\fP)
.PP
.SH "6\&.21\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.14\&.2\fP
.PP

.PP
.SH "6\&.21\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix bug with \fRroute\&.lazy\fP not working correctly on initial SPA load when \fRv7_partialHydration\fP is specified (\fR#11121\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.14\&.1\fP
.PP

.PP
.SH "6\&.21\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add a new \fRfuture\&.v7_relativeSplatPath\fP flag to implement a breaking bug fix to relative routing when inside a splat route\&. (\fR#11087\fP)

.PP
This fix was originally added in \fR#10983\fP and was later reverted in \fR#11078\fP because it was determined that a large number of existing applications were relying on the buggy behavior (see \fR#11052\fP)

.PP
\fBThe Bug\fP The buggy behavior is that without this flag, the default behavior when resolving relative paths is to \fIignore\fP any splat (\fR*\fP) portion of the current route path\&.

.PP
\fBThe Background\fP This decision was originally made thinking that it would make the concept of nested different sections of your apps in \fR<Routes>\fP easier if relative routing would \fIreplace\fP the current splat:

.PP
.PP
.nf
<BrowserRouter>
  <Routes>
    <Route path="/" element={<Home />} />
    <Route path="dashboard/*" element={<Dashboard />} />
  </Routes>
</BrowserRouter>
.fi
.PP

.PP
Any paths like \fR/dashboard\fP, \fR/dashboard/team\fP, \fR/dashboard/projects\fP will match the \fRDashboard\fP route\&. The dashboard component itself can then render nested \fR<Routes>\fP:

.PP
.PP
.nf
function Dashboard() {
  return (
    <div>
      <h2>Dashboard</h2>
      <nav>
        <Link to="/">Dashboard Home</Link>
        <Link to="team">Team</Link>
        <Link to="projects">Projects</Link>
      </nav>

      <Routes>
        <Route path="/" element={<DashboardHome />} />
        <Route path="team" element={<DashboardTeam />} />
        <Route path="projects" element={<DashboardProjects />} />
      </Routes>
    </div>
  );
}
.fi
.PP

.PP
Now, all links and route paths are relative to the router above them\&. This makes code splitting and compartmentalizing your app really easy\&. You could render the \fRDashboard\fP as its own independent app, or embed it into your large app without making any changes to it\&.

.PP
\fBThe Problem\fP

.PP
The problem is that this concept of ignoring part of a path breaks a lot of other assumptions in React Router - namely that \fR"\&."\fP always means the current location pathname for that route\&. When we ignore the splat portion, we start getting invalid paths when using \fR"\&."\fP:

.PP
.PP
.nf
// If we are on URL /dashboard/team, and we want to link to /dashboard/team:
function DashboardTeam() {
  // ❌ This is broken and results in <a href="/dashboard">
  return <Link to="\&.">A broken link to the Current URL</Link>;

  // ✅ This is fixed but super unintuitive since we're already at /dashboard/team!
  return <Link to="\&./team">A broken link to the Current URL</Link>;
}
.fi
.PP

.PP
We've also introduced an issue that we can no longer move our \fRDashboardTeam\fP component around our route hierarchy easily - since it behaves differently if we're underneath a non-splat route, such as \fR/dashboard/:widget\fP\&. Now, our \fR"\&."\fP links will, properly point to ourself \fIinclusive of the dynamic param value\fP so behavior will break from it's corresponding usage in a \fR/dashboard/*\fP route\&.

.PP
Even worse, consider a nested splat route configuration:

.PP
.PP
.nf
<BrowserRouter>
  <Routes>
    <Route path="dashboard">
      <Route path="*" element={<Dashboard />} />
    </Route>
  </Routes>
</BrowserRouter>
.fi
.PP

.PP
Now, a \fR<Link to="\&.">\fP and a \fR<Link to="\&.\&.">\fP inside the \fRDashboard\fP component go to the same place! That is definitely not correct!

.PP
Another common issue arose in Data Routers (and Remix) where any \fR<Form>\fP should post to it's own route \fRaction\fP if you the user doesn't specify a form action:

.PP
.PP
.nf
let router = createBrowserRouter({
  path: "/dashboard",
  children: [
    {
      path: "*",
      action: dashboardAction,
      Component() {
        // ❌ This form is broken!  It throws a 405 error when it submits because
        // it tries to submit to /dashboard (without the splat value) and the parent
        // `/dashboard` route doesn't have an action
        return <Form method="post">\&.\&.\&.</Form>;
      },
    },
  ],
});
.fi
.PP

.PP
This is just a compounded issue from the above because the default location for a \fRForm\fP to submit to is itself (\fR"\&."\fP) - and if we ignore the splat portion, that now resolves to the parent route\&.

.PP
\fBThe Solution\fP If you are leveraging this behavior, it's recommended to enable the future flag, move your splat to it's own route, and leverage \fR\&.\&./\fP for any links to "sibling" pages:

.PP
.PP
.nf
<BrowserRouter>
  <Routes>
    <Route path="dashboard">
      <Route index path="*" element={<Dashboard />} />
    </Route>
  </Routes>
</BrowserRouter>

function Dashboard() {
  return (
    <div>
      <h2>Dashboard</h2>
      <nav>
        <Link to="\&.\&.">Dashboard Home</Link>
        <Link to="\&.\&./team">Team</Link>
        <Link to="\&.\&./projects">Projects</Link>
      </nav>

      <Routes>
        <Route path="/" element={<DashboardHome />} />
        <Route path="team" element={<DashboardTeam />} />
        <Route path="projects" element={<DashboardProjects />} />
      </Router>
    </div>
  );
}
.fi
.PP

.PP
This way, \fR\&.\fP means "the full current pathname for my route" in all cases (including static, dynamic, and splat routes) and \fR\&.\&.\fP always means "my parents pathname"\&.
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Properly handle falsy error values in ErrorBoundary's (\fR#11071\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.14\&.0\fP
.PP

.PP
.SH "6\&.20\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Revert the \fRuseResolvedPath\fP fix for splat routes due to a large number of applications that were relying on the buggy behavior (see https://github.com/remix-run/react-router/issues/11052#issuecomment-1836589329)\&. We plan to re-introduce this fix behind a future flag in the next minor version\&. (\fR#11078\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.13\&.1\fP
.PP

.PP
.SH "6\&.20\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Export the \fRPathParam\fP type from the public API (\fR#10719\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix bug with \fRresolveTo\fP in splat routes (\fR#11045\fP)
.IP "  \(bu" 4
This is a follow up to \fR#10983\fP to handle the few other code paths using \fRgetPathContributingMatches\fP
.IP "  \(bu" 4
This removes the \fRUNSAFE_getPathContributingMatches\fP export from \fR@remix-run/router\fP since we no longer need this in the \fRreact-router\fP/\fRreact-router-dom\fP layers
.PP

.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.13\&.0\fP
.PP

.PP
.SH "6\&.19\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add \fRunstable_flushSync\fP option to \fRuseNavigate\fP/\fRuseSumbit\fP/\fRfetcher\&.load\fP/\fRfetcher\&.submit\fP to opt-out of \fRReact\&.startTransition\fP and into \fRReactDOM\&.flushSync\fP for state updates (\fR#11005\fP)
.IP "\(bu" 2
Remove the \fRunstable_\fP prefix from the \fR\fRuseBlocker\fP\fP hook as it's been in use for enough time that we are confident in the API\&. We do not plan to remove the prefix from \fRunstable_usePrompt\fP due to differences in how browsers handle \fRwindow\&.confirm\fP that prevent React Router from guaranteeing consistent/correct behavior\&. (\fR#10991\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRuseActionData\fP so it returns proper contextual action data and not \fIany\fP action data in the tree (\fR#11023\fP)
.IP "\(bu" 2
Fix bug in \fRuseResolvedPath\fP that would cause \fRuseResolvedPath("\&.")\fP in a splat route to lose the splat portion of the URL path\&. (\fR#10983\fP)
.IP "  \(bu" 4
⚠️ This fixes a quite long-standing bug specifically for \fR"\&."\fP paths inside a splat route which incorrectly dropped the splat portion of the URL\&. If you are relative routing via \fR"\&."\fP inside a splat route in your application you should double check that your logic is not relying on this buggy behavior and update accordingly\&.
.PP

.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.12\&.0\fP
.PP

.PP
.SH "6\&.18\&.0"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix the \fRfuture\fP prop on \fRBrowserRouter\fP, \fRHashRouter\fP and \fRMemoryRouter\fP so that it accepts a \fRPartial<FutureConfig>\fP instead of requiring all flags to be included\&. (\fR#10962\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.11\&.0\fP
.PP

.PP
.SH "6\&.17\&.0"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRRouterProvider\fP \fRfuture\fP prop type to be a \fRPartial<FutureConfig>\fP so that not all flags must be specified (\fR#10900\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.10\&.0\fP
.PP

.PP
.SH "6\&.16\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
In order to move towards stricter TypeScript support in the future, we're aiming to replace current usages of \fRany\fP with \fRunknown\fP on exposed typings for user-provided data\&. To do this in Remix v2 without introducing breaking changes in React Router v6, we have added generics to a number of shared types\&. These continue to default to \fRany\fP in React Router and are overridden with \fRunknown\fP in Remix\&. In React Router v7 we plan to move these to \fRunknown\fP as a breaking change\&. (\fR#10843\fP)
.IP "  \(bu" 4
\fRLocation\fP now accepts a generic for the \fRlocation\&.state\fP value
.IP "  \(bu" 4
\fRActionFunctionArgs\fP/\fRActionFunction\fP/\fRLoaderFunctionArgs\fP/\fRLoaderFunction\fP now accept a generic for the \fRcontext\fP parameter (only used in SSR usages via \fRcreateStaticHandler\fP)
.IP "  \(bu" 4
The return type of \fRuseMatches\fP (now exported as \fRUIMatch\fP) accepts generics for \fRmatch\&.data\fP and \fRmatch\&.handle\fP - both of which were already set to \fRunknown\fP
.PP

.IP "\(bu" 2
Move the \fR@private\fP class export \fRErrorResponse\fP to an \fRUNSAFE_ErrorResponseImpl\fP export since it is an implementation detail and there should be no construction of \fRErrorResponse\fP instances in userland\&. This frees us up to export a \fRtype ErrorResponse\fP which correlates to an instance of the class via \fRInstanceType\fP\&. Userland code should only ever be using \fRErrorResponse\fP as a type and should be type-narrowing via \fRisRouteErrorResponse\fP\&. (\fR#10811\fP)
.IP "\(bu" 2
Export \fRShouldRevalidateFunctionArgs\fP interface (\fR#10797\fP)
.IP "\(bu" 2
Removed private/internal APIs only required for the Remix v1 backwards compatibility layer and no longer needed in Remix v2 (\fR_isFetchActionRedirect\fP, \fR_hasFetcherDoneAnything\fP) (\fR#10715\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.9\&.0\fP
.PP

.PP
.SH "6\&.15\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add's a new \fRredirectDocument()\fP function which allows users to specify that a redirect from a \fRloader\fP/\fRaction\fP should trigger a document reload (via \fRwindow\&.location\fP) instead of attempting to navigate to the redirected location via React Router (\fR#10705\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Ensure \fRuseRevalidator\fP is referentially stable across re-renders if revalidations are not actively occurring (\fR#10707\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.8\&.0\fP
.PP

.PP
.SH "6\&.14\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.7\&.2\fP
.PP

.PP
.SH "6\&.14\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix loop in \fRunstable_useBlocker\fP when used with an unstable blocker function (\fR#10652\fP)
.IP "\(bu" 2
Fix issues with reused blockers on subsequent navigations (\fR#10656\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.7\&.1\fP
.PP

.PP
.SH "6\&.14\&.0"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Strip \fRbasename\fP from locations provided to \fRunstable_useBlocker\fP functions to match \fRuseLocation\fP (\fR#10573\fP)
.IP "\(bu" 2
Fix \fRgeneratePath\fP when passed a numeric \fR0\fP value parameter (\fR#10612\fP)
.IP "\(bu" 2
Fix \fRunstable_useBlocker\fP key issues in \fRStrictMode\fP (\fR#10573\fP)
.IP "\(bu" 2
Fix \fRtsc --skipLibCheck:false\fP issues on React 17 (\fR#10622\fP)
.IP "\(bu" 2
Upgrade \fRtypescript\fP to 5\&.1 (\fR#10581\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.7\&.0\fP
.PP

.PP
.SH "6\&.13\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Move \fR\fRReact\&.startTransition\fP\fP usage behind a \fRfuture flag\fP to avoid issues with existing incompatible \fRSuspense\fP usages\&. We recommend folks adopting this flag to be better compatible with React concurrent mode, but if you run into issues you can continue without the use of \fRstartTransition\fP until v7\&. Issues usually boils down to creating net-new promises during the render cycle, so if you run into issues you should either lift your promise creation out of the render cycle or put it behind a \fRuseMemo\fP\&. (\fR#10596\fP)

.PP
Existing behavior will no longer include \fRReact\&.startTransition\fP:

.PP
.PP
.nf
<BrowserRouter>
  <Routes>{/*\&.\&.\&.*/}</Routes>
</BrowserRouter>

<RouterProvider router={router} />
.fi
.PP

.PP
If you wish to enable \fRReact\&.startTransition\fP, pass the future flag to your component:

.PP
.PP
.nf
<BrowserRouter future={{ v7_startTransition: true }}>
  <Routes>{/*\&.\&.\&.*/}</Routes>
</BrowserRouter>

<RouterProvider router={router} future={{ v7_startTransition: true }}/>
.fi
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Work around webpack/terser \fRReact\&.startTransition\fP minification bug in production mode (\fR#10588\fP)
.PP
.SH "6\&.12\&.1"
.PP
.RS 4
[!WARNING] Please use version \fR6\&.13\&.0\fP or later instead of \fR6\&.12\&.1\fP\&. This version suffers from a \fRwebpack\fP/\fRterser\fP minification issue resulting in invalid minified code in your resulting production bundles which can cause issues in your application\&. See \fR#10579\fP for more details\&. 
.RE
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Adjust feature detection of \fRReact\&.startTransition\fP to fix webpack + react 17 compilation error (\fR#10569\fP)
.PP
.SH "6\&.12\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Wrap internal router state updates with \fRReact\&.startTransition\fP if it exists (\fR#10438\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.6\&.3\fP
.PP

.PP
.SH "6\&.11\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRbasename\fP duplication in descendant \fR<Routes>\fP inside a \fR<RouterProvider>\fP (\fR#10492\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.6\&.2\fP
.PP

.PP
.SH "6\&.11\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix usage of \fRComponent\fP API within descendant \fR<Routes>\fP (\fR#10434\fP)
.IP "\(bu" 2
Fix bug when calling \fRuseNavigate\fP from \fR<Routes>\fP inside a \fR<RouterProvider>\fP (\fR#10432\fP)
.IP "\(bu" 2
Fix usage of \fR<Navigate>\fP in strict mode when using a data router (\fR#10435\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.6\&.1\fP
.PP

.PP
.SH "6\&.11\&.0"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Log loader/action errors to the console in dev for easier stack trace evaluation (\fR#10286\fP)
.IP "\(bu" 2
Fix bug preventing rendering of descendant \fR<Routes>\fP when \fRRouterProvider\fP errors existed (\fR#10374\fP)
.IP "\(bu" 2
Fix inadvertent re-renders when using \fRComponent\fP instead of \fRelement\fP on a route definition (\fR#10287\fP)
.IP "\(bu" 2
Fix detection of \fRuseNavigate\fP in the render cycle by setting the \fRactiveRef\fP in a layout effect, allowing the \fRnavigate\fP function to be passed to child components and called in a \fRuseEffect\fP there\&. (\fR#10394\fP)
.IP "\(bu" 2
Switched from \fRuseSyncExternalStore\fP to \fRuseState\fP for internal \fR@remix-run/router\fP router state syncing in \fR<RouterProvider>\fP\&. We found some \fRsubtle bugs\fP where router state updates got propagated \fIbefore\fP other normal \fRuseState\fP updates, which could lead to footguns in \fRuseEffect\fP calls\&. (\fR#10377\fP, \fR#10409\fP)
.IP "\(bu" 2
Allow \fRuseRevalidator()\fP to resolve a loader-driven error boundary scenario (\fR#10369\fP)
.IP "\(bu" 2
Avoid unnecessary unsubscribe/resubscribes on router state changes (\fR#10409\fP)
.IP "\(bu" 2
When using a \fRRouterProvider\fP, \fRuseNavigate\fP/\fRuseSubmit\fP/\fRfetcher\&.submit\fP are now stable across location changes, since we can handle relative routing via the \fR@remix-run/router\fP instance and get rid of our dependence on \fRuseLocation()\fP\&. When using \fRBrowserRouter\fP, these hooks remain unstable across location changes because they still rely on \fRuseLocation()\fP\&. (\fR#10336\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.6\&.0\fP
.PP

.PP
.SH "6\&.10\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Added support for \fR\fBFuture Flags\fP\fP in React Router\&. The first flag being introduced is \fRfuture\&.v7_normalizeFormMethod\fP which will normalize the exposed \fRuseNavigation()/useFetcher()\fP \fRformMethod\fP fields as uppercase HTTP methods to align with the \fRfetch()\fP behavior\&. (\fR#10207\fP)
.IP "  \(bu" 4
When \fRfuture\&.v7_normalizeFormMethod === false\fP (default v6 behavior),
.IP "    \(bu" 6
\fRuseNavigation()\&.formMethod\fP is lowercase
.IP "    \(bu" 6
\fRuseFetcher()\&.formMethod\fP is lowercase
.PP

.IP "  \(bu" 4
When \fRfuture\&.v7_normalizeFormMethod === true\fP:
.IP "    \(bu" 6
\fRuseNavigation()\&.formMethod\fP is uppercase
.IP "    \(bu" 6
\fRuseFetcher()\&.formMethod\fP is uppercase
.PP

.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix route ID generation when using Fragments in \fRcreateRoutesFromElements\fP (\fR#10193\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.5\&.0\fP
.PP

.PP
.SH "6\&.9\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
React Router now supports an alternative way to define your route \fRelement\fP and \fRerrorElement\fP fields as React Components instead of React Elements\&. You can instead pass a React Component to the new \fRComponent\fP and \fRErrorBoundary\fP fields if you choose\&. There is no functional difference between the two, so use whichever approach you prefer 😀\&. You shouldn't be defining both, but if you do \fRComponent\fP/\fRErrorBoundary\fP will "win"\&. (\fR#10045\fP)

.PP
\fBExample JSON Syntax\fP

.PP
.PP
.nf
// Both of these work the same:
const elementRoutes = [{
  path: '/',
  element: <Home />,
  errorElement: <HomeError />,
}]

const componentRoutes = [{
  path: '/',
  Component: Home,
  ErrorBoundary: HomeError,
}]

function Home() { \&.\&.\&. }
function HomeError() { \&.\&.\&. }
.fi
.PP

.PP
\fBExample JSX Syntax\fP

.PP
.PP
.nf
// Both of these work the same:
const elementRoutes = createRoutesFromElements(
  <Route path='/' element={<Home />} errorElement={<HomeError /> } />
);

const componentRoutes = createRoutesFromElements(
  <Route path='/' Component={Home} ErrorBoundary={HomeError} />
);

function Home() { \&.\&.\&. }
function HomeError() { \&.\&.\&. }
.fi
.PP

.IP "\(bu" 2
\fBIntroducing Lazy Route Modules!\fP (\fR#10045\fP)

.PP
In order to keep your application bundles small and support code-splitting of your routes, we've introduced a new \fRlazy()\fP route property\&. This is an async function that resolves the non-route-matching portions of your route definition (\fRloader\fP, \fRaction\fP, \fRelement\fP/\fRComponent\fP, \fRerrorElement\fP/\fRErrorBoundary\fP, \fRshouldRevalidate\fP, \fRhandle\fP)\&.

.PP
Lazy routes are resolved on initial load and during the \fRloading\fP or \fRsubmitting\fP phase of a navigation or fetcher call\&. You cannot lazily define route-matching properties (\fRpath\fP, \fRindex\fP, \fRchildren\fP) since we only execute your lazy route functions after we've matched known routes\&.

.PP
Your \fRlazy\fP functions will typically return the result of a dynamic import\&.

.PP
.PP
.nf
// In this example, we assume most folks land on the homepage so we include that
// in our critical\-path bundle, but then we lazily load modules for /a and /b so
// they don't load until the user navigates to those routes
let routes = createRoutesFromElements(
  <Route path="/" element={<Layout />}>
    <Route index element={<Home />} />
    <Route path="a" lazy={() => import("\&./a")} />
    <Route path="b" lazy={() => import("\&./b")} />
  </Route>
);
.fi
.PP

.PP
Then in your lazy route modules, export the properties you want defined for the route:

.PP
.PP
.nf
export async function loader({ request }) {
  let data = await fetchData(request);
  return json(data);
}

// Export a `Component` directly instead of needing to create a React Element from it
export function Component() {
  let data = useLoaderData();

  return (
    <>
      <h1>You made it!</h1>
      <p>{data}</p>
    </>
  );
}

// Export an `ErrorBoundary` directly instead of needing to create a React Element from it
export function ErrorBoundary() {
  let error = useRouteError();
  return isRouteErrorResponse(error) ? (
    <h1>
      {error\&.status} {error\&.statusText}
    </h1>
  ) : (
    <h1>{error\&.message || error}</h1>
  );
}
.fi
.PP

.PP
An example of this in action can be found in the \fR\fRexamples/lazy-loading-router-provider\fP\fP directory of the repository\&.

.PP
🙌 Huge thanks to @rossipedia for the \fRInitial Proposal\fP and \fRPOC Implementation\fP\&.
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.4\&.0\fP
.PP

.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRgeneratePath\fP incorrectly applying parameters in some cases (\fR#10078\fP)
.IP "\(bu" 2
Improve memoization for context providers to avoid unnecessary re-renders (\fR#9983\fP)
.PP
.SH "6\&.8\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.3\&.3\fP
.PP

.PP
.SH "6\&.8\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Remove inaccurate console warning for POP navigations and update active blocker logic (\fR#10030\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.3\&.2\fP
.PP

.PP
.SH "6\&.8\&.0"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.3\&.1\fP
.PP

.PP
.SH "6\&.7\&.0"
.PP
.SS "Minor Changes"
.IP "\(bu" 2
Add \fRunstable_useBlocker\fP hook for blocking navigations within the app's location origin (\fR#9709\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRgeneratePath\fP when optional params are present (\fR#9764\fP)
.IP "\(bu" 2
Update \fR<Await>\fP to accept \fRReactNode\fP as children function return result (\fR#9896\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.3\&.0\fP
.PP

.PP
.SH "6\&.6\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Ensure \fRuseId\fP consistency during SSR (\fR#9805\fP)
.PP
.SH "6\&.6\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.2\&.1\fP
.PP

.PP
.SH "6\&.6\&.0"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Prevent \fRuseLoaderData\fP usage in \fRerrorElement\fP (\fR#9735\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.2\&.0\fP
.PP

.PP
.SH "6\&.5\&.0"
.PP
This release introduces support for \fROptional Route Segments\fP\&. Now, adding a \fR?\fP to the end of any path segment will make that entire segment optional\&. This works for both static segments and dynamic parameters\&.

.PP
\fBOptional Params Examples\fP

.PP
.IP "\(bu" 2
\fR<Route path=":lang?/about>\fP will match:
.IP "  \(bu" 4
\fR/:lang/about\fP
.IP "  \(bu" 4
\fR/about\fP
.PP

.IP "\(bu" 2
\fR<Route path="/multistep/:widget1?/widget2?/widget3?">\fP will match:
.IP "  \(bu" 4
\fR/multistep\fP
.IP "  \(bu" 4
\fR/multistep/:widget1\fP
.IP "  \(bu" 4
\fR/multistep/:widget1/:widget2\fP
.IP "  \(bu" 4
\fR/multistep/:widget1/:widget2/:widget3\fP
.PP

.PP

.PP
\fBOptional Static Segment Example\fP

.PP
.IP "\(bu" 2
\fR<Route path="/home?">\fP will match:
.IP "  \(bu" 4
\fR/\fP
.IP "  \(bu" 4
\fR/home\fP
.PP

.IP "\(bu" 2
\fR<Route path="/fr?/about">\fP will match:
.IP "  \(bu" 4
\fR/about\fP
.IP "  \(bu" 4
\fR/fr/about\fP
.PP

.PP
.SS "Minor Changes"
.IP "\(bu" 2
Allows optional routes and optional static segments (\fR#9650\fP)
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Stop incorrectly matching on partial named parameters, i\&.e\&. \fR<Route path="prefix-:param">\fP, to align with how splat parameters work\&. If you were previously relying on this behavior then it's recommended to extract the static portion of the path at the \fRuseParams\fP call site: (\fR#9506\fP)
.PP

.PP
.PP
.nf
// Old behavior at URL /prefix\-123
<Route path="prefix\-:id" element={<Comp /> }>

function Comp() {
  let params = useParams(); // { id: '123' }
  let id = params\&.id; // "123"
  \&.\&.\&.
}

// New behavior at URL /prefix\-123
<Route path=":id" element={<Comp /> }>

function Comp() {
  let params = useParams(); // { id: 'prefix\-123' }
  let id = params\&.id\&.replace(/^prefix\-/, ''); // "123"
  \&.\&.\&.
}
.fi
.PP

.PP
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.1\&.0\fP
.PP

.PP
.SH "6\&.4\&.5"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.0\&.5\fP
.PP

.PP
.SH "6\&.4\&.4"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.0\&.4\fP
.PP

.PP
.SH "6\&.4\&.3"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
\fRuseRoutes\fP should be able to return \fRnull\fP when passing \fRlocationArg\fP (\fR#9485\fP)
.IP "\(bu" 2
fix \fRinitialEntries\fP type in \fRcreateMemoryRouter\fP (\fR#9498\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.0\&.3\fP
.PP

.PP
.SH "6\&.4\&.2"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Fix \fRIndexRouteObject\fP and \fRNonIndexRouteObject\fP types to make \fRhasErrorElement\fP optional (\fR#9394\fP)
.IP "\(bu" 2
Enhance console error messages for invalid usage of data router hooks (\fR#9311\fP)
.IP "\(bu" 2
If an index route has children, it will result in a runtime error\&. We have strengthened our \fRRouteObject\fP/\fRRouteProps\fP types to surface the error in TypeScript\&. (\fR#9366\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.0\&.2\fP
.PP

.PP
.SH "6\&.4\&.1"
.PP
.SS "Patch Changes"
.IP "\(bu" 2
Preserve state from \fRinitialEntries\fP (\fR#9288\fP)
.IP "\(bu" 2
Updated dependencies:
.IP "  \(bu" 4
\fR@remix-run/router@1\&.0\&.1\fP
.PP

.PP
.SH "6\&.4\&.0"
.PP
Whoa this is a big one! \fR6\&.4\&.0\fP brings all the data loading and mutation APIs over from Remix\&. Here's a quick high level overview, but it's recommended you go check out the \fRdocs\fP, especially the \fRfeature overview\fP and the \fRtutorial\fP\&.

.PP
\fBNew APIs\fP

.PP
.IP "\(bu" 2
Create your router with \fRcreateMemoryRouter\fP
.IP "\(bu" 2
Render your router with \fR<RouterProvider>\fP
.IP "\(bu" 2
Load data with a Route \fRloader\fP and mutate with a Route \fRaction\fP
.IP "\(bu" 2
Handle errors with Route \fRerrorElement\fP
.IP "\(bu" 2
Defer non-critical data with \fRdefer\fP and \fRAwait\fP
.PP

.PP
\fBBug Fixes\fP

.PP
.IP "\(bu" 2
Path resolution is now trailing slash agnostic (#8861)
.IP "\(bu" 2
\fRuseLocation\fP returns the scoped location inside a \fR<Routes location>\fP component (#9094)
.PP

.PP
\fBUpdated Dependencies\fP

.PP
.IP "\(bu" 2
\fR@remix-run/router@1\&.0\&.0\fP 
.PP

