.TH "md_frontend_2node__modules_2resolve_2readme" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2resolve_2readme \- resolve \*{\fR\fP\*}  
.PP


.PP
implements the \fRnode \fRrequire\&.resolve()\fP algorithm\fP such that you can \fRrequire\&.resolve()\fP on behalf of a file asynchronously and synchronously

.PP
\fR\fP \fR\fP \fR\fP \fR\fP [][license-url] \fR\fP

.PP
\fR\fP.SH "example"
.PP
asynchronously resolve:

.PP
.PP
.nf
var resolve = require('resolve/async'); // or, require('resolve')
resolve('tap', { basedir: __dirname }, function (err, res) {
    if (err) console\&.error(err);
    else console\&.log(res);
});
.fi
.PP

.PP
.PP
.nf
$ node example/async\&.js
/home/substack/projects/node\-resolve/node_modules/tap/lib/main\&.js
.fi
.PP

.PP
synchronously resolve:

.PP
.PP
.nf
var resolve = require('resolve/sync'); // or, `require('resolve')\&.sync
var res = resolve('tap', { basedir: __dirname });
console\&.log(res);
.fi
.PP

.PP
.PP
.nf
$ node example/sync\&.js
/home/substack/projects/node\-resolve/node_modules/tap/lib/main\&.js
.fi
.PP
.SH "methods"
.PP
.PP
.nf
var resolve = require('resolve');
var async = require('resolve/async');
var sync = require('resolve/sync');
.fi
.PP

.PP
For both the synchronous and asynchronous methods, errors may have any of the following \fRerr\&.code\fP values:

.PP
.IP "\(bu" 2
\fRMODULE_NOT_FOUND\fP: the given path string (\fRid\fP) could not be resolved to a module
.IP "\(bu" 2
\fRINVALID_BASEDIR\fP: the specified \fRopts\&.basedir\fP doesn't exist, or is not a directory
.IP "\(bu" 2
\fRINVALID_PACKAGE_MAIN\fP: a \fRpackage\&.json\fP was encountered with an invalid \fRmain\fP property (eg\&. not a string)
.PP
.SS "resolve(id, opts={}, cb)"
Asynchronously resolve the module path string \fRid\fP into \fRcb(err, res [, pkg])\fP, where \fRpkg\fP (if defined) is the data from \fRpackage\&.json\fP\&.

.PP
options are:

.PP
.IP "\(bu" 2
opts\&.basedir - directory to begin resolving from
.IP "\(bu" 2
opts\&.package - \fRpackage\&.json\fP data applicable to the module being loaded
.IP "\(bu" 2
opts\&.extensions - array of file extensions to search in order
.IP "\(bu" 2
opts\&.includeCoreModules - set to \fRfalse\fP to exclude node core modules (e\&.g\&. \fRfs\fP) from the search
.IP "\(bu" 2
opts\&.readFile - how to read files asynchronously
.IP "\(bu" 2
opts\&.isFile - function to asynchronously test whether a file exists
.IP "\(bu" 2
opts\&.isDirectory - function to asynchronously test whether a file exists and is a directory
.IP "\(bu" 2
opts\&.realpath - function to asynchronously resolve a potential symlink to its real path
.IP "\(bu" 2
\fRopts\&.readPackage(readFile, pkgfile, cb)\fP - function to asynchronously read and parse a package\&.json file
.IP "  \(bu" 4
readFile - the passed \fRopts\&.readFile\fP or \fRfs\&.readFile\fP if not specified
.IP "  \(bu" 4
pkgfile - path to package\&.json
.IP "  \(bu" 4
cb - callback
.PP

.IP "\(bu" 2
\fRopts\&.packageFilter(pkg, pkgfile, dir)\fP - transform the parsed package\&.json contents before looking at the "main" field
.IP "  \(bu" 4
pkg - package data
.IP "  \(bu" 4
pkgfile - path to package\&.json
.IP "  \(bu" 4
dir - directory that contains package\&.json
.PP

.IP "\(bu" 2
\fRopts\&.pathFilter(pkg, path, relativePath)\fP - transform a path within a package
.IP "  \(bu" 4
pkg - package data
.IP "  \(bu" 4
path - the path being resolved
.IP "  \(bu" 4
relativePath - the path relative from the package\&.json location
.IP "  \(bu" 4
returns - a relative path that will be joined from the package\&.json location
.PP

.IP "\(bu" 2
opts\&.paths - require\&.paths array to use if nothing is found on the normal \fRnode_modules\fP recursive walk (probably don't use this)

.PP
For advanced users, \fRpaths\fP can also be a \fRopts\&.paths(request, start, opts)\fP function
.IP "  \(bu" 4
request - the import specifier being resolved
.IP "  \(bu" 4
start - lookup path
.IP "  \(bu" 4
getNodeModulesDirs - a thunk (no-argument function) that returns the paths using standard \fRnode_modules\fP resolution
.IP "  \(bu" 4
opts - the resolution options
.PP

.IP "\(bu" 2
\fRopts\&.packageIterator(request, start, opts)\fP - return the list of candidate paths where the packages sources may be found (probably don't use this)
.IP "  \(bu" 4
request - the import specifier being resolved
.IP "  \(bu" 4
start - lookup path
.IP "  \(bu" 4
getPackageCandidates - a thunk (no-argument function) that returns the paths using standard \fRnode_modules\fP resolution
.IP "  \(bu" 4
opts - the resolution options
.PP

.IP "\(bu" 2
opts\&.moduleDirectory - directory (or directories) in which to recursively look for modules\&. default: \fR"node_modules"\fP
.IP "\(bu" 2
opts\&.preserveSymlinks - if true, doesn't resolve \fRbasedir\fP to real path before resolving\&. This is the way Node resolves dependencies when executed with the \fR--preserve-symlinks\fP flag\&. \fBNote:\fP this property is currently \fRtrue\fP by default but it will be changed to \fRfalse\fP in the next major version because \fINode's resolution algorithm does not preserve symlinks by default\fP\&.
.PP

.PP
default \fRopts\fP values:

.PP
.PP
.nf
{
    paths: [],
    basedir: __dirname,
    extensions: ['\&.js'],
    includeCoreModules: true,
    readFile: fs\&.readFile,
    isFile: function isFile(file, cb) {
        fs\&.stat(file, function (err, stat) {
            if (!err) {
                return cb(null, stat\&.isFile() || stat\&.isFIFO());
            }
            if (err\&.code === 'ENOENT' || err\&.code === 'ENOTDIR') return cb(null, false);
            return cb(err);
        });
    },
    isDirectory: function isDirectory(dir, cb) {
        fs\&.stat(dir, function (err, stat) {
            if (!err) {
                return cb(null, stat\&.isDirectory());
            }
            if (err\&.code === 'ENOENT' || err\&.code === 'ENOTDIR') return cb(null, false);
            return cb(err);
        });
    },
    realpath: function realpath(file, cb) {
        var realpath = typeof fs\&.realpath\&.native === 'function' ? fs\&.realpath\&.native : fs\&.realpath;
        realpath(file, function (realPathErr, realPath) {
            if (realPathErr && realPathErr\&.code !== 'ENOENT') cb(realPathErr);
            else cb(null, realPathErr ? file : realPath);
        });
    },
    readPackage: function defaultReadPackage(readFile, pkgfile, cb) {
        readFile(pkgfile, function (readFileErr, body) {
            if (readFileErr) cb(readFileErr);
            else {
                try {
                    var pkg = JSON\&.parse(body);
                    cb(null, pkg);
                } catch (jsonErr) {
                    cb(null);
                }
            }
        });
    },
    moduleDirectory: 'node_modules',
    preserveSymlinks: true
}
.fi
.PP
.SS "resolve\&.sync(id, opts)"
Synchronously resolve the module path string \fRid\fP, returning the result and throwing an error when \fRid\fP can't be resolved\&.

.PP
options are:

.PP
.IP "\(bu" 2
opts\&.basedir - directory to begin resolving from
.IP "\(bu" 2
opts\&.extensions - array of file extensions to search in order
.IP "\(bu" 2
opts\&.includeCoreModules - set to \fRfalse\fP to exclude node core modules (e\&.g\&. \fRfs\fP) from the search
.IP "\(bu" 2
opts\&.readFileSync - how to read files synchronously
.IP "\(bu" 2
opts\&.isFile - function to synchronously test whether a file exists
.IP "\(bu" 2
opts\&.isDirectory - function to synchronously test whether a file exists and is a directory
.IP "\(bu" 2
opts\&.realpathSync - function to synchronously resolve a potential symlink to its real path
.IP "\(bu" 2
\fRopts\&.readPackageSync(readFileSync, pkgfile)\fP - function to synchronously read and parse a package\&.json file
.IP "  \(bu" 4
readFileSync - the passed \fRopts\&.readFileSync\fP or \fRfs\&.readFileSync\fP if not specified
.IP "  \(bu" 4
pkgfile - path to package\&.json
.PP

.IP "\(bu" 2
\fRopts\&.packageFilter(pkg, dir)\fP - transform the parsed package\&.json contents before looking at the "main" field
.IP "  \(bu" 4
pkg - package data
.IP "  \(bu" 4
dir - directory that contains package\&.json (Note: the second argument will change to "pkgfile" in v2)
.PP

.IP "\(bu" 2
\fRopts\&.pathFilter(pkg, path, relativePath)\fP - transform a path within a package
.IP "  \(bu" 4
pkg - package data
.IP "  \(bu" 4
path - the path being resolved
.IP "  \(bu" 4
relativePath - the path relative from the package\&.json location
.IP "  \(bu" 4
returns - a relative path that will be joined from the package\&.json location
.PP

.IP "\(bu" 2
opts\&.paths - require\&.paths array to use if nothing is found on the normal \fRnode_modules\fP recursive walk (probably don't use this)

.PP
For advanced users, \fRpaths\fP can also be a \fRopts\&.paths(request, start, opts)\fP function
.IP "  \(bu" 4
request - the import specifier being resolved
.IP "  \(bu" 4
start - lookup path
.IP "  \(bu" 4
getNodeModulesDirs - a thunk (no-argument function) that returns the paths using standard \fRnode_modules\fP resolution
.IP "  \(bu" 4
opts - the resolution options
.PP

.IP "\(bu" 2
\fRopts\&.packageIterator(request, start, opts)\fP - return the list of candidate paths where the packages sources may be found (probably don't use this)
.IP "  \(bu" 4
request - the import specifier being resolved
.IP "  \(bu" 4
start - lookup path
.IP "  \(bu" 4
getPackageCandidates - a thunk (no-argument function) that returns the paths using standard \fRnode_modules\fP resolution
.IP "  \(bu" 4
opts - the resolution options
.PP

.IP "\(bu" 2
opts\&.moduleDirectory - directory (or directories) in which to recursively look for modules\&. default: \fR"node_modules"\fP
.IP "\(bu" 2
opts\&.preserveSymlinks - if true, doesn't resolve \fRbasedir\fP to real path before resolving\&. This is the way Node resolves dependencies when executed with the \fR--preserve-symlinks\fP flag\&. \fBNote:\fP this property is currently \fRtrue\fP by default but it will be changed to \fRfalse\fP in the next major version because \fINode's resolution algorithm does not preserve symlinks by default\fP\&.
.PP

.PP
default \fRopts\fP values:

.PP
.PP
.nf
{
    paths: [],
    basedir: __dirname,
    extensions: ['\&.js'],
    includeCoreModules: true,
    readFileSync: fs\&.readFileSync,
    isFile: function isFile(file) {
        try {
            var stat = fs\&.statSync(file);
        } catch (e) {
            if (e && (e\&.code === 'ENOENT' || e\&.code === 'ENOTDIR')) return false;
            throw e;
        }
        return stat\&.isFile() || stat\&.isFIFO();
    },
    isDirectory: function isDirectory(dir) {
        try {
            var stat = fs\&.statSync(dir);
        } catch (e) {
            if (e && (e\&.code === 'ENOENT' || e\&.code === 'ENOTDIR')) return false;
            throw e;
        }
        return stat\&.isDirectory();
    },
    realpathSync: function realpathSync(file) {
        try {
            var realpath = typeof fs\&.realpathSync\&.native === 'function' ? fs\&.realpathSync\&.native : fs\&.realpathSync;
            return realpath(file);
        } catch (realPathErr) {
            if (realPathErr\&.code !== 'ENOENT') {
                throw realPathErr;
            }
        }
        return file;
    },
    readPackageSync: function defaultReadPackageSync(readFileSync, pkgfile) {
        var body = readFileSync(pkgfile);
        try {
            var pkg = JSON\&.parse(body);
            return pkg;
        } catch (jsonErr) {}
    },
    moduleDirectory: 'node_modules',
    preserveSymlinks: true
}
.fi
.PP
.SH "install"
.PP
With \fRnpm\fP do:

.PP
.PP
.nf
npm install resolve
.fi
.PP
.SH "license"
.PP
MIT 
