.TH "md_frontend_2node__modules_2commander_2_c_h_a_n_g_e_l_o_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2commander_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP


.PP
All notable changes to this project will be documented in this file\&.

.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&. (Format adopted after v3\&.0\&.0\&.)
.SH "[4\&.1\&.1] (2020-02-02)"
.PP
.SS "Fixed"
.IP "\(bu" 2
TypeScript definition for \fR\&.action()\fP should include Promise for async (\fR#1157\fP)
.PP
.SH "[4\&.1\&.0] (2020-01-06)"
.PP
.SS "Added"
.IP "\(bu" 2
two routines to change how option values are handled, and eliminate name clashes with command properties ([#933] \fR#1102\fP)
.IP "  \(bu" 4
see storeOptionsAsProperties and passCommandToAction in README
.PP

.IP "\(bu" 2
\fR\&.parseAsync\fP to use instead of \fR\&.parse\fP if supply async action handlers ([#806] \fR#1118\fP)
.PP
.SS "Fixed"
.IP "\(bu" 2
Remove trailing blanks from wrapped help text (\fR#1096\fP)
.PP
.SS "Changed"
.IP "\(bu" 2
update dependencies
.IP "\(bu" 2
extend security coverage for Commander 2\&.x to 2020-02-03
.IP "\(bu" 2
improvements to README
.IP "\(bu" 2
improvements to TypeScript definition documentation
.IP "\(bu" 2
move old versions out of main CHANGELOG
.IP "\(bu" 2
removed explicit use of \fRts-node\fP in tests
.PP
.SH "[4\&.0\&.1] (2019-11-12)"
.PP
.SS "Fixed"
.IP "\(bu" 2
display help when requested, even if there are missing required options (\fR#1091\fP)
.PP
.SH "[4\&.0\&.0] (2019-11-02)"
.PP
.SS "Added"
.IP "\(bu" 2
automatically wrap and indent help descriptions for options and commands (\fR#1051\fP)
.IP "\(bu" 2
\fR\&.exitOverride()\fP allows override of calls to \fRprocess\&.exit\fP for additional error handling and to keep program running (\fR#1040\fP)
.IP "\(bu" 2
support for declaring required options with \fR\&.requiredOptions()\fP (\fR#1071\fP)
.IP "\(bu" 2
GitHub Actions support (\fR#1027\fP)
.IP "\(bu" 2
translation links in README
.PP
.SS "Changed"
.IP "\(bu" 2
dev: switch tests from Sinon+Should to Jest with major rewrite of tests (\fR#1035\fP)
.IP "\(bu" 2
call default subcommand even when there are unknown options (\fR#1047\fP)
.IP "\(bu" 2
\fIBreaking\fP Commander is only officially supported on Node 8 and above, and requires Node 6 (\fR#1053\fP)
.PP
.SS "Fixed"
.IP "\(bu" 2
\fIBreaking\fP keep command object out of program\&.args when action handler called (\fR#1048\fP)
.IP "  \(bu" 4
also, action handler now passed array of unknown arguments
.PP

.IP "\(bu" 2
complain about unknown options when program argument supplied and action handler (\fR#1049\fP)
.IP "  \(bu" 4
this changes parameters to \fRcommand:*\fP event to include unknown arguments
.PP

.IP "\(bu" 2
removed deprecated \fRcustomFds\fP option from call to \fRchild_process\&.spawn\fP (\fR#1052\fP)
.IP "\(bu" 2
rework TypeScript declarations to bring all types into imported namespace (\fR#1081\fP)
.PP
.SS "Migration Tips"
.SS "Testing for no arguments"
If you were previously using code like:

.PP
.PP
.nf
if (!program\&.args\&.length) \&.\&.\&.
.fi
.PP

.PP
a partial replacement is:

.PP
.PP
.nf
if (program\&.rawArgs\&.length < 3) \&.\&.\&.
.fi
.PP
.SH "\fR4\&.0\&.0-1\fP Prerelease (2019-10-08)"
.PP
(Released in 4\&.0\&.0)
.SH "\fR4\&.0\&.0-0\fP Prerelease (2019-10-01)"
.PP
(Released in 4\&.0\&.0)
.SH "[2\&.20\&.1] (2019-09-29)"
.PP
.SS "Fixed"
.IP "\(bu" 2
Improve tracking of executable subcommands\&.
.PP
.SS "Changed"
.IP "\(bu" 2
update development dependencies
.PP
.SH "[3\&.0\&.2] (2019-09-27)"
.PP
.SS "Fixed"
.IP "\(bu" 2
Improve tracking of executable subcommands\&.
.PP
.SS "Changed"
.IP "\(bu" 2
update development dependencies
.PP
.SH "[3\&.0\&.1] (2019-08-30)"
.PP
.SS "Added"
.IP "\(bu" 2
\&.name and \&.usage to README (\fR#1010\fP)
.IP "\(bu" 2
Table of Contents to README (\fR#1010\fP)
.IP "\(bu" 2
TypeScript definition for \fRexecutableFile\fP in CommandOptions (\fR#1028\fP)
.PP
.SS "Changed"
.IP "\(bu" 2
consistently use \fRconst\fP rather than \fRvar\fP in README (\fR#1026\fP)
.PP
.SS "Fixed"
.IP "\(bu" 2
help for sub commands with custom executableFile (\fR#1018\fP)
.PP
.SH "\fR3\&.0\&.0\fP / 2019-08-08"
.PP
.IP "\(bu" 2
Add option to specify executable file name (\fR#999\fP)
.IP "  \(bu" 4
e\&.g\&. \fR\&.command('clone', 'clone description', { executableFile: 'myClone' })\fP
.PP

.IP "\(bu" 2
Change docs for \fR\&.command\fP to contrast action handler vs git-style executable\&. ([#938] \fR#990\fP)
.IP "\(bu" 2
\fBBreaking\fP Change TypeScript to use overloaded function for \fR\&.command\fP\&. ([#938] \fR#990\fP)
.IP "\(bu" 2
Change to use straight quotes around strings in error messages (like 'this' instead of \fRthis') ([#915])\fP
.IP "\(bu" 2
\fRAdd TypeScript "reference types" for node ([#974])\fP
.IP "\(bu" 2
\fRAdd support for hyphen as an option argument in subcommands ([#697])\fP
.IP "\(bu" 2
\fRAdd support for a short option flag and its value to be concatenated for action handler subcommands ([#599])
.IP "  \(bu" 4
e\&.g\&. 
.PP
\fP-p 80\fR can also be supplied as \fP-p80\fR\fP
.IP "\(bu" 2
\fRAdd executable arguments to spawn in win32, for git-style executables ([#611])
.IP "  \(bu" 4
e\&.g\&. 
.PP
\fPnode --harmony myCommand\&.js clone\fR\fP
.IP "\(bu" 2
\fRAdd parent command as prefix of subcommand in help ([#980])\fP
.IP "\(bu" 2
\fRAdd optional custom description to \fP\&.version\fR ([#963])
.IP "  \(bu" 4
e\&.g\&. 
.PP
\fPprogram\&.version('0\&.0\&.1', '-v, --vers', 'output the current version')\fR\fP
.IP "\(bu" 2
\fRAdd \fP\&.helpOption(flags, description)\fR routine to customise help flags and description ([#963])
.IP "  \(bu" 4
e\&.g\&. 
.PP
\fP\&.helpOption('-e, --HELP', 'read more information')\fR\fP
.IP "\(bu" 2
\fRFix behavior of --no-* options ([#795])
.IP "  \(bu" 4
can now define both 
.PP
\fP--foo\fR and \fP--no-foo\fR
.IP "  \(bu" 4
**Breaking** custom event listeners: 
.PP
\fP--no-foo\fR on cli now emits \fPoption:no-foo\fR (previously \fPoption:foo\fR)
.IP "  \(bu" 4
**Breaking** default value: defining 
.PP
\fP--no-foo\fR after defining \fP--foo\fR leaves the default value unchanged (previously set it to false)
.IP "  \(bu" 4
allow boolean default value, such as from environment ([#987])
.PP
\fP
.IP "\(bu" 2
\fRIncrement inspector port for spawned subcommands ([#991])
.IP "  \(bu" 4
e\&.g\&. 
.PP
\fPnode --inspect myCommand\&.js clone`
.PP
.SS "Migration Tips"
The custom event for a negated option like \fR--no-foo\fP is \fRoption:no-foo\fP (previously \fRoption:foo\fP)\&.

.PP
.PP
.nf
program
  \&.option('\-\-no\-foo')
  \&.on('option:no\-foo', () => {
    console\&.log('removing foo');
  });
.fi
.PP

.PP
When using TypeScript, adding a command does not allow an explicit \fRundefined\fP for an unwanted executable description (e\&.g for a command with an action handler)\&.

.PP
.PP
.nf
program
  \&.command('action1', undefined, { noHelp: true }) // No longer valid
  \&.command('action2', { noHelp: true }) // Correct
.fi
.PP
.SH "3\&.0\&.0-0 Prerelease / 2019-07-28"
.PP
(Released as 3\&.0\&.0)
.SH "2\&.20\&.0 / 2019-04-02"
.PP
.IP "\(bu" 2
fix: resolve symbolic links completely when hunting for subcommands (#935)
.IP "\(bu" 2
Update index\&.d\&.ts (#930)
.IP "\(bu" 2
Update Readme\&.md (#924)
.IP "\(bu" 2
Remove --save option as it isn't required anymore (#918)
.IP "\(bu" 2
Add link to the license file (#900)
.IP "\(bu" 2
Added example of receiving args from options (#858)
.IP "\(bu" 2
Added missing semicolon (#882)
.IP "\(bu" 2
Add extension to \&.eslintrc (#876)
.PP
.SH "2\&.19\&.0 / 2018-10-02"
.PP
.IP "\(bu" 2
Removed newline after Options and Commands headers (#864)
.IP "\(bu" 2
Bugfix - Error output (#862)
.IP "\(bu" 2
Fix to change default value to string (#856)
.PP
.SH "2\&.18\&.0 / 2018-09-07"
.PP
.IP "\(bu" 2
Standardize help output (#853)
.IP "\(bu" 2
chmod 644 travis\&.yml (#851)
.IP "\(bu" 2
add support for execute typescript subcommand via ts-node (#849)
.PP
.SH "2\&.17\&.1 / 2018-08-07"
.PP
.IP "\(bu" 2
Fix bug in command emit (#844)
.PP
.SH "2\&.17\&.0 / 2018-08-03"
.PP
.IP "\(bu" 2
fixed newline output after help information (#833)
.IP "\(bu" 2
Fix to emit the action even without command (#778)
.IP "\(bu" 2
npm update (#823)
.PP
.SH "2\&.16\&.0 / 2018-06-29"
.PP
.IP "\(bu" 2
Remove Makefile and \fRtest/run\fP (#821)
.IP "\(bu" 2
Make 'npm test' run on Windows (#820)
.IP "\(bu" 2
Add badge to display install size (#807)
.IP "\(bu" 2
chore: cache node_modules (#814)
.IP "\(bu" 2
chore: remove Node\&.js 4 (EOL), add Node\&.js 10 (#813)
.IP "\(bu" 2
fixed typo in readme (#812)
.IP "\(bu" 2
Fix types (#804)
.IP "\(bu" 2
Update eslint to resolve vulnerabilities in lodash (#799)
.IP "\(bu" 2
updated readme with custom event listeners\&. (#791)
.IP "\(bu" 2
fix tests (#794)
.PP
.SH "2\&.15\&.0 / 2018-03-07"
.PP
.IP "\(bu" 2
Update downloads badge to point to graph of downloads over time instead of duplicating link to npm
.IP "\(bu" 2
Arguments description
.PP
.SH "2\&.14\&.1 / 2018-02-07"
.PP
.IP "\(bu" 2
Fix typing of help function
.PP
.SH "2\&.14\&.0 / 2018-02-05"
.PP
.IP "\(bu" 2
only register the option:version event once
.IP "\(bu" 2
Fixes issue #727: Passing empty string for option on command is set to undefined
.IP "\(bu" 2
enable eqeqeq rule
.IP "\(bu" 2
resolves #754 add linter configuration to project
.IP "\(bu" 2
resolves #560 respect custom name for version option
.IP "\(bu" 2
document how to override the version flag
.IP "\(bu" 2
document using options per command
.PP
.SH "2\&.13\&.0 / 2018-01-09"
.PP
.IP "\(bu" 2
Do not print default for --no-
.IP "\(bu" 2
remove trailing spaces in command help
.IP "\(bu" 2
Update CI's Node\&.js to LTS and latest version
.IP "\(bu" 2
typedefs: Command and Option types added to commander namespace
.PP
.SH "2\&.12\&.2 / 2017-11-28"
.PP
.IP "\(bu" 2
fix: typings are not shipped
.PP
.SH "2\&.12\&.1 / 2017-11-23"
.PP
.IP "\(bu" 2
Move @types/node to dev dependency
.PP
.SH "2\&.12\&.0 / 2017-11-22"
.PP
.IP "\(bu" 2
add attributeName() method to Option objects
.IP "\(bu" 2
Documentation updated for options with --no prefix
.IP "\(bu" 2
typings: \fRoutputHelp\fP takes a string as the first parameter
.IP "\(bu" 2
typings: use overloads
.IP "\(bu" 2
feat(typings): update to match js api
.IP "\(bu" 2
Print default value in option help
.IP "\(bu" 2
Fix translation error
.IP "\(bu" 2
Fail when using same command and alias (#491)
.IP "\(bu" 2
feat(typings): add help callback
.IP "\(bu" 2
fix bug when description is add after command with options (#662)
.IP "\(bu" 2
Format js code
.IP "\(bu" 2
Rename History\&.md to CHANGELOG\&.md (#668)
.IP "\(bu" 2
feat(typings): add typings to support TypeScript (#646)
.IP "\(bu" 2
use current node
.PP
.SH "2\&.11\&.0 / 2017-07-03"
.PP
.IP "\(bu" 2
Fix help section order and padding (#652)
.IP "\(bu" 2
feature: support for signals to subcommands (#632)
.IP "\(bu" 2
Fixed #37, --help should not display first (#447)
.IP "\(bu" 2
Fix translation errors\&. (#570)
.IP "\(bu" 2
Add package-lock\&.json
.IP "\(bu" 2
Remove engines
.IP "\(bu" 2
Upgrade package version
.IP "\(bu" 2
Prefix events to prevent conflicts between commands and options (#494)
.IP "\(bu" 2
Removing dependency on graceful-readlink
.IP "\(bu" 2
Support setting name in #name function and make it chainable
.IP "\(bu" 2
Add \&.vscode directory to \&.gitignore (Visual Studio Code metadata)
.IP "\(bu" 2
Updated link to ruby commander in readme files
.PP
.SH "2\&.10\&.0 / 2017-06-19"
.PP
.IP "\(bu" 2
Update \&.travis\&.yml\&. drop support for older node\&.js versions\&.
.IP "\(bu" 2
Fix require arguments in README\&.md
.IP "\(bu" 2
On SemVer you do not start from 0\&.0\&.1
.IP "\(bu" 2
Add missing semi colon in readme
.IP "\(bu" 2
Add save param to npm install
.IP "\(bu" 2
node v6 travis test
.IP "\(bu" 2
Update Readme_zh-CN\&.md
.IP "\(bu" 2
Allow literal '--' to be passed-through as an argument
.IP "\(bu" 2
Test subcommand alias help
.IP "\(bu" 2
link build badge to master branch
.IP "\(bu" 2
Support the alias of Git style sub-command
.IP "\(bu" 2
added keyword commander for better search result on npm
.IP "\(bu" 2
Fix Sub-Subcommands
.IP "\(bu" 2
test node\&.js stable
.IP "\(bu" 2
Fixes TypeError when a command has an option called \fR--description\fP
.IP "\(bu" 2
Update README\&.md to make it beginner friendly and elaborate on the difference between angled and square brackets\&.
.IP "\(bu" 2
Add chinese Readme file
.PP
.SH "2\&.9\&.0 / 2015-10-13"
.PP
.IP "\(bu" 2
Add option \fRisDefault\fP to set default subcommand #415 @Qix-
.IP "\(bu" 2
Add callback to allow filtering or post-processing of help text #434 @djulien
.IP "\(bu" 2
Fix \fRundefined\fP text in help information close #414 #416 @zhiyelee
.PP
.SH "2\&.8\&.1 / 2015-04-22"
.PP
.IP "\(bu" 2
Back out \fRsupport multiline description\fP Close #396 #397
.PP
.SH "2\&.8\&.0 / 2015-04-07"
.PP
.IP "\(bu" 2
Add \fRprocess\&.execArg\fP support, execution args like \fR--harmony\fP will be passed to sub-commands #387 @DigitalIO @zhiyelee
.IP "\(bu" 2
Fix bug in Git-style sub-commands #372 @zhiyelee
.IP "\(bu" 2
Allow commands to be hidden from help #383 @tonylukasavage
.IP "\(bu" 2
When git-style sub-commands are in use, yet none are called, display help #382 @claylo
.IP "\(bu" 2
Add ability to specify arguments syntax for top-level command #258 @rrthomas
.IP "\(bu" 2
Support multiline descriptions #208 @zxqfox
.PP
.SH "2\&.7\&.1 / 2015-03-11"
.PP
.IP "\(bu" 2
Revert #347 (fix collisions when option and first arg have same name) which causes a bug in #367\&.
.PP
.SH "2\&.7\&.0 / 2015-03-09"
.PP
.IP "\(bu" 2
Fix git-style bug when installed globally\&. Close #335 #349 @zhiyelee
.IP "\(bu" 2
Fix collisions when option and first arg have same name\&. Close #346 #347 @tonylukasavage
.IP "\(bu" 2
Add support for camelCase on \fRopts()\fP\&. Close #353 @nkzawa
.IP "\(bu" 2
Add node\&.js 0\&.12 and io\&.js to travis\&.yml
.IP "\(bu" 2
Allow RegEx options\&. #337 @palanik
.IP "\(bu" 2
Fixes exit code when sub-command failing\&. Close #260 #332 @pirelenito
.IP "\(bu" 2
git-style \fRbin\fP files in $PATH make sense\&. Close #196 #327 @zhiyelee
.PP
.SH "2\&.6\&.0 / 2014-12-30"
.PP
.IP "\(bu" 2
added \fRCommand#allowUnknownOption\fP method\&. Close #138 #318 @doozr @zhiyelee
.IP "\(bu" 2
Add application description to the help msg\&. Close #112 @dalssoft
.PP
.SH "2\&.5\&.1 / 2014-12-15"
.PP
.IP "\(bu" 2
fixed two bugs incurred by variadic arguments\&. Close #291 @Quentin01 #302 @zhiyelee
.PP
.SH "2\&.5\&.0 / 2014-10-24"
.PP
.IP "\(bu" 2
add support for variadic arguments\&. Closes #277 @whitlockjc
.PP
.SH "2\&.4\&.0 / 2014-10-17"
.PP
.IP "\(bu" 2
fixed a bug on executing the coercion function of subcommands option\&. Closes #270
.IP "\(bu" 2
added \fRCommand\&.prototype\&.name\fP to retrieve command name\&. Closes #264 #266 @tonylukasavage
.IP "\(bu" 2
added \fRCommand\&.prototype\&.opts\fP to retrieve all the options as a simple object of key-value pairs\&. Closes #262 @tonylukasavage
.IP "\(bu" 2
fixed a bug on subcommand name\&. Closes #248 @jonathandelgado
.IP "\(bu" 2
fixed function normalize doesn’t honor option terminator\&. Closes #216 @abbr
.PP
.SH "2\&.3\&.0 / 2014-07-16"
.PP
.IP "\(bu" 2
add command alias'\&. Closes PR #210
.IP "\(bu" 2
fix: Typos\&. Closes #99
.IP "\(bu" 2
fix: Unused fs module\&. Closes #217
.PP
.SH "2\&.2\&.0 / 2014-03-29"
.PP
.IP "\(bu" 2
add passing of previous option value
.IP "\(bu" 2
fix: support subcommands on windows\&. Closes #142
.IP "\(bu" 2
Now the defaultValue passed as the second argument of the coercion function\&.
.PP
.SH "2\&.1\&.0 / 2013-11-21"
.PP
.IP "\(bu" 2
add: allow cflag style option params, unit test, fixes #174
.PP
.SH "2\&.0\&.0 / 2013-07-18"
.PP
.IP "\(bu" 2
remove input methods (\&.prompt, \&.confirm, etc)
.PP
.SH "Older versions"
.PP
.IP "\(bu" 2
\fB1\&.x\fP
.IP "\(bu" 2
\fB0\&.x\fP 
.PP

