.TH "md_frontend_2node__modules_2date-fns_2docs_2getting_started" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2date-fns_2docs_2getting_started \- Getting Started 
.PP

.SH "Table of Contents"
.PP
.IP "\(bu" 2
\fBIntroduction\fP
.IP "\(bu" 2
\fBSubmodules\fP
.IP "\(bu" 2
\fBInstallation\fP
.PP
.SH "Introduction"
.PP
\fBdate-fns\fP provides the most comprehensive, yet simple and consistent toolset for manipulating \fBJavaScript dates\fP in \fBa browser\fP & \fBNode\&.js\fP\&.

.PP
\fBdate-fns\fP is like \fRlodash\fP for dates\&. It has \fR\fB200+ functions\fP for all occasions\fP\&.

.PP
.PP
.nf
import { format, compareAsc } from "date\-fns";

format(new Date(2014, 1, 11), "MM/dd/yyyy");
//=> '02/11/2014'

const dates = [
  new Date(1995, 6, 2),
  new Date(1987, 1, 11),
  new Date(1989, 6, 10),
];
dates\&.sort(compareAsc);
//=> [
//   Wed Feb 11 1987 00:00:00,
//   Mon Jul 10 1989 00:00:00,
//   Sun Jul 02 1995 00:00:00
// ]
.fi
.PP
.SH "Submodules"
.PP
\fBdate-fns\fP includes some optional features as submodules in the npm package\&. Here is the list of them, in order of nesting:

.PP
.IP "\(bu" 2
FP — functional programming-friendly variations of the functions\&. See \fRFP Guide\fP;
.PP

.PP
The later submodules are also included inside the former if you want to use multiple features from the list\&.

.PP
To use submodule features, \fBinstall the npm package\fP and then import a function from a submodule:

.PP
.PP
.nf
// The main submodule:
import { addDays } from "date\-fns";

// FP variation:
import { addDays, format } from "date\-fns/fp";
.fi
.PP
.SH "Installation"
.PP
The library is available as an \fRnpm package\fP\&.

.PP
To install the package, run:

.PP
.PP
.nf
npm install date\-fns \-\-save
# or
yarn add date\-fns
.fi
.PP

.PP
Start using:

.PP
.PP
.nf
import { formatDistance, subDays } from "date\-fns";

formatDistance(subDays(new Date(), 3), new Date(), { addSuffix: true });
//=> "3 days ago"
.fi
.PP
 
