.TH "md_frontend_2node__modules_2recharts_2_c_o_n_t_r_i_b_u_t_i_n_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2recharts_2_c_o_n_t_r_i_b_u_t_i_n_g \- Contributing to Recharts 
.PP


.PP
We'd love for you to contribute to our source code and to make Recharts even better than it is today! Here are the guidelines we'd like you to follow:

.PP
.IP "\(bu" 2
\fBIssues and Bugs\fP
.IP "\(bu" 2
\fBTesting\fP
.IP "\(bu" 2
\fBPull Requests\fP
.IP "\(bu" 2
\fBCode Guide\fP
.IP "\(bu" 2
\fBLicense\fP
.PP
.SH "Ongoing Initiatives"
.PP
We use Github Discussion to organize our discussion along new initiatives and organize ourselves\&. Please do check the \fRannouncements\fP section for an overview of recent initiatives\&.
.SH "Issues and Bugs"
.PP
.SS "Where to Find Known Issues"
We will be using \fRGitHub Issues\fP for our bugs and feature requests\&. We will keep a close eye on this and try to make it clear when we have an internal fix in progress\&. Before filing a new task, try to make sure your problem doesn't already exist\&.
.SS "Reporting New Issues"
The best way to get your bug fixed is to provide a reduced test case\&. codesandbox provide a way to give live examples\&. You can fork our example in \fRrecharts\&.org\fP to show your case\&.
.SH "Testing"
.PP
We do cherish tests\&. They help us move swiftly, and release with confidence\&. In our repo, you will find three types of tests: Unit tests, rendering tests with RTL, and user interaction tests in storybook\&. Wherever possible we prefer the simplest tests - unit tests\&. Only where needed / useful we would use RTL or storybook tests\&.
.SS "Unit tests"
When implementing a new feature we would prefer to extract pure helper function for data processing\&. Such functions are found a few utils files\&. An example is \fRtest/util/ShallowEqual\&.spec\&.ts\fP
.SS "React Testing Library"
Some behaviour must be tested upon rendering, such as interactions between components (Line, Tooltip), see \fRtest/component/Tooltip\&.spec\&.tsx\fP for an example\&.
.SS "Storybook Test Runner"
Storybook also has a great interface for adding tests\&. By default every story in storybook is a smoke test (rendering without error logs means the test passed)\&. Additionally, it is possible to add actual tests as play functions with an assert to a story\&. This will often be easier than using React Testing Library, because the natural test debugging tool is Storybook itself\&. See for example \fRstorybook/stories/Examples/cartesian/ReferenceLine/ReferenceLineIfOverflow\&.stories\&.tsx\fP
.SS "Performance tests"
Recharts uses (https://callstack.github.io/reassure/)[Reassure] to run performance tests\&. Here is how to use:

.PP
.IP "1." 4
Before making code changes, run \fRnpm run test:perf:baseline\fP\&. This will generate baseline data\&. You only do this once for each change\&.
.IP "2." 4
Make your code changes now
.IP "3." 4
Run \fRnpm test:perf\fP\&. Reassure will run tests again, compare with the baseline from step 1\&. and print results to the console\&. If you wish you can also review the results in a markdown file in path \fR\&./reassure/output\&.md\fP\&.
.IP "4." 4
If you are satisfied with the performance impact then go ahead and commit! If you wish to make more changes go back to step 2\&.
.PP

.PP
Reassure will look for \fR*\&.perf-test\&.tsx\fP files by default\&.

.PP
Also be aware that the performance tests might take a long time to run; up to several minutes\&.
.SH "Pull Requests"
.PP
\fBWorking on your first Pull Request?\fP You can learn how from this \fIfree\fP series \fRHow to Contribute to an Open Source Project on GitHub\fP

.PP
\fIBefore\fP submitting a pull request, please make sure the following is done…

.PP
.IP "\(bu" 2
Search \fRGitHub\fP for an open or closed Pull Request that relates to your submission\&. You don't want to duplicate effort\&.
.IP "\(bu" 2
Fork the repo and create your branch from \fRmaster\fP\&.
.IP "\(bu" 2
If you have added functionality or changed existing functionality, be sure to add a test\&. Ideally a unit test for helper function, or a test that includes rendering with RTL\&.
.IP "\(bu" 2
If you've changed APIs, make sure that the stories in Storybook are working as expected\&.
.IP "\(bu" 2
Ensure the test suite passes (\fRnpm run test\fP)\&.
.IP "\(bu" 2
Make sure your code lints (\fRnpm run lint\fP) - we've done our best to make sure these rules match our internal linting guidelines\&.
.PP
.SH "Code Guide"
.PP
Our linter will catch most styling issues that may exist in your code\&. You can check the status of your code styling by running: \fRnpm run lint\fP

.PP
However, there are still some styles that the linter cannot pick up\&. If you are unsure about something, looking at \fRAirbnb's Style Guide\fP will guide you in the right direction\&.
.SH "License"
.PP
By contributing to Recharts, you agree that your contributions will be licensed under its MIT license\&. 
