.TH "md_frontend_2node__modules_2react-smooth_2_c_h_a_n_g_e_l_o_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2react-smooth_2_c_h_a_n_g_e_l_o_g \- 3\&.0\&.0 / 2023-10-18 
.PP

.SS "refactor / chore"
.IP "\(bu" 2
upgrade dependencies
.PP
.SH "BREAKING CHANGE"
.PP
Remove some unused/unneeded code which drops support for older browser versions\&. Results in slightly decreased bundle size\&.

.PP
.IP "\(bu" 2
remove unneeded polyfill for translateStyle - \fRbrowser support since 2017\fP
.IP "\(bu" 2
remove unneeded polyfill for \fRNumber\&.isFinite\fP - \fRbrowser support since 2015\fP AND polyfilled by babel/core-js
.PP
.SS "2\&.0\&.5 / 2023-10-10"
.SS "fix"
.IP "\(bu" 2
Check if \fRrequestAnimationFrame\fP is defined in shouldUpdate
.PP
.SS "2\&.0\&.4 / 2023-09-12"
.SS "fix"
.IP "\(bu" 2
call \fRonAnimationEnd\fP on unmount
.PP
.SS "2\&.0\&.3 / 2023-05-08"
.SS "fix"
.IP "\(bu" 2
treat \fRduration={0}\fP as if animation is not active by doing a check and returning early\&. This fixes a bug where NaN can cause a crash in the browser\&.
.PP
.SS "2\&.0\&.2 / 2023-02-23"
.SS "chore"
.IP "\(bu" 2
upgrade \fRfast-equals\fP to latest\&. No breaking changes - see https://github.com/planttheidea/fast-equals/blob/master/CHANGELOG.md
.IP "\(bu" 2
don't upgrade \fRreact-transition-group\fP in minor release as this requires dropping support for react <16\&.6
.IP "\(bu" 2
upgrade devDependencies
.IP "\(bu" 2
update babel config
.IP "\(bu" 2
update deprecated eslint parser
.PP
.SS "2\&.0\&.1 / 2022-06-27"
.SS "feat"
.IP "\(bu" 2
feat: allow React 18
.IP "\(bu" 2
Remove raf polyfill for IE9
.PP
.SS "2\&.0\&.0 / 2021-03-21"
.SS "chore (#48)"
.IP "\(bu" 2
Changed peerDeps to react 15,16,17
.IP "\(bu" 2
Removed karma,chai,enzyme blablabla\&.\&.\&. and used only Jest and Testing-Library\&.
.IP "\(bu" 2
Updated devDependencies and cleared some\&.
.PP
.SS "1\&.0\&.2 / 2018-10-02"
.SS "fix"
.IP "\(bu" 2
fix babelrc
.PP
.SS "1\&.0\&.1 / 2018-10-02"
.SS "fix"
.IP "\(bu" 2
update babel, webpack, karma, etc\&.
.IP "\(bu" 2
fix import error
.PP
.SS "1\&.0\&.0 / 2017-11-06"
.SS "feat"
.IP "\(bu" 2
Support React 16
.PP
.SS "0\&.1\&.17 / 2016-12-02"
.SS "fix"
.IP "\(bu" 2
change scripts
.PP
.SS "0\&.1\&.16 / 2016-11-25"
.SS "fix"
.IP "\(bu" 2
update lodash
.PP
.SS "0\&.1\&.15 / 2016-10-31"
.SS "fix"
.IP "\(bu" 2
fix isMounted to mounted
.PP
.SS "0\&.1\&.14 / 2016-10-28"
.SS "fix"
.IP "\(bu" 2
fix: judge isMounted
.PP
.SS "0\&.1\&.12-0\&.1\&.13 / 2016-10-27"
.SS "fix"
.IP "\(bu" 2
fix script
.PP
.SS "0\&.1\&.10 / 2016-07-07"
.SS "fix"
.IP "\(bu" 2
add onAnimationReStart validation
.PP
.SS "0\&.1\&.8-0\&.1\&.9 / 2016-05-05"
.SS "feat"
.IP "\(bu" 2
add onAniamtionStart prop
.PP
.SS "0\&.1\&.7 / 2016-04-21"
.SS "fix"
.IP "\(bu" 2
fix Animate trigger animate when isActive is false
.PP
.SS "0\&.1\&.6 / 2016-04-15"
.SS "fix"
.IP "\(bu" 2
fix Animate not pipe props when Animate not active
.PP
.SS "0\&.1\&.5 / 2016-04-13"
.SS "fix"
.IP "\(bu" 2
remove pure-render-decorator
.PP
.SS "0\&.1\&.4 / 2016-04-12"
.SS "fix"
.IP "\(bu" 2
change transition-group addons to dependencies
.PP
.SS "0\&.1\&.3 / 2016-04-12"
.SS "refactor"
.IP "\(bu" 2
refactor AnimateManager
.PP
.SS "0\&.1\&.2 / 2016-04-12"
.SS "feat"
.IP "\(bu" 2
use owe PureRender util
.PP
.SS "fix"
.IP "\(bu" 2
update react to 15\&.0\&.0
.PP
.SS "0\&.1\&.1 / 2016-04-05"
.SS "feat"
.IP "\(bu" 2
add shouldReAnimate prop
.PP
.SS "0\&.1\&.0 / 2016-03-16"
.SS "feat"
.IP "\(bu" 2
use webpack 2
.PP
.SS "0\&.0\&.13-0\&.0\&.15 / 2016-03-15"
.SS "fix"
.IP "\(bu" 2
using isEqual in lodash and remove isEqual in utils
.PP
.SS "0\&.0\&.13-0\&.0\&.14 / 2016-03-15"
.SS "fix"
.IP "\(bu" 2
fix update animation judgement
.PP
.SS "0\&.0\&.12 / 2016-03-15"
.SS "fix"
.IP "\(bu" 2
fix compatable prefix in transition property
.PP
.SS "refactor"
.IP "\(bu" 2
refactor some function in utils
.IP "\(bu" 2
using JSX instead of createElement
.PP
.SS "0\&.0\&.11 / 2016-03-01"
.SS "fix"
.IP "\(bu" 2
fix haven't unsubscribe handleStyleChange
.PP
.SS "0\&.0\&.10 / 2016-02-17"
.SS "refactor"
.IP "\(bu" 2
remove lodash compose method
.IP "\(bu" 2
refactor configUpdate\&.js
.PP
.SS "0\&.0\&.9 / 2016-02-05"
.SS "fix"
.IP "\(bu" 2
fix don't build on npm publish
.PP
.SS "0\&.0\&.8 / 2016-02-05"
.SS "fix"
.IP "\(bu" 2
fix lodash minify problem
.PP
.SS "0\&.0\&.7 / 2016-02-04"
.SS "fix"
.IP "\(bu" 2
optimize npm script commands
.PP
.SS "0\&.0\&.6 / 2016-02-04"
.SS "fix"
.IP "\(bu" 2
set min time longer
.PP
.SS "0\&.0\&.5 / 2016-02-04"
.SS "fix"
.IP "\(bu" 2
fix animation not valid for set css styles too quick\&.
.PP
.SS "0\&.0\&.4 / 2016-02-02"
.SS "fix"
.IP "\(bu" 2
support onAnimationEnd in js animation
.PP
.SS "0\&.0\&.3 / 2016-02-02"
.SS "refactor"
.IP "\(bu" 2
refactor the import path of lodash function
.IP "\(bu" 2
update webpack\&.config\&.js
.PP
.SS "0\&.0\&.2 / 2016-02-02"
.SS "feat"
.IP "\(bu" 2
support js animation
.IP "\(bu" 2
support bezier and spring timing function
.IP "\(bu" 2
support group animation
.PP
.SS "0\&.0\&.1 / 2016-01-21"
.IP "\(bu" 2
Init the project 
.PP

