.TH "md_frontend_2node__modules_2mz_2_h_i_s_t_o_r_y" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2mz_2_h_i_s_t_o_r_y \- 2\&.7\&.0 / 2017-09-13 
.PP

.IP "\(bu" 2
feat: support fs\&.copyFile (#58)
.PP
.SH "2\&.6\&.0 / 2016-11-22"
.PP
.IP "\(bu" 2
Added fdatasync to fs api (#46)
.PP
.SH "2\&.5\&.0 / 2016-11-04"
.PP
.IP "\(bu" 2
feat: support fs\&.mkdtemp
.PP
.SH "2\&.4\&.0 / 2016-03-23"
.PP
.IP "\(bu" 2
add \fRfs\&.truncate()\fP \fR#34\fP
.PP
.SH "2\&.3\&.1 / 2016-02-01"
.PP
.IP "\(bu" 2
update \fRany-promise@v1\fP
.PP
.SH "2\&.3\&.0 / 2016-01-30"
.PP
.IP "\(bu" 2
feat(package): switch to \fRany-promise\fP to support more promise engines
.PP
.SH "2\&.2\&.0 / 2016-01-24"
.PP
.IP "\(bu" 2
feat(package): add index\&.js to files
.PP
.SH "2\&.1\&.0 / 2015-10-15"
.PP
.IP "\(bu" 2
support for readline library
.PP
.SH "2\&.0\&.0 / 2015-05-24"
.PP
.IP "\(bu" 2
support callbacks as well
.PP
.SH "1\&.2\&.0 / 2014-12-16"
.PP
.IP "\(bu" 2
refactor promisification to \fRthenify\fP and \fRthenify-all\fP
.PP
.SH "1\&.1\&.0 / 2014-11-14"
.PP
.IP "\(bu" 2
use \fRgraceful-fs\fP if available
.PP
.SH "1\&.0\&.1 / 2014-08-18"
.PP
.IP "\(bu" 2
don't use \fRbluebird\&.promisify()\fP - unnecessarily wraps runtime errors, causing issues
.PP
.SH "1\&.0\&.0 / 2014-06-18"
.PP
.IP "\(bu" 2
use \fRbluebird\fP by default if found
.IP "\(bu" 2
support node 0\&.8 
.PP

