.TH "md_frontend_2node__modules_2is-core-module_2_c_h_a_n_g_e_l_o_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2is-core-module_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP


.PP
All notable changes to this project will be documented in this file\&.

.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "\fRv2\&.16\&.1\fP - 2024-12-21"
.PP
.SS "Fixed"
.IP "\(bu" 2
[Fix] \fRnode:sqlite\fP is available in node ^22\&.13 \fR\fR#17\fP\fP
.PP
.SH "\fRv2\&.16\&.0\fP - 2024-12-13"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRnode:sqlite\fP \fR\fR1ee94d2\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRauto-changelog\fP, \fRtape\fP \fR\fRaa84aa3\fP\fP
.PP
.SH "\fRv2\&.15\&.1\fP - 2024-08-21"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] add \fRprocess\&.getBuiltinModule\fP tests \fR\fR28c7791\fP\fP
.IP "\(bu" 2
[Fix] \fRtest/mock_loader\fP is no longer exposed as of v22\&.7 \fR\fR68b08b0\fP\fP
.IP "\(bu" 2
[Tests] replace \fRaud\fP with \fRnpm audit\fP \fR\fR32f8060\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRmock-property\fP \fR\fRf7d3c8f\fP\fP
.IP "\(bu" 2
[Dev Deps] add missing peer dep \fR\fReaee885\fP\fP
.PP
.SH "\fRv2\&.15\&.0\fP - 2024-07-17"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRnode:sea\fP \fR\fR2819fb3\fP\fP
.PP
.SH "\fRv2\&.14\&.0\fP - 2024-06-20"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRmock-property\fP, \fRnpmignore\fP, \fRtape\fP \fR\fR0e43200\fP\fP
.IP "\(bu" 2
[meta] add missing \fRengines\&.node\fP \fR\fR4ea3af8\fP\fP
.IP "\(bu" 2
[New] add \fRtest/mock_loader\fP \fR\fRe9fbd29\fP\fP
.IP "\(bu" 2
[Deps] update \fRhasown\fP \fR\fR57f1940\fP\fP
.PP
.SH "\fRv2\&.13\&.1\fP - 2023-10-20"
.PP
.SS "Commits"
.IP "\(bu" 2
[Refactor] use \fRhasown\fP instead of \fRhas\fP \fR\fR0e52096\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRmock-property\fP, \fRtape\fP \fR\fR8736b35\fP\fP
.PP
.SH "\fRv2\&.13\&.0\fP - 2023-08-05"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRsemver\fP, \fRtape\fP \fR\fRc75b263\fP\fP
.IP "\(bu" 2
[New] \fRnode:test/reporters\fP and \fRwasi\fP/\fRnode:wasi\fP are in v18\&.17 \fR\fRd76cbf8\fP\fP
.PP
.SH "\fRv2\&.12\&.1\fP - 2023-05-16"
.PP
.SS "Commits"
.IP "\(bu" 2
[Fix] \fRtest/reporters\fP now requires the \fRnode:\fP prefix as of v20\&.2 \fR\fR12183d0\fP\fP
.PP
.SH "\fRv2\&.12\&.0\fP - 2023-04-10"
.PP
.SS "Commits"
.IP "\(bu" 2
[actions] update rebase action to use reusable workflow \fR\fRc0a7251\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fR9ae8b7f\fP\fP
.IP "\(bu" 2
[New] \fRtest/reporters\fP added in v19\&.9, \fRwasi\fP added in v20 \fR\fR9d5341a\fP\fP
.IP "\(bu" 2
[Dev Deps] add missing \fRin-publish\fP dep \fR\fR5980245\fP\fP
.PP
.SH "\fRv2\&.11\&.0\fP - 2022-10-18"
.PP
.SS "Commits"
.IP "\(bu" 2
[meta] use \fRnpmignore\fP to autogenerate an npmignore file \fR\fR3360011\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fRaud\fP, \fRtape\fP \fR\fR651c6b0\fP\fP
.IP "\(bu" 2
[New] \fRinspector/promises\fP and \fRnode:inspector/promises\fP is now available in node 19 \fR\fR22d332f\fP\fP
.PP
.SH "\fRv2\&.10\&.0\fP - 2022-08-03"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] \fRnode:test\fP is now available in node ^16\&.17 \fR\fRe8fd36e\fP\fP
.IP "\(bu" 2
[Tests] improve skip message \fR\fRc014a4c\fP\fP
.PP
.SH "\fRv2\&.9\&.0\fP - 2022-04-19"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] add \fRnode:test\fP, in node 18+ \fR\fRf853eca\fP\fP
.IP "\(bu" 2
[Tests] use \fRmock-property\fP \fR\fR03b3644\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRauto-changelog\fP, \fRtape\fP \fR\fR7c0e2d0\fP\fP
.IP "\(bu" 2
[meta] simplify "exports" \fR\fRd6ed201\fP\fP
.PP
.SH "\fRv2\&.8\&.1\fP - 2022-01-05"
.PP
.SS "Commits"
.IP "\(bu" 2
[actions] reuse common workflows \fR\fRcd2cf9b\fP\fP
.IP "\(bu" 2
[Fix] update node 0\&.4 results \fR\fR062195d\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRsafe-publish-latest\fP, \fRtape\fP \fR\fR0790b62\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRtape\fP \fR\fR7d139a6\fP\fP
.IP "\(bu" 2
[Tests] run \fRnyc\fP in \fRtests-only\fP, not \fRtest\fP \fR\fR780e8a0\fP\fP
.PP
.SH "\fRv2\&.8\&.0\fP - 2021-10-14"
.PP
.SS "Commits"
.IP "\(bu" 2
[actions] update codecov uploader \fR\fR0cfe94e\fP\fP
.IP "\(bu" 2
[New] add \fRreadline/promises\fP to node v17+ \fR\fR4f78c30\fP\fP
.IP "\(bu" 2
[Tests] node ^14\&.18 supports \fRnode:\fP prefixes for CJS \fR\fR43e2f17\fP\fP
.PP
.SH "\fRv2\&.7\&.0\fP - 2021-09-27"
.PP
.SS "Commits"
.IP "\(bu" 2
[New] node \fRv14\&.18\fP added \fRnode:\fP-prefixed core modules to \fRrequire\fP \fR\fR6d943ab\fP\fP
.IP "\(bu" 2
[Tests] add coverage for Object\&.prototype pollution \fR\fRc6baf5f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP \fR\fR6717f00\fP\fP
.IP "\(bu" 2
[eslint] fix linter warning \fR\fR594c10b\fP\fP
.IP "\(bu" 2
[meta] add \fRsideEffects\fP flag \fR\fRc32cfa5\fP\fP
.PP
.SH "\fRv2\&.6\&.0\fP - 2021-08-17"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fRtape\fP \fR\fR6cc928f\fP\fP
.IP "\(bu" 2
[New] add \fRstream/consumers\fP to node \fR&gt;= 16\&.7\fP \fR\fRa1a423e\fP\fP
.IP "\(bu" 2
[Refactor] Remove duplicated \fR&&\fP operand \fR\fR86faea7\fP\fP
.IP "\(bu" 2
[Tests] include prereleases \fR\fRa4da7a6\fP\fP
.PP
.SH "\fRv2\&.5\&.0\fP - 2021-07-12"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fRauto-changelog\fP, \fReslint\fP \fR\fR6334cc9\fP\fP
.IP "\(bu" 2
[New] add \fRstream/web\fP to node v16\&.5+ \fR\fR17ac59b\fP\fP
.PP
.SH "\fRv2\&.4\&.0\fP - 2021-05-09"
.PP
.SS "Commits"
.IP "\(bu" 2
[readme] add actions and codecov badges \fR\fR82b7faa\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fR@ljharb/eslint-config\fP, \fRaud\fP \fR\fR8096868\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP \fR\fR6726824\fP\fP
.IP "\(bu" 2
[New] add \fRdiagnostics_channel\fP to node \fR^14\&.17\fP \fR\fR86c6563\fP\fP
.IP "\(bu" 2
[meta] fix prepublish script \fR\fR697a01e\fP\fP
.PP
.SH "\fRv2\&.3\&.0\fP - 2021-04-24"
.PP
.SS "Commits"
.IP "\(bu" 2
[meta] do not publish github action workflow files \fR\fR060d4bb\fP\fP
.IP "\(bu" 2
[New] add support for \fRnode:\fP prefix, in node 16+ \fR\fR7341223\fP\fP
.IP "\(bu" 2
[actions] use \fRnode/install\fP instead of \fRnode/run\fP; use \fRcodecov\fP action \fR\fR016269a\fP\fP
.IP "\(bu" 2
[patch] remove unneeded \fR\&.0\fP in version ranges \fR\fRcb466a6\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP, \fRtape\fP \fR\fRc9f9c39\fP\fP
.IP "\(bu" 2
[actions] update workflows \fR\fR3ee4a89\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP \fR\fRdee4fed\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP \fR\fR7d046ba\fP\fP
.IP "\(bu" 2
[meta] use \fRprepublishOnly\fP script for npm 7+ \fR\fR149e677\fP\fP
.IP "\(bu" 2
[readme] remove travis badge \fR\fR903b51d\fP\fP
.PP
.SH "\fRv2\&.2\&.0\fP - 2020-11-26"
.PP
.SS "Commits"
.IP "\(bu" 2
[Tests] migrate tests to Github Actions \fR\fRc919f57\fP\fP
.IP "\(bu" 2
[patch] \fRcore\&.json\fP: s/ /\\t/g \fR\fRdb3f685\fP\fP
.IP "\(bu" 2
[Tests] run \fRnyc\fP on all tests \fR\fRb2f925f\fP\fP
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP, \fR@ljharb/eslint-config\fP, \fRaud\fP; add \fRsafe-publish-latest\fP \fR\fR89f02a2\fP\fP
.IP "\(bu" 2
[New] add \fRpath/posix\fP, \fRpath/win32\fP, \fRutil/types\fP \fR\fR77f94f1\fP\fP
.PP
.SH "\fRv2\&.1\&.0\fP - 2020-11-04"
.PP
.SS "Commits"
.IP "\(bu" 2
[Dev Deps] update \fReslint\fP \fR\fR5e0034e\fP\fP
.IP "\(bu" 2
[New] Add \fRdiagnostics_channel\fP \fR\fRc2d83d0\fP\fP
.PP
.SH "\fRv2\&.0\&.0\fP - 2020-09-29"
.PP
.SS "Commits"
.IP "\(bu" 2
v2 implementation \fR\fR865aeb5\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fR5a5e660\fP\fP
.IP "\(bu" 2
Initial commit for v2 \fR\fR5a51524\fP\fP
.IP "\(bu" 2
Tests \fR\fR116eae4\fP\fP
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fRc24388b\fP\fP
.IP "\(bu" 2
[actions] add "Automatic Rebase" and "require allow edits" actions \fR\fR34292db\fP\fP
.IP "\(bu" 2
[Tests] add \fRnpm run lint\fP \fR\fR4f9eeee\fP\fP
.IP "\(bu" 2
[readme] fix travis badges, https all URLs \fR\fRe516a73\fP\fP
.IP "\(bu" 2
[meta] create FUNDING\&.yml \fR\fR1aabebc\fP\fP
.IP "\(bu" 2
[Fix] \fRdomain\fP: domain landed sometime > v0\&.7\&.7 and <= v0\&.7\&.12 \fR\fR2df7d37\fP\fP
.IP "\(bu" 2
[Fix] \fRsys\fP: worked in 0\&.6, not 0\&.7, and 0\&.8+ \fR\fRa75c134\fP\fP
.PP
.SH "\fRv1\&.0\&.2\fP - 2014-09-28"
.PP
.SS "Commits"
.IP "\(bu" 2
simpler \fR\fR66fe90f\fP\fP
.PP
.SH "\fRv1\&.0\&.1\fP - 2014-09-28"
.PP
.SS "Commits"
.IP "\(bu" 2
remove stupid \fR\fRf21f906\fP\fP
.IP "\(bu" 2
update readme \fR\fR1eff0ec\fP\fP
.PP
.SH "v1\&.0\&.0 - 2014-09-28"
.PP
.SS "Commits"
.IP "\(bu" 2
init \fR\fR48e5e76\fP\fP 
.PP

