.TH "md_frontend_2node__modules_2supports-preserve-symlinks-flag_2_c_h_a_n_g_e_l_o_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2supports-preserve-symlinks-flag_2_c_h_a_n_g_e_l_o_g \- Changelog 
.PP


.PP
All notable changes to this project will be documented in this file\&.

.PP
The format is based on \fRKeep a Changelog\fP and this project adheres to \fRSemantic Versioning\fP\&.
.SH "v1\&.0\&.0 - 2022-01-02"
.PP
.SS "Commits"
.IP "\(bu" 2
Tests \fR\fRe2f59ad\fP\fP
.IP "\(bu" 2
Initial commit \fR\fRdc222aa\fP\fP
.IP "\(bu" 2
[meta] do not publish workflow files \fR\fR5ef77f7\fP\fP
.IP "\(bu" 2
npm init \fR\fR992b068\fP\fP
.IP "\(bu" 2
read me \fR\fR6c9afa9\fP\fP
.IP "\(bu" 2
Initial implementation \fR\fR2f98925\fP\fP
.IP "\(bu" 2
[meta] add \fRauto-changelog\fP \fR\fR6c476ae\fP\fP
.IP "\(bu" 2
[Dev Deps] add \fReslint\fP, \fR@ljharb/eslint-config\fP \fR\fRd0fffc8\fP\fP
.IP "\(bu" 2
Only apps should have lockfiles \fR\fRab318ed\fP\fP
.IP "\(bu" 2
[meta] add \fRsafe-publish-latest\fP \fR\fR2bb23b3\fP\fP
.IP "\(bu" 2
[meta] add \fRsideEffects\fP flag \fR\fR600223b\fP\fP 
.PP

