.TH "md_frontend_2node__modules_2date-fns_2docs_2i18n" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2date-fns_2docs_2i18n \- Internationalization 
.PP

.SH "Table of Contents"
.PP
.IP "\(bu" 2
\fBUsage\fP
.IP "\(bu" 2
\fBAdding New Language\fP
.PP
.SH "Usage"
.PP
There are just a few functions that support I18n:

.PP
.IP "\(bu" 2
\fR\fRformat\fP\fP
.IP "\(bu" 2
\fR\fRformatDistance\fP\fP
.IP "\(bu" 2
\fR\fRformatDistanceStrict\fP\fP
.IP "\(bu" 2
\fR\fRformatRelative\fP\fP
.PP

.PP
To use a locale, you need to require it and then pass as an option to a function:

.PP
.PP
.nf
import { formatDistance } from "date\-fns";
// Require Esperanto locale
import { eo } from "date\-fns/locale";

const result = formatDistance(
  new Date(2016, 7, 1),
  new Date(2015, 0, 1),
  { locale: eo }, // Pass the locale as an option
);
//=> 'pli ol 1 jaro'
.fi
.PP

.PP
It might seem complicated to require and pass locales as options, but unlike Moment\&.js which bloats your build with all the locales by default date-fns forces developer to manually require locales when needed\&. To make API simple, we encourage you to write tiny wrappers and use those instead of original functions:

.PP
.PP
.nf
// app/_lib/format\&.js

import { format } from "date\-fns";
import { enGB, eo, ru } from "date\-fns/locale";

const locales = { enGB, eo, ru };

// by providing a default string of 'PP' or any of its variants for `formatStr`
// it will format dates in whichever way is appropriate to the locale
export default function (date, formatStr = "PP") {
  return format(date, formatStr, {
    locale: locales[window\&.__localeId__], // or global\&.__localeId__
  });
}

// Later:

import format from "app/_lib/format";

window\&.__localeId__ = "enGB";
format(friday13, "EEEE d");
//=> 'Friday 13'

window\&.__localeId__ = "eo";
format(friday13, "EEEE d");
//=> 'vendredo 13'

// If the format string is omitted, it will take the default for the locale\&.
window\&.__localeId__ = "enGB";
format(friday13);
//=> Jul 13, 2019

window\&.__localeId__ = "eo";
format(friday13);
//=> 2019\-jul\-13
.fi
.PP
.SH "Adding New Language"
.PP
At the moment there is no definitive guide, so if you feel brave enough, use this quick guide:

.PP
.IP "\(bu" 2
First of all, \fRcreate an issue\fP so you won't overlap with others\&.
.IP "\(bu" 2
A detailed explanation of how to \fRadd a new locale\fP\&.
.IP "\(bu" 2
Use \fREnglish locale\fP as the basis and then incrementally adjust the tests and the code\&.
.IP "\(bu" 2
Directions on \fRadding a locale with the same language as another locale\fP\&.
.IP "\(bu" 2
If you have questions or need guidance, leave a comment in the issue\&.
.PP

.PP
Thank you for your support! 
