.TH "md_frontend_2node__modules_2decimal_8js-light_2_c_h_a_n_g_e_l_o_g" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_frontend_2node__modules_2decimal_8js-light_2_c_h_a_n_g_e_l_o_g \- 2\&.5\&.1 
.PP


.PP
.IP "\(bu" 2
30/09/2020
.IP "\(bu" 2
Correct initial \fRsqrt\fP estimate\&.
.PP
.SS "2\&.5\&.0"
.IP "\(bu" 2
16/10/2018
.IP "\(bu" 2
Add default export to \fIdecimal\&.d\&.ts\fP\&.
.IP "\(bu" 2
Add \fRSymbol\&.for('nodejs\&.util\&.inspect\&.custom')\fP to \fIdecimal\&.mjs\fP\&.
.PP
.SS "2\&.4\&.1"
.IP "\(bu" 2
24/05/2018
.IP "\(bu" 2
Add \fRbrowser\fP field to \fIpackage\&.json\fP\&.
.PP
.SS "2\&.4\&.0"
.IP "\(bu" 2
22/05/2018
.IP "\(bu" 2
Amend \fI\&.mjs\fP exports\&.
.IP "\(bu" 2
Remove extension from \fRmain\fP field in \fIpackage\&.json\fP\&.
.PP
.SS "2\&.3\&.1"
.IP "\(bu" 2
13/11/2017
.IP "\(bu" 2
Add constructor properties to typings\&.
.IP "\(bu" 2
Amend \fRLN10\fP section of \fIdoc/API\&.html\fP\&.
.PP
.SS "2\&.3\&.0"
.IP "\(bu" 2
26/09/2017
.IP "\(bu" 2
Add \fIbignumber\&.mjs\fP\&.
.PP
.SS "2\&.2\&.5"
.IP "\(bu" 2
08/09/2017
.IP "\(bu" 2
#5 Fix import\&.
.PP
.SS "2\&.2\&.4"
.IP "\(bu" 2
15/08/2017
.IP "\(bu" 2
Add TypeScript type declaration file, \fIdecimal\&.d\&.ts\fP
.IP "\(bu" 2
Correct \fRtoPositive\fP and \fRtoNegative\fP examples
.PP
.SS "2\&.2\&.3"
.IP "\(bu" 2
04/05/2017
.IP "\(bu" 2
Fix \fIREADME\fP badge
.PP
.SS "2\&.2\&.2"
05/04/2017
.IP "\(bu" 2
\fRDecimal\&.default\fP to \fRDecimal['default']\fP IE8 issue
.PP
.SS "2\&.2\&.1"
10/03/2017
.IP "\(bu" 2
Remove \fRtonum\fP from documentation
.PP
.SS "2\&.2\&.0"
10/01/2017
.IP "\(bu" 2
Add \fRexponent\fP method
.PP
.SS "2\&.0\&.2"
12/12/2016
.IP "\(bu" 2
npm publish
.PP
.SS "2\&.0\&.1"
12/12/2016
.IP "\(bu" 2
Filename-casing issue
.PP
.SS "2\&.0\&.0"
11/12/2016
.IP "\(bu" 2
Make \fRLN10\fP configurable at runtime
.IP "\(bu" 2
Reduce \fRLN10\fP default precision
.IP "\(bu" 2
Remove \fRceil\fP, \fRfloor\fP, \fRmin\fP, \fRmax\fP and \fRtruncated\fP
.IP "\(bu" 2
Rename \fRdivToInt\fP to \fRidiv\fP, \fRtoSD\fP to \fRtosd\fP, \fRtoDP\fP to \fRtodp\fP, \fRisInt\fP to \fRisint\fP, \fRisNeg\fP to \fRisneg\fP, \fRisPos\fP to \fRispos\fP and \fRround\fP to \fRtoInteger\fP
.IP "\(bu" 2
Rename some test files
.IP "\(bu" 2
Add \fRset\fP as alias to \fRconfig\fP
.IP "\(bu" 2
Support ES6 import shims
.IP "\(bu" 2
Add to README
.PP
.SS "1\&.0\&.4"
28/02/2016
.IP "\(bu" 2
Add to README
.PP
.SS "1\&.0\&.3"
25/02/2016
.IP "\(bu" 2
Add to README
.PP
.SS "1\&.0\&.2"
25/02/2016
.IP "\(bu" 2
Correct url
.IP "\(bu" 2
Amend \&.travis\&.yml as Node\&.js v0\&.6 doesn't include \fRprocess\&.hrtime\fP which is used in testing\&.
.PP
.SS "1\&.0\&.0"
24/02/2016
.IP "\(bu" 2
Initial release 
.PP

