.TH "middleware.logging_middleware" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
middleware.logging_middleware
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSocketIOLogger\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetup_logging\fP ()"
.br
.ti -1c
.RI "\fBlog_request_middleware\fP (\fBapp\fP)"
.br
.in -1c
.SS "Constants"

.in +1c
.ti -1c
.RI "\fBsocketio_logger\fP = \fBSocketIOLogger\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Logging Middleware
Proporciona logging estructurado y profesional para la aplicación

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "middleware\&.logging_middleware\&.log_request_middleware ( app)"

.PP
.nf
Middleware para logging de requests HTTP

.fi
.PP
 
.SS "middleware\&.logging_middleware\&.setup_logging ()"

.PP
.nf
Configurar el sistema de logging de la aplicación

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
