.TH "middleware.logging_middleware.SocketIOLogger" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
middleware.logging_middleware.SocketIOLogger
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBlog_connection\fP (self, sid, username=None)"
.br
.ti -1c
.RI "\fBlog_disconnection\fP (self, sid, username=None)"
.br
.ti -1c
.RI "\fBlog_join_room\fP (self, sid, room_id, username=None)"
.br
.ti -1c
.RI "\fBlog_message_sent\fP (self, username, room_id, message_length)"
.br
.ti -1c
.RI "\fBlog_error\fP (self, event, error, sid=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger('chatapp\&.socketio')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Logger especializado para eventos de Socket\&.IO

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "middleware\&.logging_middleware\&.SocketIOLogger\&.log_connection ( self,  sid,  username = \fRNone\fP)"

.PP
.nf
Log de nueva conexión Socket\&.IO
.fi
.PP
 
.SS "middleware\&.logging_middleware\&.SocketIOLogger\&.log_disconnection ( self,  sid,  username = \fRNone\fP)"

.PP
.nf
Log de desconexión Socket\&.IO
.fi
.PP
 
.SS "middleware\&.logging_middleware\&.SocketIOLogger\&.log_error ( self,  event,  error,  sid = \fRNone\fP)"

.PP
.nf
Log de error en Socket\&.IO
.fi
.PP
 
.SS "middleware\&.logging_middleware\&.SocketIOLogger\&.log_join_room ( self,  sid,  room_id,  username = \fRNone\fP)"

.PP
.nf
Log de unión a sala
.fi
.PP
 
.SS "middleware\&.logging_middleware\&.SocketIOLogger\&.log_message_sent ( self,  username,  room_id,  message_length)"

.PP
.nf
Log de mensaje enviado
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
