.TH "repositories.private_chat_repository.PrivateChatRepository" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repositories.private_chat_repository.PrivateChatRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrepositories\&.base_repository\&.BaseRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Optional[str] \fBcreate_private_chat\fP (self, str user1_username, str user2_username, bool is_temporary=True)"
.br
.ti -1c
.RI "Optional[Dict] \fBget_private_chat\fP (self, str chat_id)"
.br
.ti -1c
.RI "Optional[Dict] \fBfind_chat_between_users\fP (self, str user1_username, str user2_username)"
.br
.in -1c

Public Member Functions inherited from \fBrepositories\&.base_repository\&.BaseRepository\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "Optional[Any] \fBexecute_query\fP (self, str query, tuple params=None, bool fetch_one=False, bool fetch_all=False)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBrepositories\&.base_repository\&.BaseRepository\fP
.in +1c
.ti -1c
.RI "\fBdb_manager\fP = db_manager"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
