.TH "repositories.base_repository.UserRepository" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repositories.base_repository.UserRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrepositories\&.base_repository\&.BaseRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Optional[Dict] \fBfind_by_username\fP (self, str username)"
.br
.ti -1c
.RI "Optional[Dict] \fBfind_by_id\fP (self, str user_id)"
.br
.ti -1c
.RI "str \fBcreate_user\fP (self, str username, str email, str password_hash)"
.br
.ti -1c
.RI "None \fBupdate_last_login\fP (self, str user_id)"
.br
.in -1c

Public Member Functions inherited from \fBrepositories\&.base_repository\&.BaseRepository\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "Optional[Any] \fBexecute_query\fP (self, str query, tuple params=None, bool fetch_one=False, bool fetch_all=False)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBrepositories\&.base_repository\&.BaseRepository\fP
.in +1c
.ti -1c
.RI "\fBdb_manager\fP = db_manager"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Repository para operaciones de usuarios

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " str repositories\&.base_repository\&.UserRepository\&.create_user ( self, str username, str email, str password_hash)"

.PP
.nf
Crear nuevo usuario
.fi
.PP
 
.SS " Optional[Dict] repositories\&.base_repository\&.UserRepository\&.find_by_id ( self, str user_id)"

.PP
.nf
Buscar usuario por ID
.fi
.PP
 
.SS " Optional[Dict] repositories\&.base_repository\&.UserRepository\&.find_by_username ( self, str username)"

.PP
.nf
Buscar usuario por username
.fi
.PP
 
.SS " None repositories\&.base_repository\&.UserRepository\&.update_last_login ( self, str user_id)"

.PP
.nf
Actualizar último login
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
