.TH "repositories.base_repository.MessageRepository" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repositories.base_repository.MessageRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrepositories\&.base_repository\&.BaseRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Optional[str] \fBsave_message\fP (self, str user_id, str room_id, str content)"
.br
.ti -1c
.RI "List[Dict] \fBget_messages_by_room\fP (self, str room_id, int limit=50, int offset=0)"
.br
.ti -1c
.RI "int \fBget_message_count_by_room\fP (self, str room_id)"
.br
.ti -1c
.RI "bool \fBdelete_message\fP (self, str message_id, str user_id)"
.br
.in -1c

Public Member Functions inherited from \fBrepositories\&.base_repository\&.BaseRepository\fP
.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "Optional[Any] \fBexecute_query\fP (self, str query, tuple params=None, bool fetch_one=False, bool fetch_all=False)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBrepositories\&.base_repository\&.BaseRepository\fP
.in +1c
.ti -1c
.RI "\fBdb_manager\fP = db_manager"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Repository para operaciones de mensajes

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " bool repositories\&.base_repository\&.MessageRepository\&.delete_message ( self, str message_id, str user_id)"

.PP
.nf
Soft delete de mensaje (solo el autor puede borrar)
.fi
.PP
 
.SS " int repositories\&.base_repository\&.MessageRepository\&.get_message_count_by_room ( self, str room_id)"

.PP
.nf
Contar mensajes en una sala
.fi
.PP
 
.SS " List[Dict] repositories\&.base_repository\&.MessageRepository\&.get_messages_by_room ( self, str room_id, int  limit = \fR50\fP, int  offset = \fR0\fP)"

.PP
.nf
Obtener mensajes de una sala con paginación
.fi
.PP
 
.SS " Optional[str] repositories\&.base_repository\&.MessageRepository\&.save_message ( self, str user_id, str room_id, str content)"

.PP
.nf
Guardar nuevo mensaje
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
