.TH "repositories.friend_repository.FriendRepository" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repositories.friend_repository.FriendRepository
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBremove_friend\fP (self, str user_id, str friend_id)"
.br
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "Optional[str] \fBsend_request\fP (self, str sender_id, str receiver_id)"
.br
.ti -1c
.RI "bool \fBrespond_request\fP (self, str request_id, str status)"
.br
.ti -1c
.RI "List[Dict] \fBget_pending_requests\fP (self, str user_id)"
.br
.ti -1c
.RI "List[Dict] \fBget_sent_requests\fP (self, str user_id)"
.br
.ti -1c
.RI "List[Dict] \fBget_friends\fP (self, str user_id)"
.br
.ti -1c
.RI "List[Dict] \fBsearch_users\fP (self, str query_str, List[str] exclude_ids, int limit=10)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdb_manager\fP = db_manager"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
