.TH "repositories.base_repository" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repositories.base_repository
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseRepository\fP"
.br
.ti -1c
.RI "class \fBUserRepository\fP"
.br
.ti -1c
.RI "class \fBMessageRepository\fP"
.br
.ti -1c
.RI "class \fBRoomRepository\fP"
.br
.in -1c
.SS "Constants"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Base Repository Class
Implementa el patrón Repository para abstracción de acceso a datos

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
