.TH "services.friend_service.FriendService" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services.friend_service.FriendService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBremove_friend\fP (self, str user_id, str friend_id)"
.br
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "str \fBsend_request\fP (self, str sender_id, str receiver_id)"
.br
.ti -1c
.RI "bool \fBrespond_request\fP (self, str request_id, str status)"
.br
.ti -1c
.RI "\fBget_pending_requests\fP (self, str user_id)"
.br
.ti -1c
.RI "\fBget_sent_requests\fP (self, str user_id)"
.br
.ti -1c
.RI "\fBget_friends\fP (self, str user_id)"
.br
.ti -1c
.RI "\fBsearch_users\fP (self, str query_str, list exclude_ids, int limit=10)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrepo\fP = \fBFriendRepository\fP()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
