.TH "services.chat_service.ChatService" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services.chat_service.ChatService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBget_user_rooms\fP (self, user_id)"
.br
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "Optional[Dict] \fBget_or_create_individual_room\fP (self, str username_1, str username_2, bool is_temporary=False)"
.br
.ti -1c
.RI "bool \fBdelete_room\fP (self, str room_id)"
.br
.ti -1c
.RI "int \fBcleanup_temporary_rooms\fP (self, str user_id)"
.br
.ti -1c
.RI "Optional[Dict] \fBsend_message\fP (self, str username, str room_id, str content)"
.br
.ti -1c
.RI "List[Dict] \fBget_room_messages\fP (self, str room_id, int page=1, int per_page=50)"
.br
.ti -1c
.RI "List[Dict] \fBget_available_rooms\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmessage_repository\fP = \fBMessageRepository\fP()"
.br
.ti -1c
.RI "\fBroom_repository\fP = \fBRoomRepository\fP()"
.br
.ti -1c
.RI "\fBuser_repository\fP = \fBUserRepository\fP()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "str \fB_sanitize_message_content\fP (self, str content)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS " str services\&.chat_service\&.ChatService\&._sanitize_message_content ( self, str content)\fR [protected]\fP"

.PP
.nf
Sanitizar contenido de mensajes
Remover caracteres potencialmente peligrosos

.fi
.PP
 
.SS " int services\&.chat_service\&.ChatService\&.cleanup_temporary_rooms ( self, str user_id)"

.PP
.nf
Desactiva todos los chats temporales donde participa el usuario
.fi
.PP
 
.SS " bool services\&.chat_service\&.ChatService\&.delete_room ( self, str room_id)"

.PP
.nf
Eliminar/desactivar una sala
.fi
.PP
 
.SS " List[Dict] services\&.chat_service\&.ChatService\&.get_available_rooms ( self)"

.PP
.nf
Obtener todas las salas disponibles

Returns:
    Lista de salas en formato frontend

.fi
.PP
 
.SS " Optional[Dict] services\&.chat_service\&.ChatService\&.get_or_create_individual_room ( self, str username_1, str username_2, bool  is_temporary = \fRFalse\fP)"

.PP
.nf
Busca o crea una sala individual entre dos usuarios
.fi
.PP
 
.SS " List[Dict] services\&.chat_service\&.ChatService\&.get_room_messages ( self, str room_id, int  page = \fR1\fP, int  per_page = \fR50\fP)"

.PP
.nf
Obtener mensajes de una sala con paginación

Args:
    room_id: ID de la sala
    page: Número de página (empezando en 1)
    per_page: Mensajes por página
    
Returns:
    Lista de mensajes en formato frontend

.fi
.PP
 
.SS "services\&.chat_service\&.ChatService\&.get_user_rooms ( self,  user_id)"

.PP
.nf
Devuelve todas las salas (rooms) en las que el usuario participa, públicas e individuales\&.

.fi
.PP
 
.SS " Optional[Dict] services\&.chat_service\&.ChatService\&.send_message ( self, str username, str room_id, str content)"

.PP
.nf
Enviar un mensaje a una sala

Args:
    username: Username del remitente
    room_id: ID de la sala
    content: Contenido del mensaje
    
Returns:
    Dict con información del mensaje enviado o None si hay error

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
