.TH "services.auth_service.AuthService" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services.auth_service.AuthService
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Optional[str] \fBregister_user\fP (self, str username, str email, str password)"
.br
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "Optional[Dict] \fBauthenticate_user\fP (self, str username, str password)"
.br
.ti -1c
.RI "Optional[Dict] \fBget_user_by_username\fP (self, str username)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuser_repository\fP = \fBUserRepository\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Servicio de autenticación
Encapsula la lógica de negocio para login, logout, etc\&.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " Optional[Dict] services\&.auth_service\&.AuthService\&.authenticate_user ( self, str username, str password)"

.PP
.nf
Autenticar usuario con username y password

Args:
    username: Username del usuario
    password: Password en texto plano
    
Returns:
    Dict con información del usuario si es válido, None si no

.fi
.PP
 
.SS " Optional[Dict] services\&.auth_service\&.AuthService\&.get_user_by_username ( self, str username)"

.PP
.nf
Obtener información de usuario por username
.fi
.PP
 
.SS " Optional[str] services\&.auth_service\&.AuthService\&.register_user ( self, str username, str email, str password)"

.PP
.nf
Registrar usuario nuevo
Args:
    username: Username del usuario
    email: Email del usuario
    password: Password en texto plano
Returns:
    ID del usuario creado o None

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
