.TH "services.chat_service" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services.chat_service
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChatService\fP"
.br
.in -1c
.SS "Constants"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Chat Service
Maneja toda la lógica de negocio relacionada con mensajes y salas

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
