.TH "tests.test_validators" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.test_validators
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestLoginValidator\fP"
.br
.ti -1c
.RI "class \fBTestMessageValidator\fP"
.br
.ti -1c
.RI "class \fBTestJoinRoomValidator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Unit Tests for Validators
Tests de validación de datos de entrada

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
