.TH "tests.test_services" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.test_services
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestAuthService\fP"
.br
.ti -1c
.RI "class \fBTestChatService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Unit Tests for Services
Tests de lógica de negocio

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
