.TH "tests.test_services.TestChatService" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.test_services.TestChatService
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP (self)"
.br
.ti -1c
.RI "\fBtest_send_message_success\fP (self)"
.br
.ti -1c
.RI "\fBtest_send_message_room_not_found\fP (self)"
.br
.ti -1c
.RI "\fBtest_send_message_empty_content\fP (self)"
.br
.ti -1c
.RI "\fBtest_get_room_messages\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmock_message_repo\fP = Mock()"
.br
.ti -1c
.RI "\fBmock_room_repo\fP = Mock()"
.br
.ti -1c
.RI "\fBmock_user_repo\fP = Mock()"
.br
.ti -1c
.RI "\fBmock_message_repo_class\fP = patcher1\&.start()"
.br
.ti -1c
.RI "\fBmock_room_repo_class\fP = patcher2\&.start()"
.br
.ti -1c
.RI "\fBmock_user_repo_class\fP = patcher3\&.start()"
.br
.ti -1c
.RI "\fBchat_service\fP = ChatService()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Tests para ChatService
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "tests\&.test_services\&.TestChatService\&.setUp ( self)"

.PP
.nf
Configurar mocks para cada test
.fi
.PP
 
.SS "tests\&.test_services\&.TestChatService\&.test_get_room_messages ( self)"

.PP
.nf
Test de obtención de mensajes
.fi
.PP
 
.SS "tests\&.test_services\&.TestChatService\&.test_send_message_empty_content ( self)"

.PP
.nf
Test con contenido vacío
.fi
.PP
 
.SS "tests\&.test_services\&.TestChatService\&.test_send_message_room_not_found ( self)"

.PP
.nf
Test con sala no encontrada
.fi
.PP
 
.SS "tests\&.test_services\&.TestChatService\&.test_send_message_success ( self)"

.PP
.nf
Test de envío de mensaje exitoso
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
