.TH "tests.conftest" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.conftest
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmock_db_connection\fP ()"
.br
.ti -1c
.RI "\fBsample_user_data\fP ()"
.br
.ti -1c
.RI "\fBsample_message_data\fP ()"
.br
.ti -1c
.RI "\fBsample_room_data\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Test Configuration
Configuración base para tests de la aplicación

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "tests\&.conftest\&.mock_db_connection ()"

.PP
.nf
Mock de conexión a base de datos para tests
.fi
.PP
 
.SS "tests\&.conftest\&.sample_message_data ()"

.PP
.nf
Datos de mensaje de ejemplo para tests
.fi
.PP
 
.SS "tests\&.conftest\&.sample_room_data ()"

.PP
.nf
Datos de sala de ejemplo para tests
.fi
.PP
 
.SS "tests\&.conftest\&.sample_user_data ()"

.PP
.nf
Datos de usuario de ejemplo para tests
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
