.TH "tests.test_validators.TestJoinRoomValidator" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.test_validators.TestJoinRoomValidator
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_valid_join_data\fP (self)"
.br
.ti -1c
.RI "\fBtest_invalid_room_id\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Tests para JoinRoomValidator
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "tests\&.test_validators\&.TestJoinRoomValidator\&.test_invalid_room_id ( self)"

.PP
.nf
Test con ID de sala inválido
.fi
.PP
 
.SS "tests\&.test_validators\&.TestJoinRoomValidator\&.test_valid_join_data ( self)"

.PP
.nf
Test con datos válidos para unirse a sala
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
