.TH "tests.test_validators.TestLoginValidator" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.test_validators.TestLoginValidator
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_valid_login_data\fP (self)"
.br
.ti -1c
.RI "\fBtest_missing_username\fP (self)"
.br
.ti -1c
.RI "\fBtest_missing_password\fP (self)"
.br
.ti -1c
.RI "\fBtest_invalid_username_characters\fP (self)"
.br
.ti -1c
.RI "\fBtest_username_too_short\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Tests para LoginValidator
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "tests\&.test_validators\&.TestLoginValidator\&.test_invalid_username_characters ( self)"

.PP
.nf
Test con caracteres inválidos en username
.fi
.PP
 
.SS "tests\&.test_validators\&.TestLoginValidator\&.test_missing_password ( self)"

.PP
.nf
Test con password faltante
.fi
.PP
 
.SS "tests\&.test_validators\&.TestLoginValidator\&.test_missing_username ( self)"

.PP
.nf
Test con username faltante
.fi
.PP
 
.SS "tests\&.test_validators\&.TestLoginValidator\&.test_username_too_short ( self)"

.PP
.nf
Test con username muy corto
.fi
.PP
 
.SS "tests\&.test_validators\&.TestLoginValidator\&.test_valid_login_data ( self)"

.PP
.nf
Test con datos válidos
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
