.TH "tests.test_validators.TestMessageValidator" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.test_validators.TestMessageValidator
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_valid_message_data\fP (self)"
.br
.ti -1c
.RI "\fBtest_message_content_sanitization\fP (self)"
.br
.ti -1c
.RI "\fBtest_empty_message\fP (self)"
.br
.ti -1c
.RI "\fBtest_message_too_long\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Tests para MessageValidator
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "tests\&.test_validators\&.TestMessageValidator\&.test_empty_message ( self)"

.PP
.nf
Test con mensaje vacío
.fi
.PP
 
.SS "tests\&.test_validators\&.TestMessageValidator\&.test_message_content_sanitization ( self)"

.PP
.nf
Test de sanitización de contenido
.fi
.PP
 
.SS "tests\&.test_validators\&.TestMessageValidator\&.test_message_too_long ( self)"

.PP
.nf
Test con mensaje muy largo
.fi
.PP
 
.SS "tests\&.test_validators\&.TestMessageValidator\&.test_valid_message_data ( self)"

.PP
.nf
Test con datos de mensaje válidos
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
