.TH "utils.validators.BaseValidator" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.validators.BaseValidator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fButils\&.validators\&.JoinRoomValidator\fP, \fButils\&.validators\&.LoginValidator\fP, and \fButils\&.validators\&.MessageValidator\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "str \fBvalidate_string\fP (Any value, str field_name, int min_length=1, int max_length=255, bool required=True)"
.br
.ti -1c
.RI "str \fBvalidate_username\fP (Any username)"
.br
.ti -1c
.RI "str \fBvalidate_room_id\fP (Any room_id)"
.br
.ti -1c
.RI "str \fBvalidate_message_content\fP (Any content)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Clase base para validadores
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS " str utils\&.validators\&.BaseValidator\&.validate_message_content (Any content)\fR [static]\fP"

.PP
.nf
Validar contenido de mensaje
.fi
.PP
 
.SS " str utils\&.validators\&.BaseValidator\&.validate_room_id (Any room_id)\fR [static]\fP"

.PP
.nf
Validar ID de sala
.fi
.PP
 
.SS " str utils\&.validators\&.BaseValidator\&.validate_string (Any value, str field_name, int  min_length = \fR1\fP, int  max_length = \fR255\fP, bool  required = \fRTrue\fP)\fR [static]\fP"

.PP
.nf
Validar campo string
.fi
.PP
 
.SS " str utils\&.validators\&.BaseValidator\&.validate_username (Any username)\fR [static]\fP"

.PP
.nf
Validar username con reglas específicas
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
