.TH "utils.database.DatabaseManager" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.database.DatabaseManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__new__\fP (cls)"
.br
.ti -1c
.RI "\fBget_connection\fP (self)"
.br
.ti -1c
.RI "\fBreturn_connection\fP (self, connection)"
.br
.ti -1c
.RI "\fBclose_all_connections\fP (self)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_initialize_pool\fP (self)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fB_instance\fP = None"
.br
.ti -1c
.RI "\fB_pool\fP = None"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Singleton pattern para manejar el pool de conexiones de PostgreSQL

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "utils\&.database\&.DatabaseManager\&._initialize_pool ( self)\fR [protected]\fP"

.PP
.nf
Inicializar el pool de conexiones
.fi
.PP
 
.SS "utils\&.database\&.DatabaseManager\&.close_all_connections ( self)"

.PP
.nf
Cerrar todas las conexiones del pool
.fi
.PP
 
.SS "utils\&.database\&.DatabaseManager\&.get_connection ( self)"

.PP
.nf
Obtener una conexión del pool
.fi
.PP
 
.SS "utils\&.database\&.DatabaseManager\&.return_connection ( self,  connection)"

.PP
.nf
Devolver una conexión al pool
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
