.TH "utils.database" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.database
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDatabaseManager\fP"
.br
.in -1c
.SS "Constants"

.in +1c
.ti -1c
.RI "\fBlevel\fP"
.br
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "\fBdb_manager\fP = \fBDatabaseManager\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Database Connection Pool Manager
Implements connection pooling for PostgreSQL to improve performance

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
