.TH "utils.validators.ValidationError" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.validators.ValidationError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Excepción personalizada para errores de validación
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
