.TH "utils.validators" 3 "Version 0.1" "Chat-ME!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.validators
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBValidationError\fP"
.br
.ti -1c
.RI "class \fBBaseValidator\fP"
.br
.ti -1c
.RI "class \fBLoginValidator\fP"
.br
.ti -1c
.RI "class \fBMessageValidator\fP"
.br
.ti -1c
.RI "class \fBJoinRoomValidator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Validation Schemas
Define esquemas de validación para datos de entrada

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Chat-ME! from the source code\&.
